### ISSUE TITLE
Immer overwrites properties

### ISSUE THREAD

**Issue by yasinitskyi** [immerjs/immer#1000]
Trying to create alternative object build with produce, but everything comes down to immer overwriting properties every time in the loop:
Original:
![Screen Shot 2022-12-09 at 4 01 45 PM](https://user-images.githubusercontent.com/67145411/206654202-fd0c58ce-7f86-4077-aed0-0162ef256e25.png)
Produce alternative:
![Screen Shot 2022-12-09 at 4 04 06 PM](https://user-images.githubusercontent.com/67145411/206654298-a2491e6e-500e-4e05-8303-610aa439ca29.png)
Can someone explain to me how to make alternative version to be working as one with spreads? Thank you!

**Comment by mweststrate** [comment]
Can you post a code snippet instead and examples with what you are trying to achieve and get? Images aren't editable. But I imagine it'd be something like this  `draft[canvas.format.platformType][canvas.format.platform].groups[group.name] = group` in the inner forEach.

**Comment by yasinitskyi** [comment]
@mweststrate it will throw an Error since the draft is empty in the beginning, as you can see, it is an empty object passed as initial value for produce, so once you tried to dig through the chain of properties it will exit immediately.
This is what i am getting with version with spreads:
![telegram-cloud-photo-size-5-6095916125268325584-y](https://user-images.githubusercontent.com/67145411/206667780-d8f8dcab-bfb6-4eb4-b542-40f6524b34b8.jpg)
This is produce:
![telegram-cloud-photo-size-5-6095916125268325585-y](https://user-images.githubusercontent.com/67145411/206667831-4fe5a833-5369-4fa5-b6ea-e9b25563a183.jpg)
Code snippets:
`processPurposes() {
    const platforms = {};
    this.layout.compositionGroups.forEach((group) => {
      group.canvasses.forEach((canvas) => {
        platforms[canvas.format.platformType] = {
          ...platforms[canvas.format.platformType],
          [canvas.format.platform]: {
            groups: {
              ...platforms[canvas.format.platformType]?.[canvas.format.platform]?.groups,
              [group.name]: group,
            },
          },
        };
      });
    });
    console.log('platforms: ', platforms);
  }`
`processPurposesNew() {
    const basePurposes = {};
    const handlePurposes = produce((draft) => {
      this.layout.compositionGroups.forEach((group) => {
        group.canvasses.forEach((canvas) => {
          draft[canvas.format.platformType] = {
            [canvas.format.platform]: {
              groups: {
                [group.name]: group,
              },
            },
          };
        });
      });
    });
    const nextPurposes = handlePurposes(basePurposes);
    console.log('platforms: ', nextPurposes);
  }`
Data:
`[
compositionGroup1: {
      name: horizontal
      canvasses: [{format: {platformType: social_media, platform: GDN}}]
    }
    compositionGroup2: {
      name: square
      canvasses: [{format: {platformType: social_media, platform: INSTAGRAM}}]
    }
]`

**Comment by yasinitskyi** [comment]
@mweststrate Any suggestions how to make it clean, example of code snippet maybe? Or I dont need produce in this example and can use spread version of it? I just imagine if nesting will be even more complex... Thank you

**Comment by mweststrate** [comment]
```
const x = a.b.c;
if (!x.y) {
  x.y = {}
}
x.y[z] = w
```

or: `(a.b.c.y ??= {})[z] = w`, but the readability improvement could be contested
