### ISSUE TITLE
Maximum call stack size exceeded error in production mode

### ISSUE THREAD

**Issue by toy9986619** [immerjs/immer#1030]
## 🐛 Bug Report

I make a react component using styled (from @mui/material/styles, @emotion), it will crash when the reducer change.
If the data use a native div or "Box" component (from material-UI), it will not crash.

It doesn't crash when I use development mode.

## Link to repro

link: https://toy9986619.github.io/immer-issue/
repo: https://github.com/toy9986619/immer-issue

## To Reproduce

* insert an styled component instance create from emotion to immer state.

## Observed behavior

An error comes from immer code

Uncaught RangeError: Maximum call stack size exceeded
    at Object.hasOwnProperty (<anonymous>)
    at common.ts:45:25

![image](https://user-images.githubusercontent.com/19423708/229088872-f6420e8b-9ba0-4332-91e3-1e928c02ce37.png)

![image](https://user-images.githubusercontent.com/19423708/229088928-abee6beb-74ec-4d31-97f4-08e16dc643fc.png)

## Expected behavior

Will not have error

## Environment

- **Immer version:** 9.0.16
- [ ] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by toy9986619** [comment]
Sorry, I need to check this issue is from redux-toolkit lib or immer first.

**Comment by mweststrate** [comment]
```
actions.addHintMsg({
   [immerable]: false
   ...
```

or in `addHintMsg` call `Object.freeze` on the incoming object first will probably do the trick

**Comment by toy9986619** [comment]
Thanks for your reply, I agree the project is too big now.
I know there are some unsafe actions when using redux, but it is a base code in our project now.
I roll back the redux reducer to use the mutable reducer. I avoid the issue now.

I will try to narrow down the test and find out if it can reproduce or not. 

I think I can close the issue now.

**Comment by markerikson** [comment]
@toy9986619 : yeah, it sounds like you're trying to put a _component instance_ or similar into the Redux state, and **you absolutely _should not ever_ do that!**

- https://redux.js.org/style-guide/#do-not-put-non-serializable-values-in-state-or-actions
