### ISSUE TITLE
underfined is not a function

### ISSUE THREAD

**Issue by LouisMuriuki** [immerjs/immer#1048]
## 🐛 Bug Report
I am using immer in my react Native app and I updated immer to version "^10.0.1", before I was using version "^9.0.18". I also updated my expo version which somehow enabled hermes by default. This triggers the error whenever I pass data to my reducers "underfined is not a function"

This is how I was using it across all my reducers
`addProducts: (state, action) => {
      return produce(state, (draftState) => {
        draftState.products = action.payload;
      });
    },`

I decided to downgrade back to version 9.0.18, and now it works again like before without the error

**Comment by mweststrate** [comment]
check the release notes
