### ISSUE TITLE
Eliminate the `?.` operator for some lower-end devices.

### ISSUE THREAD

**Issue by wenerme** [immerjs/immer#1049]
## 🚀 Feature Proposal

I want to use immer in wechat miniprogram, but the immer container `?.` which is not supported.

## Motivation

Just eliminate the `?.` by config bundler ?

## Can this be solved in user-land code?

Rebundle ?

**Comment by markerikson** [comment]
Immer 10 includes a `legacy-esm` build artifact that has been transpiled to ES2017, which includes removing any `?.` uses.  You'll want to configure your bundler to use that (via some kind of alias or resolution bundler config option):

https://unpkg.com/browse/immer@10.0.2/dist/immer.legacy-esm.js

**Comment by markerikson** [comment]
Yes, that's my point.  You'd need to configure your _bundler_ so that any attempt to import `"immer"` actually imports `"node_modules/immer/dist/immer.legacy-esm.js"` instead.

**Comment by wenerme** [comment]
Thanks, after pnpm patch, works as expected.

**Comment by christopher-francisco** [comment]
@wenerme what's the patch that fixed it?
