### ISSUE TITLE
Is there a possibility to use immear as one-liner?

### ISSUE THREAD

**Issue by max-prtsr** [immerjs/immer#1059]
## 🙋‍♂ Question

I personally don't like this code taking 3 lines instead of one 

```ts
    const newRecords = produce(scheduleRecords, (draft) => {
      draft[index] = updatedRecord
    })
```

I would like to have
```ts
    const newRecords = produce(scheduleRecords, (draft) => draft[index] = updatedRecord)
```

but I got a TS error 
```
TS2769: No overload matches this call.   
The last overload gave the following error.     
Type 'Partial<Record>' is not assignable to type 'ValidRecipeReturnType<WritableDraft<Partial<Record>>[]>'. 
```

## Environment

v10.0.2
We only accept questions against the latest Immer version.

**Comment by mweststrate** [comment]
=> void ...

**Comment by lyluongthien** [comment]
> ## 🙋‍♂ Question
> I personally don't like this code taking 3 lines instead of one
> 
> ```ts
>     const newRecords = produce(scheduleRecords, (draft) => {
>       draft[index] = updatedRecord
>     })
> ```
> 
> I would like to have
> 
> ```ts
>     const newRecords = produce(scheduleRecords, (draft) => draft[index] = updatedRecord)
> ```
> 
> but I got a TS error
> 
> ```
> TS2769: No overload matches this call.   
> The last overload gave the following error.     
> Type 'Partial<Record>' is not assignable to type 'ValidRecipeReturnType<WritableDraft<Partial<Record>>[]>'. 
> ```
> 
> ## Environment
> v10.0.2 We only accept questions against the latest Immer version.

@max-prtsr 
Of course, you can achieve that with the [comma operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_operator) of javascript. [For instance:](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzmKEAmBXAxgUzgXzgDNUQ4AiUEHKcgbgCgGsIA7AZ3jRyIEMMANjACyATwDKGAEbiYvGHgC8iBnDjsI1WVGCsA5gC4KRCBHIAaOA3xMWHeKxwB3AEo4WUNOzjKU6bDgAFNx8giIS0rLyOJbBULxEMACUPgB8cHEJMADa5BpaMDr65AC6PhQYYGjRaG4eaBZwAG4QwGhwAAxJSQxAA)

```typescript
import { produce } from "immer";

const defaultMySubState = {
  someString: "foo", 
}

const newRecords = produce(defaultMySubState, (draft) => (draft["someString"] = "updatedRecord", void 0))

```
But to have better readable codes, I will never use this shortcode in a team project 😂. I think we should avoid it.

**Comment by max-prtsr** [comment]
@mweststrate @lyluongthien thank you guys

**Comment by mweststrate** [comment]
To clarify my previous message, no comma operator is needed here, since void can be used directly as operator. So it'd become:

`const newRecords = produce(scheduleRecords, (draft) => void draft[index] = updatedRecord)`
