### ISSUE TITLE
Exception thrown when modifying object with Symbol

### ISSUE THREAD

**Issue by ninesunsabiu** [immerjs/immer#1074]
## 🐛 Bug Report
I am using immer for state transformation in React, and I have a data object with a Symbol property. However, when modifying this type of data, an exception is thrown.

<img width="707" alt="image" src="https://github.com/immerjs/immer/assets/19882837/d280fa51-eea6-4580-b219-ff47bd921847">

## Link to repro
https://codesandbox.io/s/immer-with-symbol-7n5nhn?file=/src/symbolImmer.ts

or here is a test file
```typescript
import {produce} from "../src/immer"

describe("change state contain symbol", () => {
	const sym = Symbol("coordinate")

	type Card = { name: string; [sym]?: {streamId: string} }

	type State = { card: Card }

	const state: State = { card: { name: "a", [sym]: {streamId: "1"} } }

	it("will crash when extends object contain symbol", () => {
		const s1 = produce(state, draft => {
			const card = draft.card
			const newCard = produce(card, draftCard => ({...draftCard, name: "b"}))
			draft.card = newCard
		})
		expect(s1.card.name).toBe("b")

		const s2 = produce(s1, draft => {
			const card = draft.card
			const newCard = produce(card, draftCard => {
				// crush here
				return {...draftCard, name: "c"}
			})
			draft.card = newCard
		})

		expect(s2.card.name).toBe("c")
	})
})

```

## To Reproduce

open the codesanbox and you will see the error

## Observed behavior

when I change the state again, it throw an error in my console

## Expected behavior

it's not error

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:** 9.0.21 (and main branch also)
- [x] I filed this report against the _latest_ version of Immer
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Immer uses by default an object reflection that is fast but skips special members like Symbols, getters etc. You can set the flag `setUseStrictShallowCopy(true);` to get the slower behavior that also picks up Symbols.

**Comment by ninesunsabiu** [comment]
Okay, I have decided to avoid using Symbol properties in my project. 
However, I tried using `setUseStrictShallowCopy(true)` in the main branch, but the exception still occurs. 
I'm not sure if this is the final solution.

<img width="978" alt="image" src="https://github.com/immerjs/immer/assets/19882837/f84c1dc4-d225-48b8-8758-87735964e812">
