### ISSUE TITLE
Minified error nr: 0.

### ISSUE THREAD

**Issue by Dagur** [immerjs/immer#1077]
## 🐛 Bug Report

If I do a release build of my project I get this error

```
Uncaught ReferenceError: Cannot access 'v7' before initialization", source: bundle.js (1)
Error handling response: Error: [Immer] minified error nr: 0. Full error at: https://bit.ly/3cXEKWf
```

I haven't touched any code except some react components.

## Link to repro

I have no idea how to reproduce this.

## To Reproduce

I have no idea how to reproduce this.

## Observed behavior

Everything works fine on debug builds. Official builds have worked without issue for months.

## Expected behavior

No error.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version: 10.0.3 (and 10.0.2)**
- [x] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by markerikson** [comment]
Is there _any_ kind of a stack trace?

Can you provide a repro of that project at all?  Or, possibly even better, record and share a Replay ( https://replay.io/record-bugs )?

**Comment by Dagur** [comment]
Sorry about the lack of info.

It turned out that this was a sympton of a bug in webpack. Closing this issue.
