### ISSUE TITLE
Error: [Immer] minified error nr: 4. Find the full error at: (3cXEKWf)

### ISSUE THREAD

**Issue by hmeerlo** [immerjs/immer#1078]
I know you only accept issue reports for the latest version but the version is not completely under my control. We get this error very very often in production versions of our app. But I have no clue what the error means:

`Error: [Immer] minified error nr: 4. Find the full error at: (3cXEKWf)`

I followed the link of course but that just leads me to a method of Immer. How can I find out why this error occurs and what we can do to mitigate the problem?

- **Immer version: 9.0.17**

**Comment by mweststrate** [comment]
The unminified errors for your version can be found here: https://github.com/immerjs/immer/blob/v9.0.17/src/utils/errors.ts

**Comment by hmeerlo** [comment]
Doh! Could have found that myself, sorry for bothering you with this.
