### ISSUE TITLE
Is there any plan for support enableES5?

### ISSUE THREAD

**Issue by Emiya0306** [immerjs/immer#1085]
## 🙋‍♂ Question

I have many customers using morden browsers, but also some Internet Explorer. Old browser customers are offline in computer labs only with local network. Some techs are also limited by Microsoft, just like [office 2019 plugin](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins?view=excel-js-preview#perpetual-versions-of-office-on-windows) (Volume-licensed) which must use IE 11.

If I upgrade the immer, I will lost old browser customers. If not, I will not get the new features of immer. It is very pain for me to this. 

So is there any plan to let enableES5 come back? 😭

## Link to repro

Please provide a [CodeSandbox demo](https://codesandbox.io/s/immer-sandbox-6wijw) to clarify your question if possible. Typically, questions without minimal codesandbox demo won't be answered.

## Environment

We only accept questions against the latest Immer version.

- **Immer version:**
- 10.0.0

**Comment by mweststrate** [comment]
There is no active development going on introducing new features, so I recommend to just stay at the previous major version instead.

**Comment by Emiya0306** [comment]
@mweststrate
Got it. So is next version of immer focus on just performance improving? That sounds good. I will keep the immer version on 9.0.21, thanks! 👍
