### ISSUE TITLE
In Vue 2's array, using push causes an error

### ISSUE THREAD

**Issue by badspider7** [immerjs/immer#1090]
## 🙋‍♂ Question
In Vue 2's array, using push causes an error,but others operation is ok

## Link to repro
![example](https://github.com/immerjs/immer/assets/54093230/1a15bd98-8316-44c7-8896-6e4ade897c38)

## Environment
vue 2.6.10
immer latest

- **Immer version:10.0.3**
<img width="1270" alt="error" src="https://github.com/immerjs/immer/assets/54093230/f2fe8fad-7011-4f42-8bfa-4295142967d1">

**Comment by mweststrate** [comment]
A screenshot is not a repro. Please follow the issue template.
