### ISSUE TITLE
how to modify data with unknown path

### ISSUE THREAD

**Issue by millievn** [immerjs/immer#1133]
i have some data like this:
```
type Node = {
children: Node[]
id: string
name: string
}

type Tree = {
   tree: Node[]
   id: string
   name: string
}
```

how to modify node data with unknown and deep path?

**Comment by mweststrate** [comment]
Same as you would do it without Immer? What did you try / doesn't work?

**Comment by mweststrate** [comment]
That should work with immer not different than without immer, so this is more of a general "how do I do X in JavaScript", for which stackoverflow is the proper resource.
