### ISSUE TITLE
Clarify the use of useCallback in documentation

### ISSUE THREAD

**Issue by scamurcuoglu** [immerjs/immer#1137]
## 🙋‍♂ Question

In the documentation React examples, event handler methods are wrapped in useCallback. I am not sure if this is strictly necessary, so I believe it would be great if we could provide some guidance on if/when to use useCallback.

Also in the examples useCallback is used with an empty dependency array, but when I do that, ESLint warns me that the function depends on the immer setter function (when using useImmer) and it should be declared in the dependencies. I believe this behavior also needs some clarification.

Thanks!

**Comment by mweststrate** [comment]
`useCallback` is imho good React practice, but further unrelated to Immer and leaving it out wouldn't semantically change the application. For the recommendations / explanations please refer to the React docs.
