### ISSUE TITLE
error: node_modules/immer/dist/immer.legacy-esm.js: /Users/eave/Downloads/rn4/node_modules/immer/dist/immer.legacy-esm.js: Cannot read properties of null (reading 'consequent')

### ISSUE THREAD

**Issue by situzhuoming** [immerjs/immer#1142]
error: node_modules/immer/dist/immer.legacy-esm.js: /Users/eave/Downloads/rn4/node_modules/immer/dist/immer.legacy-esm.js: Cannot read properties of null (reading 'consequent')

**Comment by mweststrate** [comment]
give indications as to his tribal affiliation, is debated. It is however traditionally derived from the Germanic components *auda (luck, possession, wealth) and *wakra (awake, vigilant, lively). It is not clear from which branch of the

**Comment by crise1993** [comment]
i find the same error when i use "immer": "^10.1.1"
