### ISSUE TITLE
TypeScript error: 'key' is declared but its value is never read

### ISSUE THREAD

**Issue by alissalkvc** [immerjs/immer#1144]
Hi there, I'm using Immer in my TS project and I'm getting a TS error for the following line:
https://github.com/immerjs/immer/blob/e2d222bd4fb26abded04075c936290715e9ee335/src/utils/common.ts#L207

Running `tsc --noEmit` gives me this error:
```
node_modules/immer/src/utils/common.ts:207:33 - error TS6133: 'key' is declared but its value is never read.
```
is it possible for this to be fixed? Thanks.

**Comment by markerikson** [comment]
Your project shouldn't be trying to compile Immer's own source in the first place. Can you check your TS config and figure out why it's trying to do that?

**Comment by alissalkvc** [comment]
Sure. Here's the `tsconfig.json`. 

Immer was loaded into my project as a dependency of another third-party package. Anything jump out to you as part of this configuration?

```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "incremental": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "moduleResolution": "node",
    "noEmit": true,
    "removeComments": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "strictBindCallApply": false,
    "strictNullChecks": true,
    "target": "esnext",
    "typeRoots": ["./src/@types", "./node_modules/@types"]
  },
  "exclude": ["./node_modules", "../typings"],
  "include": ["./src", "./vite.config.ts", "./jest.config.ts"]
}
```

**Comment by markerikson** [comment]
Hmm. Not immediately. `include`, `exclude`, and `skipLibCheck` all seem reasonable.

**Comment by alissalkvc** [comment]
Perhaps because it's a transitive dependency in my project, and TS is type-checking it as part of the third-party module I'm using. I'll keep looking into it.

**Comment by alissalkvc** [comment]
Yeah, seems like the way it's being loaded into the third party package (https://github.com/gorules/jdm-editor) is a little funky. I've fixed this with https://www.npmjs.com/package/patch-package.

I can update the file to use `_key` instead of `key`  if that sounds okay - if so what branch should I make a PR against?
