### ISSUE TITLE
move to org

### ISSUE THREAD

**Issue by DanielRuf** [immerjs/immer#239]
I hereby propose to move this repo to an org account to ease maintenance, create multiple teams with permissions, increase the truck factor and improve the overall processes.

**Comment by aleclarson** [comment]
Thoughts on this, @mweststrate?

**Comment by aleclarson** [comment]
I wonder if @immer would donate his username.. :)

**Comment by DanielRuf** [comment]
Alternatively immerjs.

**Comment by immer** [comment]
I would prefer to keep my username. Although, if you have a strong preference for immer, (over immerjs, or some alternative), I'd be happy trade it in :)

**Comment by mweststrate** [comment]
Moved!
