### ISSUE TITLE
Idea: immer modern

### ISSUE THREAD

**Issue by mweststrate** [immerjs/immer#266]
Immer is quite large (4KB) if you compare it with the possible minimal implementation. 

We could introduce an additional build or package that only targets modern browser and skip some of the lesser used features, making it ideal to bundle with packages that target modern bundles

- no ES 5 support
- no patches, hooks
- no custom configs?
- no polyfills / use modern browser features (for of, Array.of, etc etc)
- bundle ESM only?

Before doing that, probably should move to own org first (see #239)

**Comment by aleclarson** [comment]
Yeah, we better do it before someone else does. :P

**Comment by aleclarson** [comment]
Also, we should use Jest snapshots more when testing it. :)

**Comment by aleclarson** [comment]
Would it make sense for Immer 2.0 to be this?

**Comment by mweststrate** [comment]
No, I think the world is not ready yet for a proxy only library. And features like patch support are valuable in the future as well. 

What we could do already know btw, is to setup a separate compilation entry point, that doesn't include the ES5 implementation, and recommend people to setup (for example) node resolutions in `package.json` to build with the lighter version: `"resolutions": { "immer": "immer/lite" }`. That would easily fit in the current package, and enable quickly changing implementations if needed

**Comment by aleclarson** [comment]
@mweststrate I'm not too worried about the overhead of `npm install immer-lite` :)

**Comment by mweststrate** [comment]
Me neither, but the advantage of `resolutions` is that it works for transitive deps as well. So libraries can always be written against the full immer, and then the hosting project can decide to use `lite` instead, instead of shipping with both. (this can of course be done with a separate package as well)

**Comment by greydrizzle** [comment]
Also note that readme.md still says the gzipped size is 2KB but it is now 4KB as mentioned above.

**Comment by aleclarson** [comment]
@greydrizzle Updated. Thanks!

**Comment by Aetet** [comment]
@mweststrate Would be great for 3.0 version

**Comment by mweststrate** [comment]
Note: this solution could work as well, and doesn't need a separate package
or separately maintained major:
https://twitter.com/mweststrate/status/1099030105815437312

**Comment by aleclarson** [comment]
@mweststrate You already mentioned that in [this comment](https://github.com/mweststrate/immer/issues/266#issuecomment-449705774), unless I'm missing something. :)

**Comment by mweststrate** [comment]
I did a quick investigation, leaving out the the es5 implementation saves ~800 bytes (minified, gzipped). I think a little more can be gained by removing certain of the polyfills we use, like `each`, symbols,etc. 

Although the reduction is relatively speaking roughly 20 - 25% of the lib, I don't think the absolute size reduction is worth the effort of complicating the build setup / duplicating code for now. If someone disagrees, PR is welcome that takes care of the build and test infra for that!
