### ISSUE TITLE
[TS] Draft<T> mangles class types

### ISSUE THREAD

**Issue by aleclarson** [immerjs/immer#278]
Currently, Immer _never_ creates proxies for class instances, but we still support nesting class instances inside your immutable objects/arrays.

The issue is that we cannot distinguish __plain__ object types from `class` types. ([more info](https://github.com/Microsoft/TypeScript/issues/29063))

So `class` types end up being [mangled by a mapped type](https://github.com/mweststrate/immer/blob/d60db147173d236727f035fd31e2aac372d7bf8b/src/immer.d.ts#L35).

```ts
class Foo {
    private test: any
    constructor(public bar: string) {}
}

// Error 😔
let val: Foo = {} as Draft<Foo>
```

**Comment by mweststrate** [comment]
I think we can close this one for now, for being impossible currently...
