### ISSUE TITLE
Give warning if something is returned from thunk

### ISSUE THREAD

**Issue by mweststrate** [immerjs/immer#3]

**Comment by Gregjarvez** [comment]
Hi. I am new to contributing to open source and I am really. I work on #3. 
   1 . I checked if something either than undefined was returns for invoking the thunk and printed a 
        warning as request  
 2.  One test was added and function was added.

Fixes #3

**Comment by mweststrate** [comment]
See #16

**Comment by mweststrate** [comment]
Thanks a lot @Gregjarvez! Left a few comments, but looking good :)

**Comment by mweststrate** [comment]
Released as part of 0.1.0
