### ISSUE TITLE
Remove support for `this = draft` in recipes

### ISSUE THREAD

**Issue by mweststrate** [immerjs/immer#308]
Currently, `this` is always equal to the draft inside recipes. I suggest to remove that. It has a few benefits:

1. simpler typings
2. simpler docs
3. I didn't see anyone use it
3. it makes pattern like this possible (note that we should make sure that the curried version does preserve `this`):

```
const context = {
  foo: 1,
  bar: produce(function(draft) {
    draft.foo = this.foo
  })
}
```

**Comment by scriby** [comment]
+1 to this

**Comment by mweststrate** [comment]
Done in the `immer3` branch.
