### ISSUE TITLE
Typescript definitions could prevent returning arbitary state from producer

### ISSUE THREAD

**Issue by nkovacic** [immerjs/immer#349]
## 🐛 Bug Report

Typescript definitions allow returning arbitary state from producer

## To Reproduce

Returning any state from producer (can have properties that should not exist in state)

## Expected behavior

You could only return properties that are defined in the original state.

## Link to repro (highly encouraged)

https://codesandbox.io/s/o9pq7lmky9?fontsize=14

## Environment

-   **Immer version:**
-   [ ] Occurs with `setUseProxies(true)`
-   [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by aleclarson** [comment]
In this case, your downstream code should trigger a compiler error, since a type exists that is not accounted for.

@mweststrate Do you think `produce` should be more strict?

**Comment by mweststrate** [comment]
@aleclarson, no, I don't see why a produce should not be allowed to return something different than was passed in. Maybe produce tries to produce a parcel config from your base webpack config. (just a random example). 

The types describe what actually is happening. If you want to restrict what is allowed to happen, than make sure to assign the produced value to a typed variable (`const nextState: State = produce(...)`)
