### ISSUE TITLE
Usage question - Why we should handle patches in the callback ? 

### ISSUE THREAD

**Issue by tuoxiansp** [immerjs/immer#355]
https://runkit.com/tuoxiansp/5cb981a3c91bdd001267c94a

![QQ20190419-161240](https://user-images.githubusercontent.com/3960056/56414710-0f35c080-62be-11e9-8a9d-df72614ae28e.png)

I was confused if it is synchronous when handling patches in callback . So I did an experiment .

Maybe this is better?

```js
const [next, patches, reverse] = produce(data, draft => {
  //do something
})
```

**Comment by mweststrate** [comment]
It needlessly complicates the 98% use case: just being interested in the
next state. So at least some signature overloading would need to be added
in such case

**Comment by aleclarson** [comment]
You can wrap the `produce` function if you prefer that API.

```js
import _produce from 'immer'
export function produce(state, recipe) {
  const patches = []
  const inverse = []
  const result = _produce(state, recipe, (_patches, _inverse) => {
    patches.push(..._patches)
    inverse.push(..._inverse)
  })
  return [result, patches, inverse]
}
```
