### ISSUE TITLE
[TS] Incorrect type inference for draft from generic array state

### ISSUE THREAD

**Issue by spivachuk** [immerjs/immer#356]
## 🐛 Bug Report

Draft type is inferred incorrectly in case the state type is a generic array.

## To Reproduce

```
import { expect } from 'chai'
import produce from 'immer'

describe('produce', () => {

  it('works with generic array', () => {
    const append = <T>(queue: T[], item: T) => produce(queue, (queueDraft) => {
      queueDraft.push(item)
    })

    const queueBefore = [1, 2, 3]

    const queueAfter = append(queueBefore, 4)

    expect(queueAfter).deep.equal([1, 2, 3, 4])
    expect(queueBefore).deep.equal([1, 2, 3])
  })

})
```

In the example above the type of `queueDraft` is inferred as `Draft<T>[]` rather than `Draft<T[]>`. As a result, typescript compiler reports the following error for the argument of the call `queueDraft.push(item)`:
`Argument of type 'T' is not assignable to parameter of type 'Draft<T>'.`

## Expected behavior

Types must be inferred in a way not to produce compilation errors in the above code.

## Environment

- immer 3.0.0
- typescript 3.4.3

## Comments

There was a similar issue #272 containing a workaround with use of `ReadonlyArray` for the state type. However, neither the bug was fixed, nor the workaround was added to the documentation.

Is it planned to eventually fix the bug with type inference?

If no, can the mentioned workaround be described in the documentation?

**Comment by mweststrate** [comment]
I don't think this is generally fixable (any types we will define for drafts will always error on one side of the equation, so not applying `Draft` will introduce the inverse problem, that a value read from the array would become immutable). However, the solution here is to simply be more explicit about the draft type: 

```typescript
const append = <T>(queue: T[], item: T) =>
        produce(queue, (queueDraft: T[]) => {
            queueDraft.push(item)
        })
```

**Comment by yonigibbs** [comment]
@mweststrate: Sorry to comment on a closed issue (let me know if you'd rather I opened a new issue), but am hitting the same problem, I think, and the workaround above doesn't seem to work for me. I have one suggested workaround but wanted to check if this was the right thing to do.

The difference I can see between what I'm doing and what's above, is that I can't declare the draft parameter as an array, as I'm not working directly with the array: instead I'm working with an object which exposes the array as a property. If I explicitly declare the draft parameter then it loses the fact that it's a `Draft` object and therefore I can't update the properties on it, as they're marked as `readonly`.

Here's some code that demonstrates what I mean:

```
interface State<T> {
    readonly array: Array<T>
    readonly primitive: string
}

function Test<T>(state: State<T>) {
    function getTArray(): T[] { return [] } // Just a dummy implementation for brevity

    const reducer1 = produce(state, draft => {
        draft.primitive = "test" // Works
        draft.array = getTArray() // *** Doesn't compile: Type 'T[]' is not assignable to 'Draft<T>[]'
        draft.array = getTArray().map(i => i as Draft<T>) // Workaround for the above: is this correct?
    })
    
    const reducer2 = produce(state, (draft: State<T>) => {
        draft.primitive = "test" // Doesn't compile as State.primitive is readonly
        draft.array = getTArray() // Doesn't compile as State.array is readonly
    }) 
}
```
So is the workaround above correct? i.e. map every item in the array to `Draft<T>`?

**Comment by mweststrate** [comment]
https://github.com/immerjs/immer/issues/379#issuecomment-499088789

If things typewise don't work out. Type the `draft` argument explicitly, or
use a cast. Don't change your implementation itself to make the compiler
happy, that misses the point

**Comment by yonigibbs** [comment]
What type should I declare it as?  In `reducer2` above I tried typing it as `State<T>` and that doesn't work as the properties are readonly on the `State` interface. Alternatively, I tried declaring `draft` as `Draft<State<T>>` but that doesn't work either: I get the same error as before, i.e. `Type 'T[]' is not assignable to 'Draft<T>[]'`
