### ISSUE TITLE
State is not immutable if one uses classes

### ISSUE THREAD

**Issue by uwinkler** [immerjs/immer#357]
## 🐛 Bug Report

If one is using "constructor" objects (instead of literal objects) as state, the state object is mutated. Is this a bug? Or do I use `immer` in the wrong way?

## To Reproduce

```js
// Typescript

it('works', () => {
  const state = {
    a: 1,
  }

  const nextState = produce(state, s => {
    s.a = 2
  })

  expect(state.a).toEqual(1)
  expect(nextState.a).toEqual(2)
})

it('fails', () => {
  class State {
    a = 1
  }

  const state = new State()

  const nextState = produce(state, s => {
    s.a = 2
  })

  expect(state.a).toBe(1) // FAILED: state.a is now 2 as well
  expect(nextState.a).toBe(2)
})

```
Is that intended?

## Expected behavior

I would expected, 
- that the `nextState` is an object of type `State` with an value of `a =2`
- and that the `state` object still has the value of `a = 1`

## Link to repro (highly encouraged)

https://codesandbox.io/s/j3nw10pyj3

## Environment

-   **Immer version:**
-   [ ] Occurs with `setUseProxies(true)`
-   [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by aleclarson** [comment]
You need the `immerable` symbol mentioned [here](https://github.com/immerjs/immer#supported-object-types).

**Comment by uwinkler** [comment]
Ah, OK. Thxs. I was skimming through the docs, but somehow missed that section. 

Maybe `immer` can warn people, if they try to draft objects that are not `immerable`?

**Comment by mweststrate** [comment]
That is hard, as there can be completely valid use cases for that as well..

**Comment by tmtron** [comment]
new link to doc for [immerable](https://immerjs.github.io/immer/docs/complex-objects)
