### ISSUE TITLE
Set never changed with ReactHooks

### ISSUE THREAD

**Issue by lovelope** [immerjs/immer#359]
## 🐛 Bug Report

I inited a Set and produce it, but it`s value never changed.

## To Reproduce
```tsx
function App() {
  const [list, setList] = useState<ReadonlySet<number>>(new Set());

  function handleClick(id) {
    console.info(id);
    const nextState = produce(list, (draft: Draft<ReadonlySet<number>>) => {
      console.info("draft", draft);
      const newSet = new Set(draft as Set<number>);
      newSet.add(id);
      draft = newSet;
    });

    console.info("next", nextState);
    setList(nextState);
  }
  return (
    <div className="App">
      <ul>
        {[1, 2, 3, 4].map(item => (
          <li key={item} onClick={() => handleClick(item)}>
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}

```

## Expected behavior

I expect the set`s value changed.

## Link to repro (highly encouraged)

[CodeSandbox demo](https://codesandbox.io/embed/6n22yvl4k3) 

## Environment

-   **Immer version: 3.1.1**
-   [x] Occurs with `setUseProxies(true)`
-   [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by aleclarson** [comment]
You need to `return newSet` instead of `draft = newSet`.

Note: If that's all you're using `produce` for, you don't need `produce`.

**Comment by lovelope** [comment]
> You need to `return newSet` instead of `draft = newSet`.
> 
> Note: If that's all you're using `produce` for, you don't need `produce`.

Thanks. It`s worked.
I use it because the real business scenario is more complicated.
