### ISSUE TITLE
Recursive use

### ISSUE THREAD

**Issue by bard** [immerjs/immer#361]
## 🐛 Bug Report

I've read through https://github.com/immerjs/immer/issues/100 and https://github.com/immerjs/immer/issues/225 but I'm still not sure whether what I'm looking for is supposed to work or not. So this may not be a bug report at all, just a request for clarification.

Given the following:

```js
import produce from 'immer'

const reducer = (state, action) => produce(state, (draft) => {
    switch (action.type) {
        case 'INCREMENT':
            draft.counter++
            return
        case 'DOUBLE_THEN_INCREMENT':
            draft.counter *= 2;
            reducer(draft, { type: 'INCREMENT' })
            return
    }
})
const state = { counter: 2 }
const newState = reducer(state, { type: 'DOUBLE_THEN_INCREMENT' })
console.log(newState.counter)
```

I would expect the last line to print `5`, instead it prints `4`.

It's easy enough to work around it with a manual check to see if the passed state is already a draft, in which case I skip `produce`, like this:

```js
const producer = (draft, action) => {
    switch (action.type) {
        case 'INCREMENT':
            draft.counter++
            return
        case 'DOUBLE_THEN_INCREMENT':
            draft.counter *= 2
            reducer(draft, { type: 'INCREMENT' })
            return
    }
}
const reducer = (stateOrDraft, action) => isDraft(stateOrDraft)
    ? producer(stateOrDraft, action)
    : produce(stateOrDraft, (draft) => producer(draft, action))
```

## Link to repro

https://codesandbox.io/s/m506x7pwx8

## Environment

-   **Immer version: 3.1.1**
-   [x] Occurs with `setUseProxies(true)`
-   [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by bard** [comment]
On second look, I see that I'm overloading the concept of `reducer` and a return-less call like:

```
            reducer(draft, { type: 'INCREMENT' })
```

Doesn't really make sense. Sorry for the noise, closing as `wontmakesense`.

**Comment by aleclarson** [comment]
Note: You can still do `return reducer(draft, { ... })` and it should work

**Comment by bard** [comment]
That is only if the draft is unmodified, no? In other words, just `return reducer(draft, { ... })` would work, but `            draft.counter *= 2; return reducer(draft, { ... })` wouldn't.

**Comment by aleclarson** [comment]
@bard No, any draft that is passed into `produce` is wrapped with another draft that reflects any current changes.
