### ISSUE TITLE
Symbol.for error on IE11

### ISSUE THREAD

**Issue by faberyx** [immerjs/immer#365]
## 🐛 Bug Report

I get this error on IE11:
Object doesn't support property or method 'for'

on 
```
var DRAFTABLE = typeof Symbol !== "undefined" ? Symbol.for("immer-draftable") : "__$immer_draftable";
var DRAFT_STATE = typeof Symbol !== "undefined" ? Symbol.for("immer-state") : "__$immer_state";
```

on IE11 Symbol is not undefined actually but for it is, so I guess there should be also a check for Symbol.for existence like ` typeof Symbol === 'function' && Symbol.for `

this appeared on the latest version of immer, previous version were (I was on 2.0.0)  not affected
## To Reproduce

Using the latest version of immer  I get this error on IE11: Object doesn't support property or method 'for'

 

## Environment

-   **Immer version: 3.1.1**
-   [ ] Occurs with `setUseProxies(true)`
-   [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by faberyx** [comment]
I'm not using a polyfill actually (and I would prefer to avoid it if possible :) ). 
In version 2.0.0
`var DRAFT_STATE = typeof Symbol !== "undefined" ? Symbol("immer-state") : "__$immer_state";`
was working fine in IE11 without requiring to add Symbol polyfill, while on version 2.1.3 was changed to
`var DRAFT_STATE = typeof Symbol !== "undefined" ? Symbol.for("immer-state") : "__$immer_state";` 
which brakes IE11 because Symbol is not undefined but Symbol.for actually is. Adding a   `&& Symbol.for` would fix the issue on IE11 without requiring to add a polyfill for it.  

thank you!

**Comment by mweststrate** [comment]
Pr is welcome!

Op di 14 mei 2019 17:45 schreef Fabrizio Catitti <notifications@github.com>:

**Comment by graue** [comment]
Fascinating. I've seen other problems with Immer and IE11 (see #362), but not this one. In fact when I start an IE11 session in Browserstack and go into the console I can use `Symbol.for` just fine with no issues at all.

**Comment by mweststrate** [comment]
Lol, how many different IE11's are out there? 😅

**Comment by faberyx** [comment]
😄  microsoft browsers have always been erratic.. 🙈 unfortunately we still have traffic on IE and with great pain we need to support it. I have v. 11.590.17134.0 installed
according to [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for) is not supported on IE
