### ISSUE TITLE
Default object freezing

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [immerjs/immer#367]
Hi,

this i snot a bug but i did not get answer in stackoverflow. Also this is very abstractly documented in your docs so you say that - ` By default, it is turned on during local development and turned off in production` (setAutoFreeze) - so my question is - how immer nows that it is production? because of env variables or? Can you provide example please?

**Comment by mweststrate** [comment]
Based on whether NODE_ENV=production is set and substituted during
bundling. Typically webpack and similar tools set this automatically for
you when creating a production build

Op vr 17 mei 2019 22:16 schreef Vytautas Pranskunas <
notifications@github.com>:

**Comment by vytautas-pranskunas-** [comment]
Ok, that was my question 😊 thanks
