### ISSUE TITLE
destructuring doesn't seem to work? is this a regression?

### ISSUE THREAD

**Issue by sw-yx** [immerjs/immer#368]
## 🐛 Bug Report

destructuring doesnt seem to work! i dont see this documented, and nobody's raised an issue, i suspect i'm doing something wrong?

## To Reproduce

check this: https://repl.it/repls/YearlyImprobableOpengl

this works:

```js
const produce = require('immer').default

const baseState = {
        todo: "Learn typescript",
        done: true
    }

const nextState = produce(baseState, draft => {
    draft.done = false
})

console.log(nextState) // { todo: 'Learn typescript', done: false }
```

but this doesnt  work
```js
const nextState = produce(baseState, ({done}) => {
    done = false
})

console.log(nextState) // { todo: 'Learn typescript', done: true } 
```

the mutation doesnt work if i destructure! is this expected or documented anywhere? I cant find anything

## Expected behavior

destructuring should just work

## Link to repro (highly encouraged)

https://repl.it/repls/YearlyImprobableOpengl

## Environment

-   **Immer version:** 3.1.1
-   [ ] Occurs with `setUseProxies(true)`
-   [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by markerikson** [comment]
Hmm.  Looking at this... yes, I would expect this doesn't work, and I don't think it's even an Immer problem exactly.

Conceptually, `done = true` is just overwriting a local variable in the function.  It doesn't matter whether that variable is a primitive or an object - you're just saying "this local variable name now points to something else".

Immer specifically works by using Proxies to track assignments and mutations to fields in an object.  I think it's okay if you read a nested object off the parent object and then mutate one of the nested object's fields, but with `done = true`, there's no object field being modified at all.

**Comment by sw-yx** [comment]
ohh. wow. then my idea of proxies' power is way off. i thought it works like `babel-blade` where i even account for destructuring and follow through on it. fair enough!

**Comment by markerikson** [comment]
Yup.  Basically, a Proxy lets you define a callback that is given the key name being accessed:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/get

If there's no object key being accessed here, then nothing can be tracked.

**Comment by jeremy-coleman** [comment]
think of a proxy as an overload on .
