### ISSUE TITLE
Immer curried producer types do not work with typescript-fsa-reducers

### ISSUE THREAD

**Issue by jenni-divvito** [immerjs/immer#371]
## 🐛 Bug Report

Hi, I seem to be having issues with the typescript definitions for curried producers. I first noticed this while attempting to use the `typescript-fsa-reducers` package but in creating a repro I have discovered the issue also presents without this package 

## To Reproduce

Use the curried producers with `typescript-fsa-reducers`'s functionality. Anywhere that the reducer lib requires a `Handler` type (that is, a function that takes a state and some additional parameters, and returns a new state. If I understand correctly that should match what the curried form of produce returns (a function that takes state and some extra params, and returns a new state). However, we get instead a typescript error like: 

```
Argument type <Base extends Immutable<Parameters<Recipe>[0]>>(base: Base, ...rest: Tail<Params extends any[]>[]) => Produced<Base extends Immutable<T>, ReturnType<Recipe extends (...args: any[]) => any>> is not assignable to parameter type Handler<State, State, Baz> less... (Ctrl+F1) 
```

## Expected behavior

The type returned by the curried form of reduce is a function taking the state and additional parameters, and returning a new state.

## Link to repro (highly encouraged)

```
import actionCreatorFactory from "typescript-fsa";
import { reducerWithInitialState } from "typescript-fsa-reducers";
import produce, { Draft } from "immer";

const actionCreator = actionCreatorFactory('foo');

interface Baz {
  s: string;
  n: number;
}

const barAction = actionCreator<string>('bar');
const bazAction = actionCreator<Baz>('baz');

interface State {
  latestBar: string;
  bazStr: string;
  bazNum: number;
}

const INITIAL_STATE: State = {
  latestBar: 'initBar',
  bazStr: 'initBaz',
  bazNum: 0,
};

const barProducer = produce((draft: Draft<State>, bar: string) => void (draft.latestBar = bar));
const bazProducer = produce((draft: Draft<State>, {s, n}: Baz) => void (draft.bazStr = s, draft.bazNum += n));


// Argument type <Base extends Immutable<Parameters<Recipe>[0]>>(base: Base, ...rest: Tail<Params extends any[]>[]) => Produced<Base extends Immutable<T>, ReturnType<Recipe extends (...args: any[]) => any>> is not assignable to parameter type Handler<State, State, Baz> less... (Ctrl+F1)
const reducer = reducerWithInitialState<State>(INITIAL_STATE)
  .case(barAction, barProducer)
  .case(bazAction, bazProducer)
  .build();

// Argument types do not match parameters
const reducer2 = reducerWithInitialState<State>(INITIAL_STATE)
  .case(barAction, (state: State, val: string) => barProducer(state, val))
  .case(bazAction, (state: State, val: Baz) => bazProducer(state, val))
  .build();

// This works but it's stupid
const reducer3 = reducerWithInitialState<State>(INITIAL_STATE)
  .case(barAction, (state: State, val: string) => barProducer(state, ...[val]))
  .case(bazAction, (state: State, val: Baz) => bazProducer(state, ...[val]))
  .build();

// Also reproducible without typescript-fsa-reducers
// Argument types do not match parameters
let newState = barProducer(INITIAL_STATE, 'newBar');

// Also reproducible using the example code from the immer github
const mapper = produce((draft, index) => {
  draft.index = index
});

// example usage from immer github
// Argument type <Base extends Immutable<Parameters<Recipe>[0]>>(base: Base, ...rest: Tail<Params extends any[]>[]) => Produced<Base extends Immutable<T>, ReturnType<Recipe extends (...args: any[]) => any>> is not assignable to parameter type (value: {}, index: number, array: {}[]) => any
console.dir([{}, {}, {}].map(mapper));
```

## Environment

-   **Immer version:3.1.2**
-   **Typescript version:3.4.5**
-   [ ] Occurs with `setUseProxies(true)`
-   [ ] Occurs with `setUseProxies(false)` (ES5 only)

It seems to be something to do with the definition of the Rest parameter, seeing as it can be resolving by wrapping the extra args with an array that is immediately spread. 

Is there a better way than this to resolve this? It feels very dodgy doing things the only way I've found that works (in `reducer3` in the example above).

**Comment by aleclarson** [comment]
This seems to be a very complex issue, and I'm not a user of `typescript-fsa-reducers`, so I won't be able to look into this. Sorry!

**Comment by adberard** [comment]
Same problem using curried produce with typescript 3.5.1, no problem with typescript 3.4.5
@aleclarson op did provide examples that doesnt work even without fsa and state that it doesnt work even with the github example.

**Comment by salvoravida** [comment]
@jenni-divvito you should try combineReducer from redux-immer so you do not have to use nested produce

https://github.com/immerjs/immer/issues/372
or
https://github.com/salvoravida/redux-immer
