### ISSUE TITLE
Typescript typings of array elements may be off?

### ISSUE THREAD

**Issue by pdemarino** [immerjs/immer#375]
## 🐛 Bug Report

In Typescript typings, Drafts of arrays seem to refer to original types, not to drafts of elements. 

## To Reproduce

Install immer. Create a draft of an array, and try to pop an element. The returned type is off.
 
```
import * as React from "react";
import produce from "immer";

type undoRedoState<S> = {
  present: S;
  past: S[];
};

export function useUndoRedo<S>(initialState: S) {
  const [state, setState] = React.useState<undoRedoState<S>>(() => ({
    past: [],
    present: initialState
  }));

  return {
    undo: () =>
      setState(
        produce<undoRedoState<S>>(state, draft => {
          const x = draft.past.pop();
          draft.present = x;            <<<<<<< ERROR IS HERE
        })
      )
  };
}
```
Errors with `Type 'S' is not assignable to type 'Draft<S>'.ts(2322)`

## Expected behavior

`Array<S>.pop` should return `Draft<S>`, not `S`

## Link to repro (highly encouraged)

https://codesandbox.io/s/intelligent-nightingale-c2ufc?from-embed

## Environment

-   **Immer version:** 3.1.2
-   [ ] Occurs with `setUseProxies(true)`
-   [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by aleclarson** [comment]
CodeSandbox currently uses TypeScript 3.3, which is not supported by Immer 3 and up.

**Comment by mweststrate** [comment]
`castDraft` can be used in the future for these kind of issues, from Immer 5.3 and up
