### ISSUE TITLE
draftState is not inferred correctly with TypeScript

### ISSUE THREAD

**Issue by steida** [immerjs/immer#376]
## 🐛 Bug Report

For some reason, I have to add drafState type explicitly.

```ts
return produce(state, (draftState: RovingTabIndexState) => {
```

## To Reproduce

draftState without type fails.

## Expected behavior

Type should be inferred.

## Link to repro (highly encouraged)

TODO

**Comment by mweststrate** [comment]
Please create a reproduction

Op vr 31 mei 2019 02:57 schreef Daniel Steigerwald <notifications@github.com

**Comment by steida** [comment]
Sorry for a delay. Here is it https://codesandbox.io/s/immer-sandbox-ys4u3
