### ISSUE TITLE
Nested array and object contents mutable?

### ISSUE THREAD

**Issue by coodoo** [immerjs/immer#378]
Let's say we have an immer object `foo.bar`, seemed the content inside `bar` could be modified, instead being immutable, is this expected? 

```js
// foo.bar = { baz: 'bbb }
foo.bar.baz = 'ccc' // is this supposed to fail? 
```
Coming from a FP background I would naturally expect the whole `foo` object and it's deep nested contents being immutable, hence the question.

**Comment by aleclarson** [comment]
I might be wrong, but this seems to be a **duplicate** of #260

For a workaround, see here: https://github.com/immerjs/immer/issues/260#issuecomment-443708874
