### ISSUE TITLE
option to preserve object references after produce

### ISSUE THREAD

**Issue by chaouiy** [immerjs/immer#380]
It would be great if we can preserve that **x** has the same reference as **t[0]** after prduce 
```
let t = [{ id: 1 }, {id: 2}]
let x = t[0]
let state = {
    t: t,
    x: x
}
console.log(state.x==state.t[0])
// true

let newState = produce(state, draft=>{
draft.x.id = 2;
})
console.log(newState.x==newState.t[0])
// false
```

**Comment by mweststrate** [comment]
Immer is designed to work with immutable trees, not graphs. What you are
proposing would mutate `t`

**Comment by chaouiy** [comment]
What if I decide to work with graphs ? 
I use ngxs and I find it usefull to share object references across multiple pages.

**Comment by mweststrate** [comment]
Then don't store direct references, so that it is no longer a graph.
Immutability and graphs are going to trip you over sooner or later (I mean,
without immer, doing that update you are proposing is still very tricky to
do correct, as you will have to clone and spread both t and x. )
