### ISSUE TITLE
Question: merging nested objects

### ISSUE THREAD

**Issue by anthonychung14** [immerjs/immer#387]
**Question:**
How do you think about...
1. Organizing `produce` functions for a reducer with nested objects
2. Using nested `produce` functions every time you update a nested object

**Context**
Using `immer` and `nevernull` for nested object updates.
I am moving our boilerplate reducer code to use immer.
Trying to modify code that merges objects (potentially nested):

```
bar: {...state.foo.bar, ...action.nextBar},
```

**Problem**
I am unsure if I need to `produce` drafts of new objects, or if `produce` will add its immutability properties to new, nested objects (my intuition tells me no). For example:

**Example**
I have a state tree so that

```
state = {
  foo: {
    bar: null
  }
}
```

some steps later..

```
state = {
  foo: {
    bar: {
       baz: 1
     }
  }
}
```

**Intuition**
If I want to update `baz` to 2, I want to do:
`produce(state, draft => draft.foo.bar.baz() = 2)`

However, I THINK what I'll need to do is make `bar` a subreducer so that 
`produce(state.bar, draft => draft.baz() = 2)`

**Comment by aleclarson** [comment]
> I am unsure if I need to `produce` drafts of new objects, or if `produce` will add its immutability properties to new, nested objects (my intuition tells me no).

See here: https://github.com/immerjs/immer/issues/260#issuecomment-443630375
