### ISSUE TITLE
Question: using undefined base object

### ISSUE THREAD

**Issue by NickSevens** [immerjs/immer#390]
I'm trying to use immer.js to set a property in an object which is possible undefined - as are it's children. Can I ensure the object is initialized somehow?

```typescript
type Config = {
  personal?: {
    navigate?: boolean;
  }
};

const myFunc = (configuration?: Config): void => {
  const mergedConfig: Config = produce(configuration, (draft): void => {
    draft.personal.navigate = true;
  });
};
```

Using this code, I receive a typescript error saying Object 'draft' is possibly 'undefined'.
Anyway I can solve this?

Thanks.

**Comment by mweststrate** [comment]
If you search a bit in the closed issues, I'm pretty confident you'll find
a duplicate. Let me know if you don't.

Op vr 21 jun. 2019 11:09 schreef Nick Sevens <notifications@github.com>:

**Comment by NickSevens** [comment]
I've searched quite a bit but couldn't find a solution for me. If you could point me in the right direction would be much appreciated!

**Comment by mweststrate** [comment]
See https://github.com/immerjs/immer/issues/292

P.S. optional chaining moved to stage3 last week!

**Comment by aleclarson** [comment]
This is not Immer's problem. You just need to learn more TypeScript.

```diff
-const myFunc = (configuration?: Config): void => {
+const myFunc = (configuration: Config = {}): void => {
   const mergedConfig: Config = produce(configuration, (draft): void => {
     draft.personal.navigate = true;
   });
 };
```

**Comment by aleclarson** [comment]
Duplicate of #337, but that issue never had a proper solution given.
