### ISSUE TITLE
cancelDraft/revokeDraft ?

### ISSUE THREAD

**Issue by artola** [immerjs/immer#396]
I find very useful `createDraft ` and `finsihDraft`, but missing something like `cancelDraft` or `revokeDraft`, in a way to return to the starting point. is it possible already in some way?

**Comment by aleclarson** [comment]
```js
import { original, createDraft } from 'immer'

let draft = createDraft({ a: 1 })
draft.a += 1

draft = createDraft(original(draft))
draft.a // => 1
```

**Comment by artola** [comment]
The problem with this approach is that we lose the initial identity of `draft` that I need to keep. That's why I would prefer a way to revoke the changes, but while keep the original references.

**Comment by aleclarson** [comment]
Why is preserving the identity important to you?

**Comment by artola** [comment]
Because we keep references to this object from different parts of the app, without we should use a function to retrieve the object (we would like to avoid it), or we should use another proxy in between to proxy a to the draft (we would like to avoid it).

**Comment by mweststrate** [comment]
DON'T KEEP REFERENCES TO DRAFTS.

If you do, you are just bypassing the entire point of immutability, and
should just use mutable objects instead, instead of immutability + immer.
That would be a way simpler approach to achieve the very same thing that
store references to drafts does.

To get the original value, dropping the draft and just using the state you
started with should be suffice (or indeed finding that one back through
`original`). If that doesn't work, you are mixing to opposite paradigm
(mutability and immutability) and your code will probably be very hard to
comprehend.

**Comment by artola** [comment]
@mweststrate Thanks for your hint. I used ImmutableJS for several years, and Immer for almost 2 years now. Great libraries mainly when dealing with React/Redux "state" and shallow comparison.

But in this case, we would like to profit of the concept of "draft" and return to the initial state when required.
Just for sake of simplicity, imagine that we "print" the value of the object while the user is changing it, but the user can "reset" the object to the initial value.

Our real case is a way more complex, but same principle, we need to keep the reference.
Might be that this simple implementation is the way to go, and just avoid the use Immer in this case.
What do you think?

```js
const initial = {counter: 0};
const obj = Object.assign({}, initial);

setInterval(function print() {
  console.log(obj.counter);
}, 1e3);

function up() {
  obj.counter += 1;
}

function down() {
  obj.counter -= 1;
}

function reset() {
  for (const prop in obj) {
    delete obj[prop];
  }

  Object.assign(obj, initial);
}
```

**Comment by mweststrate** [comment]
You are treating obj as mutable. Which goes against the principles if redux
/ immer / immutablejs. As long as simply doing `obj = initial` as a way to
reset doesn't work,  you are not actually leveraging the immutable
paradigm, and you could just as well directly change obj directly all the
time, and you don't even need immer. Probably your actual product is more
complex, but your sample code at least isn't really doing immutability,
except for cloning that initial state once

Op za 13 jul. 2019 22:43 schreef martin <notifications@github.com>:

**Comment by mweststrate** [comment]
In the immutable paradigm, print should *always* print 0. Which is not what
you are seemingly trying to achieve

Op za 13 jul. 2019 23:02 schreef Michel Weststrate <mweststrate@gmail.com>:

**Comment by mweststrate** [comment]
If immutability is not your goal, this mutability-with-zero-state is quite
a cool / funny application of immer though 🤔😀

Op za 13 jul. 2019 23:04 schreef Michel Weststrate <mweststrate@gmail.com>:

**Comment by artola** [comment]
I agree with you about immutability, and we are not interested here in the paradigm, just the use of the Immer, to create a draft and reset it when required. We would like to `createDraft ` use the draft and rest it if required, but never use `finishDraft `.

As we use AMD and we download already Immer for other uses, then it would be a nice possibility to get all the functionality with the same library.
This is why something like `reset/revokeDraft` will be handy.
