### ISSUE TITLE
Circular reference throw error

### ISSUE THREAD

**Issue by gitHber** [immerjs/immer#406]
## 🐛 Bug Report

my data is circular reference，when I set data by use immer，I get a error Maxcallsize error，immer cannot deep clone a data that is circular reference？？

## To Reproduce
```
let m = {}
let n = {}
m.n = n
n.m = m
... model reducer
state.m = m
```

## Expected behavior

state.m is successed be m

## Environment

-   **Immer version:**
-   [ ] Occurs with `setUseProxies(true)`
-   [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by gitHber** [comment]
read api and know why

**Comment by joshuawootonn** [comment]
This is what ^ is referring to: https://immerjs.github.io/immer/pitfalls#immer-only-supports-unidirectional-trees
