### ISSUE TITLE
Trying to use immer but get "export is not defined"

### ISSUE THREAD

**Issue by at-mrts** [immerjs/immer#407]
installed immer with 

> npm i immer

imported on a file

> import produce from immer

Getting this error:

```
main.fecd3e5cffcbcf12a004.js:80067 Uncaught ReferenceError: exports is not defined
    at Module.<anonymous> (main.fecd3e5cffcbcf12a004.js:80067)
    at Module../node_modules/ui-stack/node_modules/immer/dist/immer.js
```

Actually using latest version (3.2.0)

What could it be?

**Comment by at-mrts** [comment]
It seems that I have another immer instaled inside the folder of another dependencie... this is the immer that is causing the error. I tried to change the version of my immer to the same as the version that the another package is using, but get the same error

**Comment by at-mrts** [comment]
It looks like produce is inside "dist" folder even if not in dependencies on package.json..

**Comment by mweststrate** [comment]
It sounds like an issue in your build setup (or that of the library using immer), like mixing up ESM imports with CJS builds or something. 

Please provide a _minimal_ reproduction as otherwise it will be impossible to help.
