### ISSUE TITLE
Does listening for patches have any performance overhead?

### ISSUE THREAD

**Issue by lostpebble** [immerjs/immer#409]
For example, to get some performance optimization, could I be doing something like so:

```tsx
if (patchesCallback) {
  const [nextState, patches, inversePatches] = produceWithPatches(currentState, s => {
    // Make state changes
  });

  patchesCallback(patches, inversePatches);

  doSomethingWithNextState(nextState);
} else {
  doSomethingWithNextState(produce(currentState as any, s => {
    // Make state changes
  }));
}
```
(Excluding the overhead of running `patchesCallback()`)

Or does it make no difference? (i.e. the patches are calculated behind the scenes anyway).

**Comment by mweststrate** [comment]
Would it matter?

Op za 17 aug. 2019 11:23 schreef Paul Myburgh <notifications@github.com>:

**Comment by lostpebble** [comment]
Yes? This is why I'm asking... If it doesn't make it difference, then no, it doesn't matter.

If it does, even if it's only slightly, then I'll continue to run conditional checks on whether I should use `produce` or `produceWithPatches`.

I'm creating a library and using patches or not is core to one of the operations I'd like to add. And I'd like my operations to be as performant as possible behind the scenes.

**Comment by lostpebble** [comment]
For the example, it wouldn't really matter. But in other scenarios it might.

I'm basically just asking if there is any difference to running:

```tsx
produce(recipe);
```

or

```tsx
produce(recipe, patchesCallback);
//or
produceWithPatches(recipe);
```

If its negligible, then its no problem. Just thought that over thousands of operations in a short while, creating the patches object might be noticeable.

**Comment by lostpebble** [comment]
Never mind, looked into the code and found followed where `scope.patches` leads. Should have just done that first.

Will have to run benchmarks to know just how much overhead it creates, as it seems like it does get quite involved.

Will close this for now.

**Comment by mweststrate** [comment]
Just write your framework naively first, then optimize once you have
numbers from realistic scenarios. Otherwise you are probably just
prematurely optimizing and complicating your codebase, just to get a
theoretical gain which is neglectable in the bigger scheme of things

Op za 17 aug. 2019 18:37 schreef Paul Myburgh <notifications@github.com>:

**Comment by lostpebble** [comment]
That's true. I'm writing my library with the ability to use two methods which achieve the same thing, one with patches and one without, until I figure out which provides the best advantage eventually. I know it sounds a bit strange, but one makes use of regular `produce` and then does equality checks on sub-state listeners to check if they should update their view. The other makes use of patches to know exactly the paths which have changed, and therefor doesn't need to run equality checks and can update the views of the sub-state listeners directly.

I think they both work well in different scenarios so will probably just keep them both.

Much thanks for this library, btw! 🙂  It's truly revolutionary in the JavaScript ecosystem.

**Comment by mweststrate** [comment]
Interesting! I'd expect the patch based version to win hands down;
generating patches gives a very little constant overhead based on the size
of the mutations, while deep comparison would potentially require full tree
traversal, if enough listeners arrive

Op za 17 aug. 2019 19:23 schreef Paul Myburgh <notifications@github.com>:
