### ISSUE TITLE
applyPatches mutates patches

### ISSUE THREAD

**Issue by karl** [immerjs/immer#411]
## 🐛 Bug Report

`applyPatches` mutates patches when applying them.

## To Reproduce

https://codesandbox.io/embed/gallant-mayer-b35vd

- Produce a patch that sets an empty array.
- Produce a second patch that adds an item to the array.
- Apply both patches.

The first patch is mutated, and now becomes a patch to add an array with 1 entry.

## Expected behavior

`applyPatches` should not mutate patches.

The current behaviour means we cannot speculatively apply patches and re-use them later.

## Link to repro (highly encouraged)

https://codesandbox.io/embed/gallant-mayer-b35vd

## Environment

-   **Immer version:** 3.2.0
-   [?] Occurs with `setUseProxies(true)`
-   [?] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by Shuumatsu** [comment]
I encountered the same problem.
Here I created a pull request: https://github.com/immerjs/immer/pull/413
