### ISSUE TITLE
Discussion: Custom Proxy traps

### ISSUE THREAD

**Issue by eddyw** [immerjs/immer#414]
## 🚀 Feature Proposal

Allow setting custom Proxy traps

## Motivation

I've been working on a personal project which uses Immer under the hood. The idea was to be able to define custom schemas in the following way:
(speudo-code)
```javascript
const User = new ObjectType({ userName: String, age: Number }).actions({
  updateUser(u, a) { // <<< createDraft (updateUser bound to this = draft)
    this.userName = u // <<< userName setter checks if `u` is typeof string
    this.age = a // <<< age setter checks if `a` is typeof number and if isFinite
  } // <<< after execution, inner state = finalizeDraft
})
const data1 = User.toJSON() // Current state { userName: '', age: null }
User.updateUser('Bob', 22)
const data2 = User.toJSON() // Current state { userName: 'Bob', age: 22 }
User.userName // Bob
User.userName = 'Something' // throws, disallowed outside of actions since it's not a draft
```
The current limitation on Immer is that it doesn't allow to set custom Proxy traps, so I ended up duplicating Immer functionality around drafts to disallow extra-properties and to check first the type of the value before setting on the draft. Something like:
```
SchemaCheckerProxy -> DraftProxy
```

If there was a way to set custom traps in a way that doesn't interfere with Immer's traps, it'd be easier to implement things such as disallowing certain properties from being set or throwing a custom error or warning (e.g: `Warning: deprecated prop "name", use "userName" instead`), or using a normalize function before a value is handled by Immer (e.g: `value.toUpperCase()`)

## Example

I haven't thought yet as to how this could be better implemented within Immer, maybe something like:
```const produce = createProduce(customTraps)```
where `customTraps` could be:
```javascript
const customTraps = {
  set(prop, value) {
    // example 1
    if (prop === 'something') console.log('Warning: deprecated prop "something"')
    // example 2
    if (prop === 'age' && typeof age !== 'number') throw new Error('....')
    // example 3
    if (prop === 'userName' && typeof value === 'string') return value.toUpperCase()
    // example 4
    if (prop === 'something' && value === null) return nothing()
  }
}
```
This could be handled within Immer as something like:
```javascript
function set(state, prop, rawValue) {
        const value = getCustomTrapsSomehow().set(prop, rawValue) || rawValue
        /// ....
}
```

Custom traps could have a signature closer to Proxy traps and not giving them access to the draft or the state itself but instead just act as a middleware around prop & value before they are treated by Immer.

If anyone has better ideas of how this could be implemented without adding a new feature to Immer, that'd also be great :)

**Comment by mweststrate** [comment]
I see how you would like to use immer as vehicle for this, but I think it goes pretty far beyond the scope of what Immer is designed to do. I'd suggest to build your own proxy around drafts proxies instead, or do the validation / normalization afterwards with one of the many libraries that are available for that :).
