### ISSUE TITLE
Produced draft is read only even original object is writable

### ISSUE THREAD

**Issue by Joozty** [immerjs/immer#416]
## 🐛 Bug Report

When trying to produce a new state from the writable object the draft becomes read-only.

## To Reproduce

You can see it clearly in codesandbox I attached.

## Expected behavior

Generated draft should be writable as an original object.

## Link to repro

https://codesandbox.io/embed/long-wind-yo2ow

## Environment

```
    "immer": "3.2.0",
    "react": "16.8.4",
    "react-dom": "16.8.4",
    "react-scripts": "2.1.3"
```

Thanks for looking into it.

**Comment by mweststrate** [comment]
Note that the goal of this whole project is to work with immutable data structures, so if you need it to be mutable, Immer might not what you should be looking for. 

Anyway, for changing this behavior, see: https://github.com/immerjs/immer#auto-freezing

**Comment by mweststrate** [comment]
P.S.: please don't assign bug labels yourself, the idea is that maintainers decide on that ;-)

**Comment by mweststrate** [comment]
@Joozty apologies, spoke too soon, it was applied automatically by the issue template
