### ISSUE TITLE
Typo on Homepage: https://immerjs.github.io/immer/docs/introduction#quick-example

### ISSUE THREAD

**Issue by adebiyial** [immerjs/immer#427]
There's a typo on https://immerjs.github.io/immer/docs/introduction#quick-example

![image](https://user-images.githubusercontent.com/18689106/65006306-96817180-d8fa-11e9-9121-19d0f24fd42c.png)

**but the nextState will a new immutable tree **
**will what a new immutable tree?**

**Comment by Melzmr** [comment]
@adebiyial, I assume there should be: 
```
but the nextState will **be** a new immutable tree
```

**Comment by mweststrate** [comment]
Don't be afraid to PR folks, it's just an edit button away and looks good on your profile :)

**Comment by adebiyial** [comment]
I was just about doing that, but it's been fixed. 😟

**Comment by mweststrate** [comment]
The best result😅

Op wo 25 sep. 2019 08:57 schreef Adebiyi Adedotun <notifications@github.com
