### ISSUE TITLE
Shared reference handling

### ISSUE THREAD

**Issue by jonchardy** [immerjs/immer#429]
## 🚀 Feature Proposal

One of the current pitfalls of immer is that it doesn't maintain shared references while mutating the draft. It is explicitly mentioned in number 2 in the [pitfalls docs](https://immerjs.github.io/immer/docs/pitfalls).

## Motivation

It's not uncommon for state to contain shared references between objects, and it would be really useful if immer could handle the immutable updating of these objects.

## Example

Consider the following:
```js
import produce from "immer"

const sharedRef = { foo: "Bar" };
const baseState = [
    { key: 0, nest: sharedRef },
    { key: 1, nest: sharedRef }
];

const nextState = produce(baseState, draftState => {
    draftState[0].nest.foo = "Baz";
});

console.log(baseState[0].nest === baseState[1].nest);  // true
console.log(nextState[0].nest === nextState[1].nest);  // false
console.log(nextState[0].nest.foo);  // "Baz"
console.log(nextState[1].nest.foo);  // "Bar"
```

It would be nice if the shared reference could be maintained through the immutable update.

I don't know what's going on under the hood, so I don't know how feasible it is, but I figured it's worth logging as it would expand the cases in which immer could be used for different structures of state. If there's a way to work around this or it's already been explored, let me know.

**Comment by mweststrate** [comment]
I don't get from the description what you are trying to achieve nor what
the intended behavior is you are looking for. Please elaborate your current
problem a bit more and include a sandbox that demonstrates any problematic
behaviour.

Op vr 20 sep. 2019 19:21 schreef Jon Hardy <notifications@github.com>:

**Comment by jonchardy** [comment]
https://codesandbox.io/embed/peaceful-moon-762hx

Here's a sandbox. In this basic example, we have an object that is referenced by two different objects within our state. When we modify the shared object via produce, it would be nice if both objects still maintained that shared reference. Instead, `nextState[0].nest` no longer references the same object as `nextState[1].nest` as it did in the base state.

Not sure how else to describe this, I'm trying to provide the simplest reproducible case.

**Comment by mweststrate** [comment]
Ah, you want to work with arbitrary *graphs* rather than *trees*. That
isn't supported as explained in some other issues; as the behavior would
always confusing to half of the world. Instead, normalize your data to
trees and store identifiers rather than references where needed.

Op ma 23 sep. 2019 18:29 schreef Jon Hardy <notifications@github.com>:
