### ISSUE TITLE
[TypeScript] Regression: cannot set readonly properties in producer

### ISSUE THREAD

**Issue by srmagura** [immerjs/immer#432]
## 🐛 Bug Report

The test case in the resolved issue #97 is failing to compile again. 

## To Reproduce

`yarn install typescript immer`
As of this writing, the latest versions were typescript@3.6.3 and  immer@4.0.0.

Run `tsc` against this code:
```
import produce from 'immer'

interface IState {
  readonly foo: boolean;
}

const state: IState = {
  foo: false
};

produce(state, draft => {
  draft.foo = true; // Error: Cannot assign to 'foo' because it is a constant or a read-only property.
});

```

## Expected behavior

I expected to be able to set `draft.foo` in the producer.

## Link to repro (highly encouraged)

https://github.com/srmagura/immer-readonly-repro

## Environment

-   **Immer version:** 4.0.0
-   [ not relevant ] Occurs with `setUseProxies(true)`
-   [ not relevant ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
This is answered in the docs

Op za 28 sep. 2019 15:37 schreef Sam Magura <notifications@github.com>:

**Comment by srmagura** [comment]
Ah, okay, I figured it out. I encountered this error in my main codebase because I had an incorrect type annotation.

The minimal repro is failing because immer only erases the `readonly` modifier when you pass `--lib es2015` or greater to `tsc`.  

This issue can be closed, unless you think we should document that `--lib es2015` is required when using TypeScript.

**Comment by mweststrate** [comment]
The error is correct and should be there. Again, see the docs related to
working with Typescript.

Op za 28 sep. 2019 16:43 schreef Sam Magura <notifications@github.com>:

**Comment by mweststrate** [comment]
See https://immerjs.github.io/immer/docs/typescript, second example

**Comment by srmagura** [comment]
While I agree this is a non-issue, I am a bit confused. Both examples from
the documentation page fail to compile if --lib es2015 or greater is not
passed to the compiler.
