### ISSUE TITLE
Allow omitting the recipe function?

### ISSUE THREAD

**Issue by ianstormtaylor** [immerjs/immer#434]
Now that all objects are frozen by default, which I think is great... I think it would be nice to allow the 2nd function argument to `produce` to be omitted for cases where you want to return a value that should be immutable directly from a function. For example:

```js
// In this example world, path arrays are immutable.
const getParent = path => {
  const parent = path.slice(0, -1)
  return produce(parent)
}
```

In development this ensures the object gets frozen with the same logic that other `produce`-d objects do. And in production it would essentially be a no-op.

**Comment by mweststrate** [comment]
I read this a couple of times but don't get it, why would parent not be
frozen already, or why would immer need to freeze? But alas, I think you
could do

const freeze = produce(x => x)
freeze(thing)

Op vr 4 okt. 2019 03:51 schreef Ian Storm Taylor <notifications@github.com>:

**Comment by ianstormtaylor** [comment]
In that example, if `path` comes in frozen then `parent` would be unfrozen due to the `slice`, right? If I want the API to always return paths that are frozen I'd need to take some extra step to ensure that.

The `produce(x => x)` helper is a great way to solve that without extra work, thank you!

**Comment by mweststrate** [comment]
There is no such thing as unfreezing. Things that were frozen, remain
frozen. Slice is totally unrelated to that, as it is not a mutative
function. So the array returned by slice will be unfrozen, but it contents
will be frozen still if it was before.

**Comment by ianstormtaylor** [comment]
Ah sorry I forgot to say that the path arrays have a type of `number[]`. And I’m talking about the frozen state of the arrays themselves, not their contents. 

(And I’m just using “unfrozen” as describing intent, not implementation.)

**Comment by mweststrate** [comment]
Not sure I fully understand the issue yet, but as far as I see this issue is so easily solvable in user land that there is not real need to fix it in the library
