### ISSUE TITLE
Immer breaks in browsers with Proxy support if they don't have Proxy.revocable

### ISSUE THREAD

**Issue by esturcke** [immerjs/immer#435]
## 🐛 Bug Report

Immer does not work in browser with support for `Proxy`, but not `Proxy.revocable`, for example Firefox 24 (which we unfortunately need to support).

Firefox 24 reports:

```
[10:05:11.037] TypeError: Proxy.revocable is not a function @ http://10.151.32.17:5000/static/js/2.078cae13.chunk.js:1
```

## To Reproduce

- `git clone git@github.com:esturcke/bug-immer-ff24.git`
- `yarn build`
- `serve -s build`
- Access the page in Firefox 24

## Expected behavior

The page should render "Hello Immer".

## Link to repro

https://github.com/esturcke/bug-immer-ff24

## Environment

-   **Immer version: 4.0.0**
-   [x] Occurs with `setUseProxies(true)`
-   [ ] Occurs with `setUseProxies(false)` (ES5 only)

## Potential Fix

Maybe fall back in the non-Proxy version if `Proxy.revocable` is undefined:

```diff
@@ -19,7 +19,7 @@ import {ImmerScope} from "./scope"
 function verifyMinified() {}

 const configDefaults = {
-	useProxies: typeof Proxy !== "undefined" && typeof Reflect !== "undefined",
+	useProxies: typeof Proxy !== "undefined" && typeof Proxy.revocable !== "undefined" && typeof Reflect !== "undefined",
 	autoFreeze:
 		typeof process !== "undefined"
 			? process.env.NODE_ENV !== "production"
```

**Comment by MuhammadAffanWahid** [comment]
`const [state, dispatch] = useImmerReducer(reducer, initialState);`
On the above line I get the error `Proxy.revocable is not a function`.
