### ISSUE TITLE
Finding and updating nested tree nodes.

### ISSUE THREAD

**Issue by brad-klosterman** [immerjs/immer#442]
I am looking at using Immer to find a nested object in a Tree, update its value and then return the updated tree. 

```
const updatedTree = await produce(TRSTATE.TREE, async draft => {
      const foundNode = await findNode({
        nodeID: ID,
        nodes: [draft]
      });
      foundNode.name = "FOUND"
    });
```

**Comment by brad-klosterman** [comment]
Found it >>> Extracting the original object from a proxied instance

**Comment by mweststrate** [comment]
Sorry, but what is the question or proposal here?

**Comment by brad-klosterman** [comment]
Thanks for the response. I just need some guidance on writing this function. My attempt with the above function returns the error: Unhandled Rejection (TypeError): Cannot perform 'set' on a proxy that has been revoked

The question is this. Could you provide me with some guidance with this task? 
Search for a branch/node in a tree, edit its contents and then return the updated tree.

**Comment by brad-klosterman** [comment]
I was able to solve it with this: 
```
const newTree = async (TREE, ID) => {
      const draft = createDraft(TREE);

      let foundNode = await findNode({
        nodeID: ID,
        nodes: [draft]
      });
      foundNode.name = "FOUND!";

      return finishDraft(draft);
    };

    newTree(TRSTATE.TREE, ID).then(payload => {
      TRD({ type: "UPDATE_TREE", payload: payload });
    });
```
