### ISSUE TITLE
Missing ES5 Proxy fallback documentation

### ISSUE THREAD

**Issue by slikts** [immerjs/immer#444]
The readme used to explain this, but the website currently just says that `Proxy` support isn't required, without detailing, for instance, if the fallback still uses structural sharing and what the performance impact would be. Using `Proxy` is a common sticking point for people, so it should be better documented.

**Comment by mweststrate** [comment]
There are no semantic differences. PR welcome.

**Comment by slikts** [comment]
Legacy support seems like something that should go in the FAQ, but that'd spoil the symmetry that the FAQ has going on currently, and I'm not sure that a new page would be warranted just for the topic of legacy support.

**Comment by mweststrate** [comment]
It's currently documented here: https://immerjs.github.io/immer/docs/installation#immer-on-older-javascript-environments. It's also quite literally on the FAQ page already: https://immerjs.github.io/immer/docs/faq#q-i-cant-rely-on-proxies-being-present-on-my-target-environments-can-i-use-immer

**Comment by slikts** [comment]
I didn't think to look in the installation page and most people wouldn't, and the FAQ doesn't give details.

**Comment by mweststrate** [comment]
Feel free to PR a cross link
