### ISSUE TITLE
Performance chart is broken

### ISSUE THREAD

**Issue by TheRusskiy** [immerjs/immer#445]
## 🐛 Bug Report

Looking at the performance section of documentation the description doesn't make sense.
Either performance tests are broken or the description is out of date.

Currently, it looks like this, which means Immer is the slowest of them all:

<img width="661" alt="Screenshot 2019-10-21 at 19 28 16" src="https://user-images.githubusercontent.com/2538374/67219416-0bcfed00-f439-11e9-8c84-329abf7537d3.png">

## To Reproduce

Look at https://immerjs.github.io/immer/docs/performance.

## Expected behavior

On some blog I found this picture, the description does make sense for it:
<img width="629" alt="Screenshot 2019-10-21 at 19 24 37" src="https://user-images.githubusercontent.com/2538374/67219249-c57a8e00-f438-11e9-8798-b9a7e42799f7.png">
(https://hackernoon.com/introducing-immer-immutability-the-easy-way-9d73d8f71cb3)

**Comment by mweststrate** [comment]
Will be fixed by next release. Somehow scale got changed to logarithmic.
