### ISSUE TITLE
Improving recursive typings when TypeScript 3.7 is out

### ISSUE THREAD

**Issue by mweststrate** [immerjs/immer#448]
_Waiting for TS 3.7 to be released_

The types for `Immutable<T>` and `Draft<T>` are not as accurate as we would love them to be. This is largely caused by TypeScript not yet supporting recursive types. 3.7 should change that, so it would be a good time to revisit these types.

[ ] Improve types as suggested in f8c65f02e3221d35ac6d58dd4f44c40e0df67a55
[ ] Re-evaluate #385
[ ] Fall back to the classic TS recursivity trick?

**Comment by antonyoneill** [comment]
Hey, just a heads up that typescript 3.7 is out 🎉 

https://github.com/microsoft/TypeScript/releases/tag/v3.7.2
