### ISSUE TITLE
Reduce Immer bundle size by eliminating the Proxy based implementations of Set and Map

### ISSUE THREAD

**Issue by mweststrate** [immerjs/immer#449]
Currently all data structures supported by Immer (plain objects, arrays, Maps, Sets) have an ES5 and Proxy based implementation. However, the Proxy implementation of Maps and Sets don't really add value, as all object interactions are through patchable methods, so the ES5 implementation has no real practical or performance drawback over the Proxy implementation. Eliminating the latter should reduce the bundle size with 0.5 to 1 KB? Relevant [comment](https://github.com/immerjs/immer/pull/354#discussion_r340535391)

**Comment by oriSomething** [comment]
As much as I don't like this idea (because mutating bulllit-ins) it can solve #466 for free

**Comment by oriSomething** [comment]
By the way, have someone benchmarked if `Object.create(···)` makes slower or faster ES5 `Map`/`Set` traps?

**Comment by mweststrate** [comment]
Released as 5.2.0
