### ISSUE TITLE
Support cross window/frame?

### ISSUE THREAD

**Issue by SpringNyan** [immerjs/immer#463]
Hi,

Currently immer doesn't support creating immutable state from other window/frame. In `isPlainObject` function, it uses `proto === Object.prototype` which doesn't work if object is created from other frame. Is there any plan to support this scenario?

Repro: https://codesandbox.io/s/immer-sandbox-x2c23

**Comment by mweststrate** [comment]
See also #405, which is a similar problem. I think introducing another argument the `Immer` constructor that allows customizing these functions (or customizing which globals should be inspected) would work. 

alternatively, you might consider always creating state objects from the window that owns them, as that might fix potential similar issues with other tools as well (using symbols etc often causes similar problems).

**Comment by mweststrate** [comment]
Several issues are reported in this area. If somebody wants to champion and work on a solution, and you need this edge case, a PR is welcome if impact is limited (which I'd expect).

**Comment by oriSomething** [comment]
I think the `isPlainObject` of Lodash is actually support checking for plain objects cross realms, So the solution probably there

**Comment by mweststrate** [comment]
Closing for the lack of inactivity
