### ISSUE TITLE
Get patches without finishing draft

### ISSUE THREAD

**Issue by ptol** [immerjs/immer#464]
## 🚀 Feature Proposal

`getPatches` function that returns current patches.

## Motivation

I try to create rollback feature in my store library, so It would be possible to rollback part of the state 's update. 
When I need a rollback I use `finishDraft` and re create a new draft. It looks something like this
```
let state = {foo: 1, bar: 2}
let draft = createDraft(state)
draft.foo = 1

// I want to update bar and rollback if it's needed

let rollbackPatches : Patch[] = []
state = finishDraft(draft)
draft = createDraft(state)   
draft.bar = 3
state = finishDraft((patches, inversePatches) => {
    rollbackPatches = inversePatches
})
function rollback() {
    state = produce(newState, draft => {
       applyPatches(draft, rollbackPatches)
    })
}
```
With `getPatches` I  could do this
```
let state = {foo: 1, bar: 2}
let draft = createDraft(state)
draft.foo = 1

// I want to update bar and rollback if it's needed

const [patches, inversePatchesBeforeRollback] = getPatches(draft)
let rollbackPatches = []
draft.bar = 3
state = finishDraft((patches, inversePatches) => {
    rollbackPatches = inversePatches
})
function rollback() {
    state = produce(newState, draft => {
       applyPatches(draft, rollbackPatches )
    })
}
```
Or maybe there is another way?

**Comment by mweststrate** [comment]
The patches are only computed when finishing drafts, so are not available (easily) on the fly. Since there is a work around, the impact is high, and this is probably not a very common issue, closing it for now
