### ISSUE TITLE
Auto-freezing "turned off in production" ignores NODE_ENV=production

### ISSUE THREAD

**Issue by maranomynet** [immerjs/immer#467]
It seems to me that the auto-freezing doesn't depend on NODE_ENV but somehow relies on uglifyjs/terser's dead code removal to disable the auto-freezing. 

My dev build happened to be minified so errors were suppressed, but an unminified production build* crashed.

This was a jarring realization to me.

--

\* Don't ask. Good story. You had to be there.

**Comment by mweststrate** [comment]
The default config is 

https://github.com/immerjs/immer/blob/dbedded6f0a5fb4dc8180e7579e37ad4599a537e/src/immer.js#L29-L32

Are you sure `process.env.NODE_ENV` is properly configured and picked up by your bundler?

**Comment by mweststrate** [comment]
Closing this issue since it is doesn't look actionable.
