### ISSUE TITLE
type error when using generic type

### ISSUE THREAD

**Issue by zmayor** [immerjs/immer#470]
I want to write some custom hooks with `use-immer`. But there was a type error when I use generic type.

Look at the [reproduction](https://codesandbox.io/s/use-immer-generic-type-error-i1smf).

```typescript
function useDemo<T>() {
  const [state, updateState] = useImmer({
    data: new Array<T>(),
  });

  const newData = new Array<T>();

  updateState(draft => {
    // type error here
    // Type 'T[]' is not assignable to type 'Draft<T>[]'.
    // Type 'T' is not assignable to type 'Draft<T>'.ts(2322
    draft.data = newData;
  })

}
```

**Comment by mweststrate** [comment]
This can be fixed by using the `castDraft` utility of 5.3 as soon as it released.

**Comment by SonofNun15** [comment]
I'm having this exact same typing issue. I tried calling `castDraft` as suggested, but I'm getting this error:
```
error TS2305: Module '"../../../node_modules/immer/compat/pre-3.7/dist/immer"' has no exported member 'castDraft'.

1 import { produce, Draft, castDraft } from 'immer';
```
immer version 6.0.2

**Comment by SonofNun15** [comment]
I tried just casting the generic type to the `Draft` type directly like so:
```
nextState.child = <Draft<TChildType>> newChild;
```

But get this typescript error:
```
Argument of type 'Draft<TChildType>' is not assignable to parameter of type 'TChildType'.
  'Draft<TChildType>' is assignable to the constraint of type 'TChildType', but 'TChildType' could be instantiated with a different subtype of constraint '{}'.
    Type 'TChildType | (TChildType extends ReadonlyMap<infer K, infer V> ? Map<Draft<K>, Draft<V>> : TChildType extends ReadonlySet<infer V> ? Set<...> : TChildType extends WeakReferences ? TChildType : TChildType extends object ? { -readonly [K in keyof TChildType]: Draft<...>; } : TChildType)' is not assignable to type 'TChildType'.
```

**Comment by SonofNun15** [comment]
Ended up just casting to `<any>` within the `produce` method for now. This issue only occurs when using `produce` within a generic function with generic types.

**Comment by mweststrate** [comment]
@SonofNun15 please refrain from replying on closed issues; as barely anyone will see your message. 

Would you mind to open a new issue? Seems that the cast utilities are not exposed in the pre- typescript 3.7 typings (updating your TS version will remove the error as well)

**Comment by SonofNun15** [comment]
I'll try taking TypeScript to 3.7. Thanks!
