### ISSUE TITLE
Unexpected access to original frozen objects while updating a map

### ISSUE THREAD

**Issue by buoyad** [immerjs/immer#472]
## 🐛 Bug Report

When updating several objects in a `Map`, writing to an object that should be mutable throws an error in some cases.

## To Reproduce

This code reproduces the error.
```
import {produce} from "immer"

const project = produce(new Map(), draft => {
  draft.set("bar1", {blocked: false})
  draft.set("bar2", {blocked: false})
})

// Read before write -- no error
produce(project, draft => {
  const bar1 = draft.get("bar1")
  const bar2 = draft.get("bar2")
  bar1.blocked = true
  bar2.blocked = true
})

// Read/write interleaved -- error
produce(project, draft => {
  const bar1 = draft.get("bar1")
  bar1.blocked = true
  const bar2 = draft.get("bar2")
  bar2.blocked = true // TypeError: "blocked" is read-only
}) 
```

## Expected behavior

Writing to objects inside a map in `produce` should not error. More broadly it seems like accessing frozen objects in `produce` should only be possible with `original`.

## Link to repro (highly encouraged)

[CodeSandbox demo](https://codesandbox.io/s/immer-sandbox-84tkm)

## Environment

- **Immer version: 5.0.0**
- [x] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by oriSomething** [comment]
related #466
