### ISSUE TITLE
Object.assign polyfill does not match spec (causing error on browsers without Object.assign)

### ISSUE THREAD

**Issue by Venryx** [immerjs/immer#477]
## 🐛 Bug Report

The Object.assign polyfill does not satisfy the Object.assign spec; it errors if it's passed "null" as the second (or later) argument.

## To Reproduce

The code below works with `Object.assign`, but fails for the polyfill:
```
Object.assign({}, null); // works
assign({}, null); // errors
```

The `assign` function is declared here: https://github.com/immerjs/immer/blob/d3be40e992ee5d926fe0e3494b956c1517c1e42e/src/common.js#L64-L71

So to reproduce in console, just copy that `assign` function (removing the `Object.assign ||` part of course), then run the code in the first code block.

## Expected behavior

The function should not error. Instead, it should return null, like Object.assign does.

## Link to repro (highly encouraged)

Not needed, since can repro directly in console.

## Why does it matter

It matters because the immer module itself calls `assign` with the third argument as `null`:
Step1) https://github.com/immerjs/immer/blob/master/src/index.js#L3
Step2) https://github.com/immerjs/immer/blob/master/src/immer.js#L40

Thus, by default, just importing the immer module crashes browsers that do not have `Object.assign` defined!

(I discovered this issue when I grabbed the Object.assign polyfill from immer for some other purpose, but then noticed that it errorred with null arguments provided)

## Environment

- **Immer version:** 5.0.0 (latest)

**Comment by mweststrate** [comment]
Thanks for the detailed bug report! This really helps. A new version (5.0.1) should be published by CI soon.

**Comment by FKobus** [comment]
For me this fix isn't working. It's giving me the following error on a HTC One m9:

"undefined" isn't a function

**Comment by mweststrate** [comment]
@FKobus that error message is very generic, and I can't tell from your message whether or not it relates to this issue. Please open a new issue including reproduction details, stack traces, example code etc etc.

@Venryx could you confirm that the issue is solved for you?

**Comment by Venryx** [comment]
@mweststrate As mentioned in my OP, I didn't actually hit this error in production -- I just discovered the issue while copying the `assign` polyfill for some temporary usage elsewhere, and realized it meant the library would break on older browsers.

That said, the console-based test/usage I described earlier now passes. (but you probably already knew that)

Anyway, thanks for the quick fix! Open-source development on GitHub is so much more streamlined than the painstaking bug-report processes for enterprise/legacy software. (like Windows issues that I've seen in multiple versions, left unfixed for over _half a decade_)

**Comment by majesticuser** [comment]
Our team also switched back to the 4.0.2 version of immer as the versions 5.0.0 and 5.0.1 of immer throw an "Object.assign undefined" error in the IE11 browser.

**Comment by mweststrate** [comment]
@majesticuser @fkobus please note that this issue is resolved and closed. Same symptoms !== same issue. So if you want your issue to be looked into, please take the courtesy to file a new issue, and take this issue as example on how to provide actionable information rather than throwing symptoms over the wall :) This project is maintained for you for free, so please make things at least as easy for us as you can!
