### ISSUE TITLE
Does immer intends to support optional chaining and nullish coalesce?

### ISSUE THREAD

**Issue by p1Machado** [immerjs/immer#481]
## 🙋‍♂ Question

Does immer intends to support [optional chaining](https://github.com/tc39/proposal-optional-chaining) and [nullish coalesce](https://github.com/tc39/proposal-nullish-coalescing)? Looks like the proxy is messing up with optional chaining, it throws a unhandled promise rejection...

## Link to repro

Couldn't reproduce optional chaining in Code Sandbox. Any suggestions on how to reproduce? If none web editor can run it, I can publish a running sample on github later.

For now, this is the code i've been facing problems:
```
updateClientes(state, { payload: clientes }: PayloadAction<ClienteDTO[]>) {
  state.clientesById = {};
  clientes.forEach?.((cliente) => {
    state.clientesById[cliente.id] = cliente;
  });
},
```

And this is the error:
> (node:16941) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
> (node:16941) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

## Environment

We only accept questions against the latest Immer version.

- **Immer version:** 4.0.1 (using @reduxjs/toolkit@1.1.0)
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
These operators should work without problems. In your example, the problem is that you've put the operator at the wrong position, it should be `clientes?.forEach`; as you want to check if the clientes are null, not the forEach property.

**Comment by p1Machado** [comment]
Holly s**. It was 2am in Brazil. What a dumb mistake... hehe
Thank you, it works. Sorry for bothering.
