### ISSUE TITLE
Question: will class instances be supported?

### ISSUE THREAD

**Issue by LiangZugeng** [immerjs/immer#485]
## 🙋‍♂ Question

We are using the auto generated typescript client from NSwag for backend API access, NSwag generates classes to represent the data instead of using plain objects, so immer's produce fails to detect the changes, we searched the issue list and found one issue mentioned that the class instances are not supported and will never be supported, just want to confirm it's still the case.

## Repro Code

```
                const c1 = new TempClass();
                c1.a = 1;
                c1.b = 2;

                const tempClassList = [];
                tempClassList.push(c1);
                const newList = produce(tempClassList, list => {
                    const item = list.find(b => b.a === 1);
                    item.b = 20;
                });
                console.log(newList === tempClassList);  // output is true
```

**Comment by mweststrate** [comment]
https://immerjs.github.io/immer/docs/complex-objects

**Comment by LiangZugeng** [comment]
Thanks, tested the method and it worked, unfortunately since the TypeScript code was generated by NSwag, we will have to update the source code of NSwag to make it work, the case can be closed.
