### ISSUE TITLE
Introduce `asDraft` and `asImmutable` to convert types

### ISSUE THREAD

**Issue by mweststrate** [immerjs/immer#486]
## 🚀 Feature Proposal

Very similar to `cast` in mobx-state-tree, utility functions like

```typescript
asDraft<T>(value: T): Draft<T> {
  return value
}
```

and the inverse would help to avoid typescript error, by up / down casting to and from drafts. 

## Motivation

Issues where TS (kind of validly) complains that a read only array is not assignable to a Draft array can be fixed with this in a controlled manner (instead of `any` casting)

**Comment by oriSomething** [comment]
Shouldn't it at least check on runtime it's a draft?

**Comment by mweststrate** [comment]
No, see the example of the docs in the linked commit, it might actually be need to be able to put immutable values into a draft.
