### ISSUE TITLE
package.json version (5.1.0-beta.2) doesn't match npm version (5.1.0)

### ISSUE THREAD

**Issue by justingrant** [immerjs/immer#488]
## 🐛 Bug Report

The latest package.json says its version is `5.1.0-beta.2`, but the npm registry and the versions page of this repo says that the latest version is [5.1.0](https://www.npmjs.com/package/immer/v/5.1.0). 

https://github.com/immerjs/immer/blob/52c991467058b04fd6fccf32511ed4e97f1bc6c3/package.json#L3

I assume that either a non-beta 5.1.0 was published by mistake, or someone forgot to update package.json when releasing 5.1.0.

**Comment by mweststrate** [comment]
The package.json is unrelated to the actually published `latest` version, since the latter is managed by semantic-release. 5.1.0 on npm is correct.
