### ISSUE TITLE
Support Typescript's readonly array, map and set types

### ISSUE THREAD

**Issue by Mossop** [immerjs/immer#494]
## 🚀 Feature Proposal

Typescript has some utility types, ReadonlyArray<V>, ReadonlySet<V> and ReadonlyMap<K, V> but immer doesn't seem to correctly handle these in the Immutable<T> and Draft<T> types.

## Motivation

More consistent type checking is in everyone's best interests!

## Can this be solved in user-land code?

I could probably write my own typings to override immer's but I would expect this to be something included in immer itself.

## Example

```
import { Draft, produce } from "immer";

let foo: ReadonlySet<string> = new Set();

produce(foo, (draft: Draft<ReadonlySet<string>>) => {
  draft.set("bar");
});
```

Result:

`Property 'set' does not exist on type '{ forEach: (callbackfn: (value: string, value2: string, set: ReadonlySet<string>) => void, thisArg?: any) => void; has: (value: string) => boolean; size: number; entries: { ...; }; keys: { ...; }; values: { ...; }; }'

**Comment by mweststrate** [comment]
Implemented through #495 -> #506
