### ISSUE TITLE
immer + React, batching update of setState is broken.

### ISSUE THREAD

**Issue by cyyyu** [immerjs/immer#496]
## 🙋‍♂ Question

I'm experimenting an application with immer+React. Hope this is the right place for asking for help. 
In short: with immer, batching update of setState is no longer working. 

If you having been using React for a while, you know this code works:
```
this.setState(state => ({...state, foo: state.foo + 1}));
this.setState(state => ({...state, bar: state.bar + 1}));
```
In certain scenarios you may need to invoke `setState` twice like I do above. It's ok because under the hood React batches these two updates and both `foo` and `bar` will get updated on next render loop.

With immer I have this abstraction:
```
setStateWithImmer = (fn, callback) => {
    this.setState(produce(this.state, fn), callback);
};
```
Then I tried to use it like I did in the above example:
```
this.setStateWithImmer(state => state.foo += 1);
this.setStateWithImmer(state => state.bar += 1);
```
While this time only `bar` gets updated. Check out the codesandbox demo beneath.
I've been investigating the cause for a while but couldn't be able to figure out it. Can someone explain it for me? Many thanks in advance.

## Link to repro

https://codesandbox.io/s/immer-jw023

## Environment

- **Immer version:**
- [x] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by cyyyu** [comment]
This may not suppose to be an issue. Added 'question' label myself.

**Comment by illuminist** [comment]
```js
setStateWithImmer = (fn, callback) => {
    this.setState(produce(this.state, fn), callback);
};
```
Should be
```js
setStateWithImmer = (fn, callback) => {
    this.setState(produce(fn), callback);
};
```

Reason is you call `this.setStateWithImmer` twice and both refer to state `this.state` which it isn't updated to a new state.

**Comment by cyyyu** [comment]
@illuminist i get it. thanks a lot :)
