### ISSUE TITLE
Inconsistent usage of "producer" vs "recipe" function

### ISSUE THREAD

**Issue by jimbo1qaz** [immerjs/immer#497]
## 🐛 Bug Report

I'm looking into immer.js as inspiration to make modifying immutable data structures in C++ less painful. While studying the source code, I encountered a confusing naming inconsistency:

https://github.com/immerjs/immer/blob/b55ef46d7a880d07d1830d14fc5868fef63ae342/src/immer.ts#L74-L93

The docstring for produce() mentions a "recipe function". The `@param` mentions a `producer`. The actual function parameter name is `recipe?`. 

https://immerjs.github.io/immer/docs/produce

The Immer documentation calls the parameter `producer`.

Just wanted to point this out; I don't know if it'll get fixed or not. I'm not actually use immer.js since I don't write JavaScript, but I really like the approach used here (less painful than transients, and I can understand the API unlike lenses). I am thinking of porting this library to C++ or maybe Rust (though with setters since I can't intercept assignment).

**Comment by mweststrate** [comment]
The idea is that (but this is indeed not done consistently, as the
nomenclature evolved over time, so feel free to PR updates):

* recipe: a function that takes a draft and does something with it
* a producer: a function that takes some state, and produce some new state,
in other word; a curried recipe to which produce is applied, so `producer =
produce(recipe)`

**Comment by sunOpar** [comment]
To sum up, the feeling is more appropriate to use 「producer」?

**Comment by mweststrate** [comment]
Depends on what you are referring to: an 'immerized' function, or the function that is passed through Immer. These are two different concepts

```
const producer = immer(function recipe(draft) {
   // in recipes one manipulate drafts. 
}

// a producer is a function that takes an immutable piece of data, and returns another immutable piece of data
const produced = producer(someState)
```
