### ISSUE TITLE
IE11 breaks if window.location is passed to produce

### ISSUE THREAD

**Issue by kdelmonte** [immerjs/immer#504]
## 🐛 Bug Report

If you pass window.location as the draft to `produce`, IE11 throws an error. The error is essentially the same one described in this [core-js issue](https://github.com/zloirock/core-js/issues/601#issuecomment-514768457).

In short, IE11's native `Object.getOwnPropertyDescriptor` can't work with environment exotic objects which is the cause for this bug.

You can easily reproduce the issue by pasting this in your IE11 Dev Tools and hitting enter.

```
Object.getOwnPropertyDescriptor(window.location, 'host')
```

## Link to repro

https://github.com/kdelmonte/immer-ie11-window-location-bug

## To Reproduce

* Clone [the repo](https://github.com/kdelmonte/immer-ie11-window-location-bug)
* Install the [serve package](https://www.npmjs.com/package/serve)
* Run the following command `yarn build && serve -s build`
* Navigate to http://localhost:5000 using IE 11 and see how the app does not load
* Navigate to http://localhost:5000 using Chrome/FF and see how the app loads fine

To verify that the app loads fine in IE 11 without this bug:

* Comment out the lines 9-11 in the `src/index.js` file 
* Run `yarn build && serve -s build` once again

## Observed behavior

If you pass window.location as the draft to `produce`, IE11 throws an error.

## Expected behavior

`produce` should be able to successfully create a draft from any object in any of the supported browsers.

## Environment

* Latest version of Windows 10
* Latest version of IE11
* Immer 5.2.0

- **Immer version:**
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by illuminist** [comment]
> Immutability with normal JavaScript objects, arrays, Sets and Maps.

I might be wrong, but immer isn't intended to be used with exotic object.

**Comment by kdelmonte** [comment]
> > Immutability with normal JavaScript objects, arrays, Sets and Maps.
> 
> I might be wrong, but immer isn't intended to be used with exotic object.

@illuminist I think the docs use the phrase "normal JavaScript objects, arrays, Sets and Maps" to highlight the fact that immer does not have its own types such as Immutable.js. I don't think the phrase is there to explicitly exclude exotics.

In any case, if this is true and the immer community has no interest in supporting exotics, the docs should be updated to reflect this. Let's see what the maintainers have to say.

**Comment by mweststrate** [comment]
Correct. Feel free to PR an `Exotic objects are not supported` behind that
or in the pitfalls section :)
