### ISSUE TITLE
[bug] 5.3.0 breaking typescript

### ISSUE THREAD

**Issue by JustFly1984** [immerjs/immer#507]
## 🐛 Bug Report

<img width="1394" alt="Screenshot 2020-01-15 04 47 48" src="https://user-images.githubusercontent.com/2255993/72397917-56b88280-3752-11ea-8738-1cbece3f5744.png">

reverting back to 5.2.1 helps.

node.js 13.3.0
yarn
TS 3.8.4

**Comment by JackCA** [comment]
I'm also seeing typescript related issues in `5.3.0`, although I can't confirm that it's the same issue as @JustFly1984.

What I see is that `draft` is implicitly getting the `any` type, even though the passed in `state` object is correctly typed:

<img width="618" alt="Screen Shot 2020-01-14 at 6 39 13 PM" src="https://user-images.githubusercontent.com/296167/72400223-6fe31400-36fd-11ea-84c1-85a3fc47f3f4.png">

**Comment by laozhu** [comment]
I have the same problem with `draft` any type error.

**Comment by pdemarino** [comment]
Confirmed.

FWIW, it appears that some files are missing (e.g., `dist/types-external.ts`).

Not sure if that's the root cause.

**Comment by ptgamr** [comment]
Same for me, after upgrade:

`Parameter 'draft' implicitly has an 'any' type.`

**Comment by mweststrate** [comment]
@egoist  Looks like an issue with bili, not exporting types for files that don't export any source code.

Pushed a temporarily workaround

**Comment by gavrielco** [comment]
I'm still getting the same error with version 5.3.1

**Comment by mweststrate** [comment]
Weird, the file is still absent in npm. Manually released, could you try in 5.3.2?

**Comment by egoist** [comment]
I tried building immer locally without @mweststrate 's fix and that file is also correctly built. 🤔

**Comment by mweststrate** [comment]
argh, for me it *now* appears as well, even on commit 747d268f22e4ad3e7f20f63c952ba6b665038757

**Comment by gavrielco** [comment]
5.3.2 works for me 🚀

**Comment by hanneswidrig** [comment]
I am still having this issue on 5.3.3 and TypeScript 3.7.5 
![image](https://user-images.githubusercontent.com/3399497/73795833-9a167780-4779-11ea-9f0c-ac5cc7209e1e.png)
