### ISSUE TITLE
Regression in produce

### ISSUE THREAD

**Issue by merisbahti** [immerjs/immer#508]
In this case(taken from your tests):
```typescript
const map = new Map([
  ['a', 1],
  ['c', 3],
])

const next = produce(map, draft => {
  draft.delete('a')
  draft.set('b', 2)
  draft.set('c', 4)
  draft.clear()
})
```

I get the following errors:
`Parameter 'draft' implicitly has an 'any' type.ts(7006)`

But in 5.0.0 draft is correctly inferred.

Is this a regression?

**Comment by mweststrate** [comment]
#507 please check open issues first next time

**Comment by merisbahti** [comment]
Oh, thanks. Sorry about that.
