### ISSUE TITLE
Immer 5.3.1 is not in the npm registry anymore

### ISSUE THREAD

**Issue by tmtron** [immerjs/immer#513]
## 🐛 Bug Report

immer version 5.3.1 vanished from the npm registry and breaks our builds:: https://www.npmjs.com/package/immer?activeTab=versions

5.3.2 is available, but causes compile errors, since we are still stuck on typescript 3.4.5

## Link to repro

https://www.npmjs.com/package/immer?activeTab=versions

## To Reproduce

look for version 5.3.1

## Observed behavior

version 5.3.1 is missing

## Expected behavior

version 5.3.1 exists. packages should never be removed from the npm registry

## Environment

- **5.3.1**
- [ x] Occurs with `setUseProxies(true)`
- [ ]x Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
That is correct, made an error in that one. You will need to downgrade
5.2.x if you want to use TypeScript 3.4

**Comment by tmtron** [comment]
Ok. Downgraded for now.
