### ISSUE TITLE
Using a MobX object-tree as the source/base for Immer's "produce"

### ISSUE THREAD

**Issue by Venryx** [immerjs/immer#515]
## 🚀 Feature Proposal

Add a "recipe" to the documentation which -- using only user-land code -- makes it possible to use MobX object-trees as the source/base object for Immer's `produce` function.

## Motivation

I currently use both MobX and Immer in my project; however, they do not synergize perfectly with each other since Immer does not accept a MobX object in its `produce` function.

The reason is that MobX uses computed properties (getters and setters), which Immer does not accept for its source/base object.

My _desire_ would be for Immer to natively support operating on source object trees that have computed properties. However, this has been discussed in [this thread](https://github.com/immerjs/immer/issues/317), with the decision seeming to be that it would add too much complexity/configuration to achieve this in a way that works for all uses of computed properties.

Since that route's not currently open, my proposal is to instead just add a "recipe" to the documentation for achieving the same end result in user-land code, for the narrower case of MobX object-trees.

How can Immer be made compatible with MobX object-trees with just userland code?

The simple approach (which has [already been mentioned](https://github.com/immerjs/immer/issues/317#issuecomment-531137667) in the thread above) is to just convert the entire MobX object-tree to a plain object-tree just prior to each `produce` call. However, this is not ideal, as it can cause performance issues for large object trees, which have produce called on them repeatedly. (such as in my project, where I call produce on the entire program data-store)

Well then, is there some more efficient way of making a "plain" copy of a large MobX object-tree?

There is, in fact: you can use MobX's `autorun` function to create (and keep up to date) a "plain mirror" of the object-tree -- which makes use of structural-sharing, so that only changed subtrees get converted to plain objects after each change. See the "Implementation" section below for the actual code implementation.

## Can this be solved in user-land code?

Yes. Hence why I'm proposing this solution as a "recipe" to be mentioned in the documentation, rather than a source-code change to Immer.

If a "recipe" like this doesn't fit with the scope of the Immer documentation, I understand; in that case, this issue can just act as a searchable entry by which people can discover this solution on their own.

However, if that's the case, it would be nice if this solution could be mentioned at the end of [this issue](https://github.com/immerjs/immer/issues/317), for others who want to use MobX and Immer together but only find that issue thread. (Unfortunately, GitHub does not show "referenced by X" notices within locked threads.)

## Implementation

First draft of the implementation: (would be cleaned up if a go-ahead is given for the general approach -- for example using a `Symbol` instead of a magic string)
```
function getMirrorOfMobXTree<T>(mobxTree: T): T {
   if (mobxTree == null) return null;
   if (mobxTree["$mirror"] == null) {
      const tree_plainMirror = Array.isArray(mobxTree) ? [] : {};
      Object.defineProperty(mobxTree, "$mirror", {value: tree_plainMirror});
      startUpdatingMirrorOfMobXTree(mobxTree, tree_plainMirror);
   }
   return mobxTree["$mirror"];
}
function startUpdatingMirrorOfMobXTree(mobxTree: any, tree_plainMirror: any) {
   autorun(()=>{
      for (const key of Object.keys(mobxTree)) {
         const value = mobxTree[key]; // this counts as a mobx-get, meaning the autorun subscribes, so this func reruns when the prop-value changes
         if (typeof value == "object") {
            tree_plainMirror[key] = getMirrorOfMobXTree(value);
         } else {
            tree_plainMirror[key] = value;
         }
      }
   });
}
```

## Usage Example
```
function getNewURLForStoreChanges(mobxStore: StoreState, actionFunc: (draft: StoreState)=>void) {
   const store_plainMirror = getMirrorOfMobXTree(mobxStore);
   const store_withChanges = produce(store_plainMirror, actionFunc);
   return getURLForStoreState(store_withChanges);
}
```

**Comment by Venryx** [comment]
On thinking about it more, I doubt an addition of this sort would be wanted in the documentation, so I'll close the issue.

It might still be worth adding a brief mention or something though, just to let readers know there are ways to make the libraries work with each other. (I know for me, it was confusing to find that the great approach Immer uses for immutability/drafting couldn't work out of the box with MobX.)

**Comment by mweststrate** [comment]
I think I don't get on a fundamental level why one should use Immer on a
MST tree, which is already mutable by itself? And if you don't want to
modify the tree itself, but operate on a clone with structural sharing, I
think produce(getSnapshot(someMSTTree), recipe)) should do the trick fine.
Any further integration would sound more confusing than helping to me to be
honest. But that might be simply because I never found a reason to combine
the two (with the exception for complex frozen values, but they don't have
the getter problem)

**Comment by Venryx** [comment]
> And if you don't want to modify the tree itself, but operate on a clone with structural sharing, I
think produce(getSnapshot(someMSTTree), recipe)) should do the trick fine.

Right, if I were using MST, it would be as simple as calling `getSnapshot`. The code in my post is basically about implementing an equivalent of `getSnapshot` for a regular MobX object/object-tree, not an MST one.

As for why one would use Immer on a MobX object/object-tree: The real-world use case in my project is that, I have it set up so that the "correct current url" for the site at any moment, is completely derived from the MobX data-store. Because the URL is fully derived from the MobX state, it makes it possible to have Link elements in the UI, which define their target based not on a hard-coded url-path, but instead by just supplying an "action" function. (which receives a revision of the MobX data-store, and makes changes to it)

The Link component "converts that" action-func into a hard-coded url by:
1) Making a plain clone of the MobX data-store, since Immer can't work with MobX getters/setters. (preferably with structural sharing for best perf)
2) Using Immer to run the action-func on that store clone.
3) Running `getURLForStoreState` on the new  revision returned by Immer.
4) Using that url-string as the "href" property for the `<a>` element.

One could argue that it's easier to just create an `<a href="..."/>` element directly rather than "define it through an action func"; but in my project this isn't true because there are various url parameters that may be present in the current url that need to be transferred to any links on the page as well -- and this happens automatically when you use the action-func approach, rather than a hard-coded string. (it also makes it easier to perform complex derivations of the current-state using type-safe data-store changes, rather than string manipulation/wrangling)

I agree it's not a _super common_ case, but I think it's probably common enough to worth showing how to do it. If not, there's this issue here findable through search now at least. :)
