### ISSUE TITLE
Proxies present in nested state after modification

### ISSUE THREAD

**Issue by Shub1427** [immerjs/immer#516]
## 🙋‍♂ Question
if my reducer state is -
```js
{
  foo: {}
}
```

doing something like the following, leaves inner values to be a proxy.

```js
draft.foo[key] = state.foo[key] || [];
draft.foo[key].push(value)

// makes the `nextState` as { foo: { [key]: SOME_PROXY } }
```

Is the above situation intentional?

## Link to repro

https://codesandbox.io/s/immer-example1-scxff?fontsize=14&hidenavigation=1&theme=dark

## Environment
immer v5.0.1

**Comment by mweststrate** [comment]
Please report issues based on the latest version and including a small reproduction.

**Comment by Shub1427** [comment]
I apologize for not providing any reproduction example. Anyways, I have edited the issue with a link to code-sandbox. To test the example, click `State update Timer` once, which triggers socket events in intervals, and then randomly click `Fetch Data` to mock fetch calls.

I am unable to replicate the issue, even with `5.0.1`, but I am sure, somehow using `fetch` and `socket` simultaneously, `Proxies` used to be present inside the nested array.

Above example tries to mock the situation I was having, using fetch and websocket, but I guess as the example app is very small/light, nothing is going wrong.


**Just a quick question, is there any chance for a `proxy` to be present, once the `produce` returns, when some dispatches are async(fetch), and others sync(socket event triggers), updating the same state?**

> Do close the issue, as I am unable to replicate the situation here!

**Comment by mweststrate** [comment]
That shouldn't happen as long as you don't use data structures that are
ignored by Immer (e.g. assigning a draft to a field inside a class would
not be converted by Immer, as it won't mess with classes).

Beyond that since it is theoretically impossible to prove the absence of a
bug, assume it isn't until you can prove otherwise :)

**Comment by Shub1427** [comment]
Thanks @mweststrate , for ur time. If I do get the issue again, and could replicate it, will reopen. 👍
