### ISSUE TITLE
Type error: Type 'Draft' is not generic

### ISSUE THREAD

**Issue by ishanuda** [immerjs/immer#517]
Hi,
I am getting the following error when compiling.

node_modules/immer/dist/immer.d.ts:41:27 - error TS2315: Type 'Draft' is not generic

> "immer": "^5.3.2"
> "typescript": "~3.5.3"
> angular 8

![immer-error](https://user-images.githubusercontent.com/8893919/73268586-346a3e80-4201-11ea-8103-272695b49a77.jpg)

Regards

**Comment by mweststrate** [comment]
Your TypeScript version is outdated. This issue has been reported before,
so feel free to search for the duplicate for more details :)

**Comment by ishanuda** [comment]
Hi,
Thank you for the quick reply,

Updating typescript gives the following error from angular CLI

ERROR in The Angular Compiler requires TypeScript >=3.4.0 and <3.6.0 but 3.7.5 was found instead

> "@angular/cli": "^8.3.23",

So I won't be able to update the typescript.

regards

**Comment by mweststrate** [comment]
ok, in that case best stick to a minor version lower of Immer (5.2 from top
of my head)

**Comment by ishanuda** [comment]
Hi,

Thank you very much.
Installing "immer": "^5.2.1", with "typescript": "^3.5.3" solved the problem

regards
