### ISSUE TITLE
Returning state from produce breaks patch compression

### ISSUE THREAD

**Issue by dannyharding10** [immerjs/immer#523]
## 🐛 Bug Report

As suggested in the docs, we can compress a group of patches using `applyPatches` as seen here https://medium.com/@dedels/using-immer-to-compress-immer-patches-f382835b6c69.

When using this trick with patches created by *returning a new state* from produceWithPatches, the resulting set of patches is empty! It seems like it may be an issue with `applyPatches` attempting to update the root element.

## Link to repro

https://codesandbox.io/s/immer-from-egghead-tutorial-82ovm?fontsize=14&hidenavigation=1&theme=dark

## To Reproduce

1. Return a new state from the `produceWithPatches` callback (i.e. don't update the draft). resulting patches shows path `[]`.
2. Use those patches in `applyPatches` inside of `produceWithPatches` as suggested [in the docs](https://immerjs.github.io/immer/docs/patches)

## Observed behavior

The resulting patches from the last call to `produceWithPatches` is an empty array

## Expected behavior

I expected the patches to include the changes

## Workaround
Instead of just calling `applyPatches` inside of `produceWithPatches` ...
```
produceWithPatches(state, (draft) => {
    applyPatches(draft, patches)
})
```
*return the result* of `applyPatches`, like so
```
produceWithPatches(state, (draft) => {
    return applyPatches(draft, patches)
})
```

## Environment
Node

- **Immer version:** 5.3.2
- [X] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Patches record the _mutations_ you make to a _draft_. However. if you return an entirely new object from a producer nothing is effectively done or changed on the draft, hence there are no patches, as there is no object to which immer made changes.

**Comment by dannyharding10** [comment]
test comment

**Comment by dannyharding10** [comment]
@mweststrate thanks for the reply! The original call to `produceWithPatces` that returns a new state *does* return valid patches, the path is just set to the empty array `[]`. So the patch looks like this `{"op":"replace","path":[],"value":10}`, with `value` being whatever the returned state is. The issue is once this patch is used in applyPatches, it fails to work. I believe the offending line in patches.ts is [line 191](https://github.com/immerjs/immer/blob/master/src/patches.ts#L191), which says don't apply patches if `!path.length`. It seems that the patch is saying "replace the whole state with this value", but applyPatches just doesn't support that. Is there perhaps another reason why applyPatches shouldn't be allowed to replace the whole state?
