### ISSUE TITLE
Spread operator inside nested produce() doesn't work

### ISSUE THREAD

**Issue by Hagihara-A** [immerjs/immer#524]
## 🐛 Bug Report

Spread operator inside nested produce doesn't work.
The object inside spreaded object  seems to be null.
Actually, in my browser's console displays `Proxy object` instead of `null` (79.0.3945.130 Ubuntu)

## Link to repro
https://codesandbox.io/s/wispy-dust-2uki1?fontsize=14&hidenavigation=1&theme=dark

## Expected behavior

above example , I expect 

```{
   level1: {
     level2: {
       level3: "data";
     }
   }
 }  
```

## Environment
browser chrome (79.0.3945.130 Ubuntu)

- **Immer version:**
- [x] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

#346 seems to have solved in not nested situation.
I'm not sure whether this is a bug or simply my mistake...I'm so sorry if latter.

**Comment by mweststrate** [comment]
Thanks for the report! Will be fixed in upcoming 5.3.3
