### ISSUE TITLE
Parameter 'draft' implicitly has an 'any' type

### ISSUE THREAD

**Issue by hanneswidrig** [immerjs/immer#527]
## 🐛 Bug Report

Immer `5.3.2` works perfectly fine, however `5.3.3` displays error `Parameter 'draft' implicitly has an 'any' type.`
![image](https://user-images.githubusercontent.com/3399497/73796181-90d9da80-477a-11ea-89b9-239476f19165.png)

## Environment

Using TypeScript 3.7.5

**Comment by matobeno1** [comment]
Can confirm with TS 3.7.2, 5.3.2 works fine.

**Comment by mweststrate** [comment]
Ok, seems that something goes wrong in the automatic release, that doesn't happen when building locally, will investigate.

**Comment by mweststrate** [comment]
Upgraded the CI infra, and that seems to fix the issue, should be fixed in 5.3.4
