### ISSUE TITLE
[bug] 5.3.3 breaking typescript

### ISSUE THREAD

**Issue by xiaoyu-tamu** [immerjs/immer#528]
same as #507

**Comment by xiaoyu-tamu** [comment]
![image](https://user-images.githubusercontent.com/33362998/73796804-dfd04180-4773-11ea-980a-82826c9963b4.png)

**Comment by mweststrate** [comment]
Seems that something goes wrong in the automatic release, that doesn't happen when building locally, will investigate.

**Comment by mweststrate** [comment]
Upgraded the CI infra, and that seems to fix the issue, should be fixed in 5.3.4
