### ISSUE TITLE
Can I start a new translation?

### ISSUE THREAD

**Issue by Gumball12** [immerjs/immer#535]
## 🙋‍♂ Question

I would like to start translating ImmerJS docs to *Korean*. But I didn't find any other repository per language, could you please let me know if I can start translating to another language? If not what's the procedure?

Thanks.

## Environment

- **Immer version: latest(v5.3.6)**

**Comment by mweststrate** [comment]
Sure, feel free to go ahead with that! Our docs website is based on docusaurus, which does support multiple languages: https://docusaurus.io/docs/en/translation. I didn't figure out how to configure that, but if you would be able to open 2 pr's, one with enabling multiple languages, and one with Korean, that would be awesome!

**Comment by Gumball12** [comment]
Thanks for the details. I'll try and open pr. Thanks!

**Comment by obzva** [comment]
@Gumball12 So you have no will to translate immer anymore? I am going to start Korean translation.

**Comment by Gumball12** [comment]
@obzva 
I'm late, sorry. I don't have time to work on it right now.
