### ISSUE TITLE
Could you ship a copy of the old type definitions for <3.7 users using typesversions?

### ISSUE THREAD

**Issue by phryneas** [immerjs/immer#538]
## 🚀 Feature Proposal

Right now, it seems you've dropped support for all TS versions below 3.7. I find the prospect of the new typings exciting (we've had our share of problems with the old typings), and I'd like to propose that we bump the `immer` version we're using in `@reduxjs/toolkit` - but our minimum TS version is 3.5 and going up to 3.7 would be very bold and from what I've seen in the issues, it would hurt quite a few people.

So my idea was: could you just ship the old type definitions as a [typesversions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#version-selection-with-typesversions)-marked `.d.ts`?
Sure, those had some problems, but given the "problematic or nothing" choice, this fallback might benefit quite some people.

From what I've gathered, the actual API hasn't changed since (I might be wrong on that), so this might be just working.

**Comment by mweststrate** [comment]
Feel free to submit a PR with old typings and that field backed in :) I guess @acemark would be quite interested as well

**Comment by markerikson** [comment]
I'm @markerikson here on Github, but yes :)

**Comment by mweststrate** [comment]
Forgot to add to the release notes, but this landed in 6.0.0 as well!

**Comment by markerikson** [comment]
Awesome, thanks!

**Comment by markerikson** [comment]
(btw, you can edit GH release notes any time - goodness knows I've done that frequently)

**Comment by phryneas** [comment]
Sweet, thanks a lot!
