### ISSUE TITLE
Idea: warn if a non-draftable / class value is stored in a patch 

### ISSUE THREAD

**Issue by l3szcz** [immerjs/immer#539]
## 🐛 Bug Report

Inverse patches saved after changing Date object result in null value when applied.
Not sure if it's a bug or I'm missing something. I found [this ](https://github.com/immerjs/immer/blob/master/docs/complex-objects.md) in the docs, but I'm not mutating Date object.

## Link to repro

https://codesandbox.io/s/immer-sandbox-bnqgf

## To Reproduce

Reproduction available in CodeSandbox.

## Observed behavior

After applying patch resulting object has the value of null.

## Expected behavior

Reverse patch properly applied.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version: 5.3.6**
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Patches only support JSON serializable data structures, and Date's aren't
out of the box (you'd have to store them as string or epoch)

**Comment by l3szcz** [comment]
> Patches only support JSON serializable data structures, and Date's aren't out of the box (you'd have to store them as string or epoch)

Ok, I understand. I would expect an error or warning much earlier as the date is properly saved inside a patch - just can't be applied.

**Comment by ayshiff** [comment]
I would love to work on it 👍

**Comment by sladiri** [comment]
In our project, I wrote a small helper function which went through the state and warned for any non-serialisable value. It just did something like JSON.parse(JSON.stringify) and spit out the path to a property, which was changed.

**Comment by mweststrate** [comment]
Closing for now. Note that patches with complex objects are still useful for local purposes, they just can't be stringified / transmitted until some parsing / unparsing is done that preserves whatever they contained. For which many options are available, such as https://github.com/Rich-Harris/devalue
