### ISSUE TITLE
404 error bit.ly link

### ISSUE THREAD

**Issue by techoi** [immerjs/immer#550]
## Link to repro
[error.ts](https://github.com/immerjs/immer/blob/master/src/utils/errors.ts)

## To Reproduce

When error occur like ES5 on IE11
The error message is shown below
`[Immer] minified error nr: 19 ES5. Find the full error at: https://bit.ly/38PiBHb`

## Observed behavior
The url is not work.
404

## Expected behavior
Replace `https://bit.ly/38PiBHb` to `https://github.com/immerjs/immer/blob/master/src/utils/errors.ts`

## Environment

- **Immer version:**
- [ ] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Yes, this is stupid, PR welcome!

**Comment by techoi** [comment]
[PR](https://github.com/immerjs/immer/pull/551) fix this issue.

**Comment by stunaz** [comment]
@techoi how did you fix this error? error 19 says the plugin is not loaded.... but I did load it as the following

```javascript
import {enableES5} from 'immer';

enableES5();
```

still getting the exact error

**Comment by einasmadi** [comment]
@stunaz - I noticed that I needed to put the enableES5() line in my redux store initialization rather than at my Index.jsx entrypoint. I know it's been a while but if it helps anyone, if the error doesn't go it might be because the enabling is in the wrong place.
