### ISSUE TITLE
Setting property on an object that doesn't exist yet causes error

### ISSUE THREAD

**Issue by martinfrancois** [immerjs/immer#553]
## 🐛 Bug Report

Setting a property on an object that doesn't exist yet like so:
```
const obj = {}; // is present in draft already like this
draft.obj["nonexisting"] = "hello";
```

Results in this error:
```
TypeError: Cannot add property nonexisting, object is not extensible
```

After setting `setAutoFreeze(false);`, the error doesn't appear anymore.

I was able to reproduce the error with 5.3.6 and 6.0.1.

## Link to repro

I tried to reproduce it in a sandbox but unfortunately I haven't been able to do so. I assume that it must have something to do with the autofreezing in certain conditions. I established a codesandbox example which performs the same operations (with changed names) as in the production code, but as I mentioned, the error doesn't occur:
https://codesandbox.io/s/immer-sandbox-euinq

The following line in the codesandbox:
```
console.log("isFrozen: " + Object.isFrozen(draft.obj))
```

Returns `true` on the production code, however it is `false` in the sandbox, which leads me to believe even more that it has something to do with the autofreezing.

The original context is a React app, using react-redux, and ImmerJS is used in a reducer where this error appears after a dispatch (in case that helps).

## Environment
- **Immer version:** 6.0.1
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
This is quite a basic, well tested feature, so without a minimal
reproduction I fear we can't be of much help. Make sure that you are not
trying to modify a data structure that cannot be draft, for example a class
instance.

**Comment by martinfrancois** [comment]
I was afraid this was the case.. Unfortunately, it's just a plain object that is created just like in the codesandbox example...
Is there any way the `draft` could still contain any frozen objects? I haven't looked into the code of immer yet, but I would assume that since an object cannot be "unfrozen" there must be some kind of mechanism that copies the frozen state for `draft` correct?

**Comment by mweststrate** [comment]
If you bring in data from a closure, and that is frozen, it will still be
frozen. It will only unfreeze the draft and everything you retrieve through
reading the draft

**Comment by martinfrancois** [comment]
Unfortunately, this was not the case... We did a lot of refactoring in our code base lately and I found that for some reason the workaround is no longer necessary and I don't have the issue anymore. It's a pity we didn't really find out the root cause, I'm sorry!
