### ISSUE TITLE
t.scope.immer.markChanged when using immer.js as an exposed global variable

### ISSUE THREAD

**Issue by mmulet** [immerjs/immer#556]
## 🐛 Bug Report
When using immer as an exposed global
```html
<script src="https://cdn.jsdelivr.net/npm/immer/dist/immer.umd.js"></script>
```
```javascript
//immer is an exposed global
immer.enableMapSet();

const map = new Map();
//Will throw Uncaught TypeError: t.scope.immer.markChanged is not a function
immer.produce(map, draft => {
  draft.set("key", "value");
});
```
But it only throws this error when using immer.js as an exposed global.
It works when using a bundler like webpack.

## Link to repro
CodeSandbox shows there is an error
[code-sandbox](https://codesandbox.io/s/immer-sandbox-65zhf)
Repo shows how it works with a bundler but not with the global
[repo](https://github.com/mmulet/immerjsbug1)

## To Reproduce

Open the code sandbox.

## Observed behavior

Error: t.scope.immer.markChanged is not a function

## Expected behavior

Will not throw an error

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:** latest
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mmulet** [comment]
Are plugins available while using the exposed global?
If not, we should update the [docs](https://immerjs.github.io/immer/docs/installation#pick-your-immer-version) to reflect this. Or, add the plugins as separate files on the cdn. Looking at the cdn now, the plugin folder only contains typescript declaration files.

**Comment by mweststrate** [comment]
Ok, that took me a while to figure out, but thanks for the detailed report. After staring at code that doesn't reflect the sources at all: Turns out that the file referred in the test doesn't exist at all, and you should be using https://cdn.jsdelivr.net/npm/immer or https://cdn.jsdelivr.net/npm/immer@6.0.3/dist/immer.umd.production.min.js (note that there is also a dev build if you prefer).

**Comment by mmulet** [comment]
Thanks for figuring it out! Oh, I see you already updated the docs, ignore my pull request!
