### ISSUE TITLE
A patch value field can sometime be a proxy

### ISSUE THREAD

**Issue by renchap** [immerjs/immer#559]
## 🐛 Bug Report

I am using patches to implement undo/redo, and `applyPatches` fails because a patch's `value` field is a revoked proxy. It looks like this happens because I am nesting reducers and my reducer's state is already a draft.

## Link to repro

Codesandbox repro: https://codesandbox.io/s/immer-sandbox-d1vg0

## To Reproduce

Open the repro, check in your browsers's console

## Observed behavior

The inverse patch's value is a Proxy (displayed as `null` by CodeSandbox's console, but correctly as a Proxy in your browser's console.

`applyPatches` fails to apply it, because the proxy has been revoked when applying the patch.

## Expected behavior

It applies the patch :)

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:** 5.3.6 & 6.0.2
- [x] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only) => does not occur, as we dont have proper proxy revocation

**Comment by mweststrate** [comment]
Confirmed. I think this can be fixed quite straightforward by checking in `patches.ts`, in the different patch generating functions, that the (old)values about to be stored in a patch are a draft, and if so, call `deepClonePatchValue` first.

**Comment by renchap** [comment]
Thanks for pointing out how this can be fixed, here is a PR: #568
