### ISSUE TITLE
return array from getter will throw an error

### ISSUE THREAD

**Issue by kresli** [immerjs/immer#560]
## 🐛 Bug Report

Return array from getter throw following error
```
Cannot assign to read only property '0' of object '[object Array]'

TypeError: Cannot assign to read only property '0' of object '[object Array]'
```

## Link to repro

https://codesandbox.io/s/magical-euclid-k3n9i?fontsize=14&hidenavigation=1&theme=dark

## To Reproduce

```typescript
class Labels {
  [immerable] = true;
  labels: string[] = [];

  add() {
    this.labels.push(`label - ${this.labels.length}`);
  }
  get sorted() {
    return this.labels.sort();
  }
}

test("should pass", () => {
  const state = produce(new Labels(), draft => {
    draft.add();
    draft.add();
  });
  expect(state.labels).toHaveLength(2);
  expect(state.sorted).toHaveLength(2);
});
```

## Observed behavior

It should be possible to return array from getter

## Expected behavior

return sorted array

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [X] Occurs with `setUseProxies(true)`

**Comment by dalcib** [comment]
It is because the method `sort` mutates the original array and the array is frozen in strict mode.
You can use one of these options to solve this issue:
```js
get sorted() {
    return [...this.labels].sort();
  }
```
or 
```js
get sorted() {
    return this.labels.slice().sort();
  }
```
