### ISSUE TITLE
update draft in promise

### ISSUE THREAD

**Issue by tommybernaciak** [immerjs/immer#562]
## 🙋‍♂ Question

How to update draft in promise using immer? This is my example code, but it does not work, I get `TypeError: Cannot perform 'set' on a proxy that has been revoked`. Why this does not work?

```
produce(state, draft => {
  switch (event.key) {
    case 'v': {
      if (event.ctrlKey || event.metaKey) {
        navigator.clipboard.readText().then(clipText => {
          draft.command = clipText;
          draft.position = clipText.length;
        }).catch(e => console.log(e));
      }
    break;
  }
}})
```
immer v.5.0.2

**Comment by mweststrate** [comment]
Most probably you shouldn't as you would probably be pointlessly updating
an old state, rather than the most recent one, see
https://immerjs.github.io/immer/docs/async and the egghead video lesson
linked there.
