### ISSUE TITLE
Switch to maintained fork of cpx

### ISSUE THREAD

**Issue by pbadenski** [immerjs/immer#563]
https://github.com/mysticatea/cpx has not be released since 2 years ago.

In fact at the moment `yarn install` fails on Node 13 (Mac) from what seems to be caused by cpx dependency tree.

There seems to be two forks that are relatively popular:
 - https://github.com/bcomnes/cpx2
 - https://github.com/VizualAbstract/cpx

Please consider switching over to a maintained fork of cpx to make it possible to build on Node 13.

**Comment by mweststrate** [comment]
Feel free to open PR

**Comment by pbadenski** [comment]
Thx, done.
