### ISSUE TITLE
Immer types do not loading in vscode

### ISSUE THREAD

**Issue by felipe-ds-lima** [immerjs/immer#565]
## 🐛 Bug Report

Hello, in olders versions of vscode, in draft i have auto completer for produce, but in the latest versions, it dont appear,

im use vscode in version 1.43.2 with javascript with create-react-app.

**Comment by mweststrate** [comment]
Make sure VSCode is using the TypeScript version of your project and not
the built-in version (you can select that somewhere in the bottom right of
the status bar). Make sure you are using a TypeScript version as advertised
in the documentation.
