### ISSUE TITLE
Is there a more efficient way to diff two immutable objects?

### ISSUE THREAD

**Issue by GoranM** [immerjs/immer#569]
Given two immutable lists, with a large number of elements, where only a small fraction of those elements differ, is there a more efficient way to build a list of differing indices than:

```js
let differing = [];

for (int i = 0; i < first_list.length; ++i){
    if (first_list[i] != second_list[i]){
        differing.push(i);
    }
}
```

I assume the internal representation would make it possible to exclude whole subsections of the trie, thereby avoiding the need to equality check each and every leaf node.

**Comment by renchap** [comment]
Are those 2 different objects, or is one a result of some operations applied to the other?

If this is the case, patches are what you want, they record the differences resulting in your draft's transformations: https://immerjs.github.io/immer/docs/patches

**Comment by GoranM** [comment]
A new version of the object is produced from a previous version, but I need to know the difference between any two versions on that timeline, not just the current and the previous. That makes patches somewhat inconvenient, because I would need to track patchsets for every state transition, and have some mechanism by which to merge them, in order to derive a composite patch that represents the correct changes from one arbitrary state to another.

It would be prohibitively slow in cases where there are many versions, and many patches to merge, between the objects in question.

**Comment by GoranM** [comment]
Perhaps @mweststrate could answer this, if no one else is able?

It would be highly appreciated.

**Comment by mweststrate** [comment]
Immer can tell you want has changed. That is what patches are. If patches
aren't to your liking, you will have to do a full diff on produced data
structures. Diffing is pretty straightforward with immutable data trees,
but out of scope of this library.

**Comment by GoranM** [comment]
> If patches aren't to your liking

They're not to my liking because they can't be used to solve my problem efficiently.

Just to reiterate, because I really don't want this to be misunderstood as some sort of "stylistic preference" issue: I have multiple values over time [t0, t1, t2 ... tN], where N can be quite large, and I need to efficiently derive the changes between any two values on that timeline (ie: t0 and tN).

> Diffing is pretty straightforward with immutable data trees, but out of scope of this library.

Assuming it's not inappropriate to ask: Why is it out of scope?

Diffing seems like a fairly fundamental feature, and something that would be a real help for more involved apps, where users need to quickly jump between a number of arbitrary states.

Being able to easily implement that, and have it run efficiently, is often touted as one of the core benefits of immutable data structures ...

**Comment by mweststrate** [comment]
The diffing you propose doesn't use any feature of immer, so there is no
reason to conflate the package with it. I'm pretty sure if you search for
one on npm you can find existing solutions. That it would be useful isn't
enough justification to put it in here.

Op za 11 apr. 2020 18:40 schreef Goran Milovanovic <notifications@github.com

**Comment by GoranM** [comment]
From what I understood, immutability, supported through structural sharing, is a central feature of immerjs, and the efficient diffing I referenced depends wholly on that feature: In a bitmapped vector trie, or a bit-partitioned hash trie, the intermediate nodes in the path between the root, and the leaves that contain actual data, make it possible to discard vast portions of the structure, without needing to equality check each and every leaf node. So, in addition to being very useful, it's also a feature that would be a natural extension of any immutable data structure library.

It's not something that can be done at application level, unless immerjs provided direct access to those intermediate nodes, which doesn't seem to be the case (or, at least, I have not seen it documented).

**Comment by mweststrate** [comment]
Immer offers structural sharing, but doesn't use tries to implement that,
it shares only complete data structures and operates directly on native JS
data structures.

Op za 11 apr. 2020 23:32 schreef Goran Milovanovic <notifications@github.com

**Comment by GoranM** [comment]
Oh, I think I finally understand now.

I did read the blog post referenced in the FAQ, where it does state: "as soon as you try to change something on a proxy (directly or through any API), it will immediately create a shallow copy of the node in the source tree". However, considering the performance implications for large data structures, I assumed the nodes themselves were somekind of special object that is internally implemented as a trie.

It would be really helpful, in my opinion, if this important detail was more explicitly stated in the FAQ. IE:

Q: Does immerjs use tries to implement immutable data structures:

A: No. Unlike most immutable data structure libraries, immerjs does not use tries.

Q: Wouldn't that make operations on larger data structures horribly inneficient?

A: <I assume there's an answer/rationale that you could provide here ... ?>

Anyway, I have all the information I need now, so I'm going to close the issue.

I really appreciate that you took the time to help me.

Thanks.
