### ISSUE TITLE
In 6.0.3 flow types for enableAllPlugins() etc. don't exist in index.js.flow

### ISSUE THREAD

**Issue by watanas** [immerjs/immer#570]
## 🐛 Bug Report

Starting with immer@6.0.3, flow reports an error when trying to import the immer functions from
https://immerjs.github.io/immer/docs/installation#pick-your-immer-version

## To Reproduce

Minimal test file:
```
// @flow
import {enableAllPlugins} from 'immer';
enableAllPlugins();
```

Then run flow type checking.

## Observed behavior

Flow reports the error:
```
Cannot import enableAllPlugins because there is no enableAllPlugins export in immer.
```

## Expected behavior

No flow errors.

## Environment

- immer@6.0.3
- flow

**Comment by mweststrate** [comment]
PR welcome!

**Comment by esturcke** [comment]
I suspect this is showing up in 6.0.3 because flow is now actually using the type definitions from [this change](https://github.com/immerjs/immer/pull/555). Before that flow would treat `enableAllPlugins` as having an `any` type.

**Comment by esturcke** [comment]
@watanas do you want to put a pull request for this together. I just ran into this as well and would love to get updated flow types in. If not, I'd be happy to work on it.

**Comment by watanas** [comment]
@esturcke Added a pull request for this issue. PTAL. Thanks!
