### ISSUE TITLE
Immer version(6.0.2) - Concern on calling pollyfills(enableES5 etc) manually in IE11.

### ISSUE THREAD

**Issue by ramareddy12345** [immerjs/immer#572]
## 🙋‍♂ Question

We are having 100+ staring points in our application. with this breaking change, now we have to call enableES5 form all the places. Anyway immer knows current execution environment (either chrome or firefox or IE11) so based on that why cann't it call this enableES5 function if it needs that pollyfill.  Do we have any limitation to make this change so that app end no need to call this manually.

Immer version - 6.0.2

**Comment by mweststrate** [comment]
The reason is that Immer doesn't detect it itself, the code would always
end up in the bundle, end everyone would pay for that, as otherwise it
wouldn't be callable in case it is needed :).

If you have 100 starting points, I assume you have some common
infrastructure in place where you could cater for this as well, for example
a utility library, or a build process where you could inject this.

**Comment by kurtinatlanta** [comment]
Having an easier method of backward compatibility that doesn't require touching all the apps would have helped enormously, but if that's not something you're willing to entertain at your end, we're disappointed, but it's your code and we'll deal with it.

**Comment by ctrlplusb** [comment]
It is an open source MIT licensed project so you could create a `immer-full` fork and have it include everything by default.

In the spirit of open source and healthy communities I think we should maintain respectful tone in our conversations.

**Comment by kurtinatlanta** [comment]
That's part of the magic of open source - there are always options.

I'm all for the total elimination of IE11 everywhere. Our part of the world isn't quite there yet.

**Comment by mweststrate** [comment]
Closing issue for now. Feel free to either...

* wrap
* fork
* patch (patch-package is awesome!)
* stick with 5 

...if this direction concerns you

**Comment by kurtinatlanta** [comment]
I'm with you on IE11 elimination.

Perhaps we don't understand the 'plugin' part. I have an app with 50 reducers (that get aggregated into the single reducer given to Redux). They each import `produce`. Is it correct to say that we don't have to call `enableES5` from each of those locations, but need to add the call once somewhere in the app (perhaps near where we create the main reducer) and all uses of `produce` after that will work on IE11?

**Comment by mweststrate** [comment]
Yes, call it once for your entire app; it applies to Immer globally.
