### ISSUE TITLE
Losing TS type guards in nested records

### ISSUE THREAD

**Issue by virzen** [immerjs/immer#574]
## 🐛 Bug Report

TypeScript seems to "forget" about refinement made by if or switch statement when updating a nested object whose type was refined. 

## Link to repro

https://codesandbox.io/s/laughing-glitter-im0gt?file=/src/reducer.ts

## To Reproduce

![image](https://user-images.githubusercontent.com/13262428/78878633-fc7a4580-7a52-11ea-8e28-ac408e8b197c.png)

![image](https://user-images.githubusercontent.com/13262428/78878395-a1485300-7a52-11ea-830d-2cf5770e78be.png)

## Observed behavior

Inside `produce`, type inference is wider than outside of it, e.g. both cases of a union instead of only one, which the type was refined to by if/switch statement.

## Expected behavior

The type refinement is maintained inside `produce`.

## Environment

We only accept bug reports against the latest Immer version.

- **6.0.3**
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by virzen** [comment]
Type guards _inside_ `produce` works fine, so I suspect this is a problem with inference of the `Base` type of `produce`.

**Comment by mweststrate** [comment]
There is nothing we can do about this, you can create a local variable with a narrower type, wrap the entire switch in a type. But beyond that this is a TS limitation and not actionable by us.
