### ISSUE TITLE
How to use immer to update Input fields ?

### ISSUE THREAD

**Issue by CodeWaala** [immerjs/immer#575]
## 🙋‍♂ Question

How to use immer to update Input fields ? in other words is code example 1 is same as code example 2 ? I really appreciate any help here.
ex:  
 1) 
<Input type="text" name="address1" id="garageaddress1" placeholder="Garaged Address Line 1"
                 value={this.state.person.address1}
                 onChange={e => produce(this.state, s => { s.person.address1 = e.target.value })}/>

2) 
<Input type="text" name="address1" id="garageaddress1" placeholder="Garaged Address Line 1"
                                value={this.state.person.address1}             
                                 onChange={this.handleChange}/>

  handleChange(e) {
        const target = e.target;
        const value = target.value;
        const name = target.name;

        this.setState({
            person: {
                [name]: value
            }

        })
}

## Link to repro

Please provide a [CodeSandbox demo](https://codesandbox.io/s/immer-sandbox-6wijw) to clarify your question if possible.

## Environment

We only accept questions against the latest Immer version.

- **Immer version:**
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Please provide a reproduction in a code sandbox or at least format the message properly. The question is unclear in its current form.
