### ISSUE TITLE
Read only property modification exception when using produce in setState in React 15.6.2

### ISSUE THREAD

**Issue by fedulovivan** [immerjs/immer#576]
Faced with not 100% reproducible problem when curried **produce** is used inside setState in old react version 15.6.2

environment (see [codesandbox](https://codesandbox.io/s/dazzling-elion-3o62u?file=/src/App.js:133-174))
- immer 6.0.3
- react 15.6.2
- react-dom 15.6.2
setAutoFreeze(true);
setUseProxies(true);

given simple component:
```js
export default class App extends PureComponent {
  state = {
    foo: 1
  }
  handleClick = () => {
    this.setState(produce(draft => {
      // draft[String(Math.random())] = 2;
    }))
  }
  render() {
    return (
      <div>
          <button onClick={this.handleClick}>Click</button>
          <pre>{JSON.stringify(this.state, null, ' ')}</pre>
      </div>
    );
  }
}
```

Here there is no modification of draft, such update is supposed to be no-op,
but actually click on button raises following exception:

`Uncaught TypeError: Cannot assign to read only property 'foo' of object '#<Object>'`

which sourced from node_modules/react-dom/lib/ReactCompositeComponent.js function **_processPendingState**

stacktrace for future searches:
```
backend.js:8457 Uncaught TypeError: Cannot assign to read only property 'foo' of object '#<Object>'
    at assign (<anonymous>)
    at ReactCompositeComponentWrapper._processPendingState (ReactCompositeComponent.js:672)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:615)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (ReactCompositeComponent.js:558)
    at Object.performUpdateIfNecessary (ReactReconciler.js:154)
    at Object.performUpdateIfNecessary (backend.js:8445)
    at Object.e.<computed> [as performUpdateIfNecessary] (backend.js:9196)
    at runBatchedUpdates (ReactUpdates.js:148)
    at ReactReconcileTransaction.perform (Transaction.js:141)
    at ReactUpdatesFlushTransaction.perform (Transaction.js:141)
    at ReactUpdatesFlushTransaction.perform (ReactUpdates.js:87)
    at Object.flushBatchedUpdates (ReactUpdates.js:170)
    at ReactDefaultBatchingStrategyTransaction.closeAll (Transaction.js:207)
    at ReactDefaultBatchingStrategyTransaction.perform (Transaction.js:154)
    at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:60)
    at Object.batchedUpdates (ReactUpdates.js:95)
    at dispatchEvent (ReactEventListener.js:145)
```

In some scenarios similar exceptions appear with non-empty produce callback (when draft has some modifications) 

All subsequent clicks on button produce react exceptions like:
`Warning: performUpdateIfNecessary: Unexpected batch number (current 2, pending 1)`

---
Not reproducible with react 16 (see [codesandbox](https://codesandbox.io/s/unruffled-grass-2l4pr?file=/src/App.js))

**Comment by mweststrate** [comment]
Probably disabling autoFreeze will help

**Comment by fedulovivan** [comment]
It really helps (no freezing no accidental modification exceptions), but I want to understand the problem essence.

**Comment by mweststrate** [comment]
Looks like React is mutating the state object, or your app is somewhere.
Enable break on exceptions when debugging and you'll find out.

Op vr 10 apr. 2020 11:05 schreef Ivan Fedulov <notifications@github.com>:

**Comment by fedulovivan** [comment]
Yep, its exactly what react does. As I already mentioned in description the exception is thrown from the code which merges result of setState callback (frozen object) with component state (which is probably also became a frozen object after previous updates):
<img width="873" alt="Screenshot 2020-04-10 at 15 42 57" src="https://user-images.githubusercontent.com/752105/78991449-a20be280-7b41-11ea-8be9-bad12de9d4fb.png">
But! This is 100% typical react scenario and immer is supposed to work here. However sometimes exceptions are thrown, sometimes not.

**Comment by mweststrate** [comment]
Semantically speaking merging should go into a new object, not in a current one. If that react version does so, that means it won't be able to work with frozen objects at all. Anyway, since as far as I can see this is a React problem, not an Immer one, and given that there is a clear work-around and this occurring on an old version only, closing this issue for now.

**Comment by fedulovivan** [comment]
I think it would be nice to mention this pitfall somewhere in immer's documents when you describe its usage with setState.

**Comment by mweststrate** [comment]
Feel free to add a note to the docs

**Comment by pankgeorg** [comment]
This is a comment for people finding the issue from Google.
I faced an issue that seems to be related to this one. We have use cases where `this.setState` is sometimes being called with the `immer` function and some other times without immer. I _think_ that produces the issue; immer freezes the state and then a naive -non-immerish- `setState` thinks it can get through.

I'll probably update this comment after more testing.
