### ISSUE TITLE
Does immer product not work with class instance object?

### ISSUE THREAD

**Issue by lovetingyuan** [immerjs/immer#578]
### Not expected case:
![image](https://user-images.githubusercontent.com/7310471/79440879-1d213d00-8009-11ea-9058-440e32f3e952.png)

### Expected case:
![image](https://user-images.githubusercontent.com/7310471/79441015-493cbe00-8009-11ea-92e3-57f67a44a0a3.png)

immer version: `6.0.3`

**Comment by mweststrate** [comment]
https://immerjs.github.io/immer/docs/complex-objects

**Comment by mweststrate** [comment]
https://immerjs.github.io/immer/docs/complex-objects

**Comment by lovetingyuan** [comment]
oh, I see, thanks a lot.
