### ISSUE TITLE
immer with TypeScript control flow analysis

### ISSUE THREAD

**Issue by xiaoxiangmoe** [immerjs/immer#580]
## 🙋‍♂ Question

I don’t know if it ’s appropriate to write in this way when we use immer with TypeScript control flow analysis.

```ts
import { produce, Draft } from 'immer';

type State =
  | {
      readonly type: 'loading';
      readonly startMs: number;
    }
  | {
      readonly type: 'value';
      readonly ids: ReadonlyArray<number>;
    };

function addId(state: State, id: number) {
  return produce(state, draft => {
    // type state is State
    if (state.type === 'value') {
      // type state is { readonly type: 'value'; readonly ids: ReadonlyArray<number>; }
      const draft2 = draft as Draft<typeof state>;
      // type draft is { type: 'loading'; startMs: number; } | { type: 'value'; ids: Array<number>; }
      // type draft2 is { type: 'value'; ids: Array<number>; }
      draft2.ids.push(id);
    }
  });
}
```

If this is good, we should probably add it to the document.

**Comment by mweststrate** [comment]
To simplify the cast see https://immerjs.github.io/immer/docs/typescript#cast-utilities

**Comment by xiaoxiangmoe** [comment]
These cast functions have no effect on control flow analysis.

I think this case should be added to the document. Or a new cast function should be added.

**Comment by mweststrate** [comment]
Sorry, I don't think I get the proposal entirely, control flow analysis is coming from TS, and I think that normally works with drafts just as with normal types? Isn't the problem you are checking `state.type ===` instead of `draft.type`? as typescript won't be able to infer types for `draft` based on control flow with `state`.

**Comment by xiaoxiangmoe** [comment]
That is, all of our get and set should be based on draft, right?

**Comment by mweststrate** [comment]
Yes, unless for some reason you want to look at the original, but that is
very rare.
