### ISSUE TITLE
Why esm build version still contains `process.env.NODE_ENV`

### ISSUE THREAD

**Issue by lovetingyuan** [immerjs/immer#581]
## 🙋‍♂ Question

esm build js file still contains `process.env.NODE_ENV`.

and the build file can not be used in browser directly.

why not use `@rollup/plugin-replace` to remove process expression?

**Comment by mweststrate** [comment]
For direct browser usage please use the UMD build. We leave the
process.env.NODE_ENV in the ESM build so that bundlers can pick a build /
dev version themselves.

**Comment by lovetingyuan** [comment]
ok, thank you!

**Comment by jeremychone** [comment]
Sorry, I must be missing someting, how to use the UMD version with typescript/rollup?

**Comment by mweststrate** [comment]
Please open new issues for new questions. This one is closed.

**Comment by FallingSnow** [comment]
I ran into this issue too while trying to `use-immer` with https://jspm.org/. Perhaps an export map in `package.json` pointing browsers to `dist/immer.umd.production.min.js`?
