### ISSUE TITLE
Immer circular dependency problem

### ISSUE THREAD

**Issue by guliashvili** [immerjs/immer#582]
## 🐛 Bug Report

Immer has weird problem for recursive type, when objects have circular dependency. Check out the small repro in codesandbox

## Link to repro

https://codesandbox.io/s/small-violet-h8iim?file=/src/index.js

## To Reproduce

You will see error in codesandbox

## Observed behavior

Crashes

## Expected behavior

Just to work

## Environment

Using the latest version

- **Immer version:**
- [ +] Occurs with `setUseProxies(true)`
- [ +] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
As documented Immer only supports trees, not circular data structures. 

https://immerjs.github.io/immer/docs/pitfalls
