### ISSUE TITLE
Produce function mutates the base state with Buffer.

### ISSUE THREAD

**Issue by yrsh** [immerjs/immer#583]
## 🐛 Bug Report

Produce function mutates the base state with Buffer.

## Link to repro

There is no need for the repo, it's quite simple code for Node.js:
```javascript
const { produce } = require('immer');

const ob = { buf: Buffer.from(`qwerty`) };
const ob1 = produce(ob, draftState => {
  draftState.buf.write('MUTATED');
});
console.log(ob.buf.toString());
```

## Expected behavior

console.log(ob.buf.toString()) should prints `qwerty`, because base state should't be mutated. But it prints `MUTATE`, so the Buffer was overwritten.

## Environment

Node: v13.13.0
Immer: 6.0.3

**Comment by mweststrate** [comment]
As documented Immer only supports plain arrays and objects, Maps, Sets, and specially marked custom classes. To mutate buffers you will have to clone and assign it to buf manually.
