### ISSUE TITLE
Iterating over a Set can cause mutations to be ignored

### ISSUE THREAD

**Issue by matchu** [immerjs/immer#586]
## 🐛 Bug Report

It seems that iterating over Immer's draft of a `Set` can cause mutations to be ignored. This seems to only happen when you iterate over the set _before_ performing any mutations.

## Link to repro

Here's a runnable code sample: https://runkit.com/matchu/5ea3a4b828ff10001bb538ea

```js
const {produce, enableMapSet} = require("immer");
const {expect} = require("chai");

enableMapSet();

let set = new Set([1, 2]);
expect(Array.from(set).sort()).to.eql([1, 2]);

// If we just add to the set, it works!
set = produce(set, draftSet => {
    draftSet.add(3);
});
expect(Array.from(set).sort()).to.eql([1, 2, 3]);

// And we can safely iterate over the set between changes,
// and changes before and after will be applied correctly.
set = produce(set, draftSet => {
    draftSet.add(4);
    console.log("By the way, the set is ", Array.from(draftSet));
    draftSet.add(5);
});
expect(Array.from(set).sort()).to.eql([1, 2, 3, 4, 5]);

// But if we iterate over the set *before* making any changes,
// then all of our changes are ignored.
//
// This test case fails in Immer 6.0.3.
set = produce(set, draftSet => {
    console.log("By the way, the set is ", Array.from(draftSet));
    draftSet.add(6);
});
expect(Array.from(set).sort()).to.eql([1, 2, 3, 4, 5, 6]);

console.log("Done!");
```

## To Reproduce

1. Enable Immer's `MapSet` plugin.
2. Use a `produce` function over the `Set`, which iterates over the content of the draft set and then mutates it.

## Observed behavior

Mutations made to the draft `Set` during `produce` are not reflected in its return value.

## Expected behavior

Mutations made to the draft `Set` during `produce` would be reflected in its return value, just as if I had not performed iteration before attempting mutation.

## Environment

- **Immer version:** 6.0.3
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by matchu** [comment]
For now I'm going to work around this by adding a fake mutation near the start of my producer:

```
draftSet.add("fake-value-immer#586").delete("fake-value-immer#586");
```

**Comment by mweststrate** [comment]
Confirmed, thanks for the extensive report!

**Comment by matchu** [comment]
Thank you!!
