### ISSUE TITLE
Flow type for `Base` too limiting

### ISSUE THREAD

**Issue by esturcke** [immerjs/immer#594]
## 🐛 Bug Report

Some [recent changes to the flow types](https://github.com/immerjs/immer/commit/0dbcfe7205cb0ffdb56170da74fba61d8337d15d) seem to be too limiting: 

```js
type Base = {...} | Array<any> | Map<any> | Set<any>;
```

excludes `string | number | void | null` which all seem to be valid values to use with `immer`.

## Link to repro

Repository with reproduction case: https://github.com/esturcke/immer-flow-base-problem

## To Reproduce

```js
// @flow
import produce from "immer";

type Foo = { a: boolean } | void;

let foo: Foo = { a: false };
let bar = produce(foo, (draft) => {
  if (draft === undefined) return;
  draft.a = true;
});
```

## Observed behavior

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ index.js:7:11

Cannot call produce because undefined [1] is incompatible with function type [2].

     index.js
 [1]  4│ type Foo = { a: boolean } | void;
      5│
      6│ let foo: Foo = { a: false };
      7│ let bar = produce(foo, (draft) => {
      8│   if (draft == null) return;
      9│   draft.a = true;
     10│ });

     node_modules/immer/dist/index.js.flow
 [2] 33│         recipe: (draftState: S, a: A, b: B, c: C, ...extraArgs: any[]) => S | void,

Found 1 error
```
## Expected behavior

No flow errors.

## Environment

immer 6.0.5

**Comment by esturcke** [comment]
cc @nifgraup, do you have thoughts on how to improve this?

**Comment by nifgraup** [comment]
This should fix it:
```
diff --git a/src/types/index.js.flow b/src/types/index.js.flow
index 01a1760..0fe6c0d 100644
--- a/src/types/index.js.flow
+++ b/src/types/index.js.flow
@@ -8,7 +8,7 @@ export interface Patch {
 
 export type PatchListener = (patches: Patch[], inversePatches: Patch[]) => void
 
-type Base = {...} | Array<any> | Map<any> | Set<any>;
+type Base = {...} | Array<any> | Map<any> | Set<any> | string | number | null;
 interface IProduce {
     /**
      * Immer takes a state, and runs a function against it.
@@ -28,6 +28,11 @@ interface IProduce {
         recipe: (draftState: S) => S | void,
         patchListener?: PatchListener
     ): S;
+    (
+        currentState: void,
+        recipe: (draftState: void) => void,
+        patchListener?: PatchListener
+    ): void;
     // curried invocations with inital state
     <S: Base, A = void, B = void, C = void>(
         recipe: (draftState: S, a: A, b: B, c: C, ...extraArgs: any[]) => S | void,
```
I'm not sure how allow undefined state in curried produce without breaking the unit tests.

**Comment by nifgraup** [comment]
@esturcke Foo is an object or undefined in our example but then you compare against null, not undefined.

**Comment by esturcke** [comment]
@nifgraup Let me still update the example so it's not a distraction.

What you have works in our codebase. Yeah, we've actually been avoiding the curried form because the flow types didn't work, so I'm really happy that you had fixed those up.

**Comment by nifgraup** [comment]
It was actually just curried produce with initial state that I had issues with. I pushed a fix for curried non-initial state.

**Comment by watanas** [comment]
Does the type `Map<any>` in `Base` work? I seem to get an error (running flow 0.124.0):
```
Cannot use `Map`with fewer than 2 type arguments.
```
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAFswBeMbAUyQFkBDABwB47sBPAPgAoBKAblRA

**Comment by nifgraup** [comment]
It doesn't. I fixed and added tests for Map and Set as well.

**Comment by mweststrate** [comment]
accepting primitive values as base state to produce doesn't offer any value and has been a source of confusion, so that will be forbidding in Immer 7, meaning that the strictness of the flow types will be actually correct.

This means that in the original code, if `foo` can be `undefined`, it should be guarded like: `let bar = isDraftable(foo) ? produce(foo, /* */) : /*something else*/` (or use a simpler truthy check in this specific case)

**Comment by mweststrate** [comment]
existing Flow #595

**Comment by michaelmior** [comment]
Not 100% sure this is related, but see [this Travis failure](https://travis-ci.com/github/michaelmior/relational-playground/jobs/338785796) I had for Flow when updating to 6.0.6 from 6.0.3.

**Comment by nifgraup** [comment]
@michaelmior your code should have supplied second type argument `Action`. Instead of using this defintion of produce
```
-    <S, A>(
-        recipe: (draftState: S, a: A) => S | void
-    ): (currentState: S, a: A) => S;
```
you used this one
```
-    <S>(
-        recipe: (draftState: S, ...extraArgs: any[]) => S | void
-    ): (currentState: S, ...extraArgs: any[]) => S;
```
The simple fix is to let Flow infer both generic type arguments:
`produce((draft: State, action: Action) => {
`

**Comment by michaelmior** [comment]
@nifgraup Thanks for the response! I don't follow the suggested fix though. I do specify the types of both parameters where `produce` is used as is shown in the output from Flow.

**Comment by nifgraup** [comment]
@michaelmior Welcome. The Travis output shows a single generic type argument `<State>`, https://travis-ci.com/github/michaelmior/relational-playground/jobs/338785796#L266. You can skip it or mention both, `<State, Action>`.

**Comment by michaelmior** [comment]
@nifgraup Thanks again :) I misinterpreted your previous comment. Looks like that did the trick!

**Comment by nifgraup** [comment]
I suggest this issue should be closed as Immer 7 is out with "[BREAKING CHANGE] produce no longer accepts non-draftable objects as first argument". I dropped #595 in favor of #625.
