### ISSUE TITLE
Broken immutability

### ISSUE THREAD

**Issue by gabriel-fortin** [immerjs/immer#596]
## 🐛 Bug Report

When using `produce`, the original object gets modified. Also, running `isDraft` on it returns `false`.

If it's expected behaviour, it would be good to get an error saying that immutability is not achieved. Personal opinion: I didn't expect that the basic functionality of Immer wouldn't work. It took a long time to  find where the issue was.

## Link to repro

https://codesandbox.io/s/immer-sandbox-gkypq?file=/src/index.ts

## To Reproduce

See the sandbox

## Observed behavior

In console:
```
isDraft(mutableState): false
old state: {"current":{"foodData":[],"day":{"id":8,"ver":2}}}
```

## Expected behavior

In console:
```
isDraft(mutableState): true
old state: {"current":{"foodData":[],"day":null}}
```

## Environment

- **Immer version:** `5.3.6`, `6.0.5`
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by gabriel-fortin** [comment]
The class definition is missing `[immerable] = true;`

This still deserves an error, for example: "The object provided to the 'produce' function cannot be kept immutable. Did you forget to add '[immerable] = true' to the class definition?"

I suspect there are reasons for requiring opt-in. Maybe the documentation could explain the reasons? It would have helped me, certainly.

**Comment by dr-skot** [comment]
I agree, this should throw an error. Quietly mutating the original object is one hell of a gotcha when the whole point of using produce() is to avoid mutation.

**Comment by mweststrate** [comment]
Will be fixed in Immer 7, closing for now
