### ISSUE TITLE
flow issue, 'Unexpected token =' in src/types/index.js.flow

### ISSUE THREAD

**Issue by aliceriot** [immerjs/immer#598]
## 🐛 Bug Report

Hey all!

I'm using the `@reduxjs/toolkit` package which pulls in immer as a dependency

## Link to repro

The repo I'm working on is open-source. you can see the branch where I'm having the issue here: https://github.com/mitodl/bootcamp-ecommerce/compare/ap/drawer-component

## To Reproduce

you can try to run flow on the branch I pasted above. I'm using flow v 0.94.0 (yes, I know it's kind of old).

## Observed behavior

I'm getting a flow error after installing it that looks like this:

```
Error ---------------------------------------------------------------------- node_modules/immer/dist/index.js.flow:32:17

Unexpected token =

   32|     <S: Base, A = void, B = void, C = void>(
                       ^


Error ----------------------------------------------------------------- node_modules/immer/src/types/index.js.flow:32:17

Unexpected token =

   32|     <S: Base, A = void, B = void, C = void>(
                       ^



Found 2 errors
```

## Expected behavior

I think this shouldn't be causing any issues? I am using a relatively new version of flow, but maybe I need to upgrade. Anyhow, I can work around it by ignoring the file in `.flowconfig`, but I figured I would open an issue in case others are experiencing it too.

I noticed a recent PR changed these lines: https://github.com/immerjs/immer/pull/587 so perhaps an issue was introduced then?

## Environment

it looks as if it's pulling in the latest release.

**Comment by aliceriot** [comment]
created a fork of this repo and was able to reproduce the issue by installing `flow-bin@0.94.0` and checking that file: https://github.com/aliceriot/immer

**Comment by mweststrate** [comment]
Please upgrade relevant dependencies first, then report issues.

**Comment by nifgraup** [comment]
This error goes away in flow-bin@0.101.0. The changelog https://github.com/facebook/flow/releases/tag/v0.101.0 mentions a new feature "Function type parameters may now use default arguments."
