### ISSUE TITLE
deep freeze of object property in immerable class

### ISSUE THREAD

**Issue by jeron-diovis** [immerjs/immer#604]
## 🙋‍♂ Question
I'm trying to do smth like this:
```js
class Thing {
  [immerable] = true;

  constructor({ x }) {
    this._data = { x };
  }

  get x() {
    return this._data.x;
  }

  set x(x) {
    this._data.x = x;
  }
}

const thing = new Thing({ x: 1 })
produce(thing, draft => { draft.x += 1 })
```
Here is my sandbox: https://codesandbox.io/s/immerable-83jiv. It does work without any problems. 
In console there you can see, that property `_data` is marked as non-writable and non-configurable, but `_data.x` is writable and configurable:
<img width="700" alt="Screenshot 2020-05-24 23 25 05" src="https://user-images.githubusercontent.com/2756868/82764208-d0a1fc00-9e15-11ea-97fe-776409b3941c.png">
 So, it looks like `thing` is not deeply frozen – despite of `setAutoFreeze(true)`.

At the same time, in my real project, with exactly same setup I get this:
<img width="800" alt="Screenshot 2020-05-24 23 22 38" src="https://user-images.githubusercontent.com/2756868/82764160-799c2700-9e15-11ea-9fff-43801addffce.png">
(it's a redux app with curried producers, as described in [docs](https://immerjs.github.io/immer/docs/curried-produce))
And in console I see that `_state.selected` is non-configurable and non-writable.

I really can't understand why I can't reproduce the same in sandbox, and which of two cases is actually a correct behavior.
If it's possible, can you give any clue about this situation? Like, it has to be smth very basic about immer which I'm missing.

## Environment
- **Immer version:** 6.0.8

**Comment by jeron-diovis** [comment]
I have to reopen this issue. There is still smth wrong, even on version `7.0.5`.
Please check out [this sandbox](https://codesandbox.io/s/immerable-83jiv?file=/src/App.js)

Current sandbox behavior is:
* on first click on "inc" button, both `i` counter and `item.x` prop are updated in sync
* on succeeding clicks on "inc button, only `i` updates, `item.x` remains unchanged. Although no errors thrown.
* after uncommenting line 24 it works normally – both `i` and `item.x` are updated in sync.

In my project, in pretty same situation I have `Uncaught TypeError: Cannot assign to read only property 'x' of object '#<Object>'`. Don't know why this behavior differs, but just reading `_data` before modification still helps, so problem should be the same.

**Comment by mweststrate** [comment]
I'm not sure what 'useReducer(produce)' is supposed to do. Can you simplify
the example a bit and leave React out of it?

**Comment by jeron-diovis** [comment]
[simplified sandbox](https://codesandbox.io/s/immer-issue-604-demo-c28i1?file=/src/index.js)

Now it throws just like it does in my app.

**Comment by mweststrate** [comment]
Thanks for the update!

**Comment by mweststrate** [comment]
Thanks for the detailed reproduction. Will publish a fix soon!
