### ISSUE TITLE
ENV var to toggle immer into ES5 fallback (for debugging purposes)

### ISSUE THREAD

**Issue by Izhaki** [immerjs/immer#607]
## 🚀 Feature Proposal

It would be nice if some ENV variable (say `IMMER_DEBUG=true`) would switch immer to use the ES5 fallback instead of Proxies.

## Motivation

We use immer extensively, both in redux reducers and for pretty much all other immutable state manipulation. 

We routinely use a debugger and wish to inspect the state being manipulated, which is impossible with proxies.

## Can this be solved in user-land code?

Yes it can. One can use `original` to see the data as-is, but that requires transient imports and extra lines of code.

Using `original` may seem reasonable for people using `console.log` for debugging, but it breaks a hard-earned flow of setting up debuggers in VSCode and the likes:

![image](https://user-images.githubusercontent.com/880132/82949929-594aa480-9f9c-11ea-9ba0-943f7f8fa884.png)

By using an ENV variable, we can just add it to the lunch configuration in VSCode and always see the state. Performance matters not for this.

**Comment by mweststrate** [comment]
The `[[target]]` should contain the information you basically need, or you can JSON.stringify or spread in the debug console / a watch expression.

Supporting an env variable can be done in user land code, (e.g. `if (process.env.IMMER_DEBUG==='true) useProxies(false)`) so I don't think there is a real need to solve this in the package.

**Comment by Izhaki** [comment]
I wasn't aware of `setUseProxies(false)` (which requires `enableES5()`), but still no cake with these (note `stepOriginal` on top, and that you see the same under `.t`):

![image](https://user-images.githubusercontent.com/880132/83197575-96966a00-a135-11ea-8fdb-01d273bbc698.png)

> The [[target]] should contain the information you basically need, or you can JSON.stringify or spread in the debug console / a watch expression.

Other than `JSON.parse(JSON.stringify(steps))` I couldn't get any of these to work - spread doesn't work on the debug console / watch expression; simply not sure how I access `[[target]]`? Not sure it is relevant but the structures I'm most interested in are nested.

> I don't think there is a real need to solve this in the package.

Fair enough, I guess this can be easily done by not importing `produce` directly but rather from some module where based on environment variable toggle between immer and some low performing function (like this toy implementation):

```js
const produce = (producer) => (...args) => {
  const [currentState, ...others] = args;
  const draft = currentState ? cloneDeep(currentState) : currentState;
  return producer(...[draft, ...others]) || draft;
};
```

---

So it seems:

- ES5 fallback is not what I'm after after all (just seeing the objects in the debugger as is).
- Easiest solution seems to be a bespoke `JSON.parse(JSON.stringify(something))` on each variable of interest.
- This can be achieved by writing a `produce`-like function and changing all imports from immer.

I'm the first to support keeping api surface minimal, but I still think this will be nice-to-have.

I'm going to close these. Surely if others will want the same they'll find this issue.

**Comment by mweststrate** [comment]
Dont rewrite produce like that, it fundamentally changes its behavior
compared to the original. You dont even need produce anymore if you
deepClone anyway.

**Comment by mweststrate** [comment]
See also #441
