### ISSUE TITLE
NextJS and enabling plugins

### ISSUE THREAD

**Issue by LennardSennep** [immerjs/immer#610]
## 🙋‍♂ Question

We are using immer in our ReactJS project and running it on [NextJS](https://nextjs.org/). We want to implement the `enableES5()` for IE11 but it never resolves on the frontend. We keep getting:

`Error was not caught Error: [Immer] The plugin for 'ES5' has not been loaded into immer. To enable the plugin, import and call 'enablesES5()' when initializing your application`. 

I wonder where we need to place this code to make it run properly. Do you have a solution for this (running it on NodeJS servers or specifically on the NextJS framework)? 

We did not have issues with other NPM's to fire these kind of functions.
We have also tried the other plugins like `enableAllPlugins()` but with the same outcome of niot resolving.

## Link to repro

NA

## Environment

We only accept questions against the latest Immer version.

- **6.0.9**
- [x] Occurs with `enablesES5()`

**Comment by mweststrate** [comment]
I have no experience with NextJS, but calling enableES5 at the begin of your bundle should fix the issue. Whether you did it correctly we can't tell without a minimal reproduction.

**Comment by LennardSennep** [comment]
Hi @mweststrate ,

Thing is with NextJS, you don't have a `ReactDOM.render(element, container[, callback])` function as NextJS is running it. 

There is a file called `_app.js` where you customise the app (more or less same principle), but it doesn't even reach that code in IE11. When I console log on chrome I can see it though so it is clearly imported but not executed on the right moment.

**Comment by LennardSennep** [comment]
in addition: 

I have called the function and logged it, which I can see fire in IE11 but the error appears after:

<img width="1680" alt="Screenshot 2020-05-29 at 10 10 34" src="https://user-images.githubusercontent.com/28601422/83242698-bd37bd80-a194-11ea-8fb2-02259576bd26.png">

**Comment by mweststrate** [comment]
That usually means you have multiple instances of Immer in your app, or your module initialization is incorrect. (I usually use `yarn why immer` to figure that out). 

A foolproof fix could be to wrap produce (assuming you call produce yourself) in some utility file and use that one

```javascript
import origProduce, { enableES5 } from 'immer'

export function produce() {
  enableES5()
  return origProduce.apply(null, arguments)
}
```

calling enableES5 many times is safe and doesn't incur overhead

**Comment by LennardSennep** [comment]
You are right! It needed to be called everytime the produce function is being called. 
I had to change it a bit though otherwise I would get the following error:

"Error: [Immer] The first or second argument to `produce` must be a function"

So I wrote it like this:

`import { enableES5, produce } from 'immer'

export const produceImmer = (...args) => {
  enableES5()
  return produce(...args)
}`
