### ISSUE TITLE
Deep-freezing the state

### ISSUE THREAD

**Issue by shayantabrizi** [immerjs/immer#615]
## 🐛 Bug Report

According to [this](https://github.com/immerjs/immer/pull/417), it seems to me that all objects added to the state are frozen even if they are deep in the tree. However, it seems that immer does not do that:
```
import produce from "immer";

class Node {
  readonly x: number | undefined;

  constructor(x: number) {
    this.x = x;
  }
}

interface IGraph {
  nodes: Node[];
}

const nextState = produce({ nodes: [] }, draft => {
  draft.nodes.push(new Node(5));
});

console.log(
  Object.isFrozen(nextState),
  Object.isFrozen(nextState.nodes),
  Object.isFrozen(nextState.nodes[0])
);
```
nextState.nodes[0] seems not to be frozen.

## Link to repro

See console in [CodeSandbox demo](https://codesandbox.io/embed/lively-cloud-tgt50?fontsize=14&hidenavigation=1&theme=dark). The last value is false. I expect it to be true; Also, I expect "nextState.nodes[0].x = 6;" to fail but it doesn't.

## Environment

- **Immer version:**
6.0.9

**Comment by mweststrate** [comment]
Immer doesn't process classes that aren't marked as immerable, see the
"working with complex objects" docs
