### ISSUE TITLE
Immer isn't updating draft value when it is reassigned directly

### ISSUE THREAD

**Issue by josephdsbr** [immerjs/immer#622]
## 🐛 Bug Report

Immer does not update a value in the draft when it is set directly.

## Link to repro

https://codesandbox.io/s/immer-playground-zp1um?file=/src/index.js

## To Reproduce

1. Create a object `x = { name: 'José' }`
2. Assign to another variable the **produce** of `x`.
3. Try to replace all the draft: 
`y = produce(x, draft => {
 draft = { name: 'Carla' } 
})`

## Observed behavior

The variable y is returning the object: { name: 'José' }

## Expected behavior

The result of the produce should reproduce the changes in the draft. As it is reassigned to another object, then the expected return should be: { name: 'Carla' }. 

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version: 6.0.3**
- [x] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
That is working as expected, as your construction re-binds the local javascript variable `draft` to something else. It is similar to how `let i = 3; i = 7;` doesn't suddenly make `3` a `7` but only rebinds the local variable `i`.

Please read https://immerjs.github.io/immer/docs/return for how to replace the current state with new state.

**Comment by josephdsbr** [comment]
@mweststrate i got it. Apologizes for this. Thanks a lot.

**Comment by mweststrate** [comment]
https://immerjs.github.io/immer/docs/pitfalls#dont-reassign-the-recipe-argument
