### ISSUE TITLE
[Typescript] produce seems to loose reference / destructure original interface 

### ISSUE THREAD

**Issue by IljaDaderko** [immerjs/immer#623]
## 🐛 Bug Report
I'm not sure how to describe this bug, it's actually best shown in that codesandbox. But essentially in my example I am passing current state to `produce` and it correctly inherits its type, I then define my draft and for some reason that type changes into somewhat of an expanded object. This leads to type issues latter on as you will see from example where HTMLImageElement type is no longer valid as draft has an object type with all image element attributes.

## Link to repro
https://codesandbox.io/s/practical-drake-182z5?file=/src/index.tsx

You should see type error on line 16 where for some reason it no longer inherits type as `HTMLImageElement`, but rather makes it an object

## To Reproduce

```ts
import produce from "immer";

interface Store {
  uiImages: Record<string, HTMLImageElement>;
  setImage: () => void;
}

const store: Store = {
  uiImages: {},
  setImage() {
    produce(store, draft => {
      const image = new Image();
      draft.uiImages["test"] = image; // Type Error Here
    });
  }
};
```

## Observed behavior

Overwrites type. In theory it keeps everything as is, but in strict mode types are no longer valid.

## Expected behavior

Should keep exactly same type?

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:** 7.0.1
- [x] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Did you check https://immerjs.github.io/immer/docs/typescript#cast-utilities
and
specifically the cast section?

**Comment by IljaDaderko** [comment]
Noup, this was new to me and it solves this issue. Actually, a really interesting topic I completely forgot that some types can be readonly 👍
