### ISSUE TITLE
Set Removal in Nested Producers are Hanging the Browser

### ISSUE THREAD

**Issue by rafaelcalpena** [immerjs/immer#628]
## 🐛 Bug Report

When removing an array from a Set inside nested producers, the code will hang.

## Link to repro

https://codesandbox.io/s/immer-bug-2qsbe?file=/src/index.ts

## To Reproduce

1. Create an array (or object)
2. Create a Set with the previously created array as one of its elements.
3. Nest 2 produce calls, with second call producing from draft of outer producer.
4. Inside nested producer, delete the array from the set.

## Observed behavior

The code never returns and gets stuck. Note: This doesn't happen with numbers (instead of arrays, please check sandbox example). Also does not happen if provided array is not inserted in the Set. 

## Expected behavior

Code should return Set with removed element.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [x] I filed this report against the _latest_ version of Immer
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Can you reproduce this outside sandbox? For me the sandbox crashes even if I remove all code and immer as dep and just leave a console.log.

**Comment by rafaelcalpena** [comment]
@mweststrate I faced a similar issue too. I was able to "fix" the sandbox crash it by opening the preview in Firefox (it has a stop script button). Also needed to save all files and reload the preview **twice** consecutively. That may be the same reason why the sandbox is crashing for you.

**Comment by mweststrate** [comment]
Added a fix that will address the crash, but I don't think the double produce nesting in the end does what you might expect here, so it might need a revisit
