### ISSUE TITLE
React component rerender only with the current() method

### ISSUE THREAD

**Issue by viclafouch** [immerjs/immer#629]
## 🙋‍♂ Question

I've just begin using Immer.js in my React app. This is awesome ! But I'm facing to a problem.. I'm trying to update a value of an object in an array but my app isn't rerendering.. :/

So i used the new [current](https://immerjs.github.io/immer/docs/current) method of ImmerJS to force my array to be recreated, without this, my app is not rerendering.. But in the doc, `Use current sparingly, it can be a potentially expensive operation, especially when using ES5`. So my question is, how can I do without using the `current` method ?

```javascript

  const [videos, setVideos] = useState([])

  const handleCheckVideo = useCallback(({ id, value }) => {
    setVideos(
      produce(draft => {
        const selectedVideoIndex = draft.findIndex(v => v.id === id)
        if (draft[selectedVideoIndex].selected === value) {
          draft[selectedVideoIndex].selected = 'none'
        } else {
          draft[selectedVideoIndex].selected = value
        }
        return [...current(draft)]
      })
    )
  }, [])

console.log('render') // ONLY WORKS WITH  return [...current(draft)]

```

Thanks a lot ! 

## Environment

- **Immer version:**
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Please provide a test project like a code sandbox example.
