### ISSUE TITLE
Improve interoperability with 3rd party libraries

### ISSUE THREAD

**Issue by dhmk083** [immerjs/immer#631]
## 🚀 Feature Proposal

Allow 3rd party libraries to use `immerable` feature without depending on immer package.

## Motivation

I'm making a library that deals with immutable objects. One of the functions is like this: `update(fn: (state: T) => T): void`. My problem is that the `state` object may contain lazily computed getters, i.e. 
```js
{
  get someProp() { 
    if (!propInitialized) initProp()
    return prop
  }
}
```
If an end-user use immer's `produce` to get a next state, it would forcibly evaluate all getters, which is not desirable. So I did a trick with inheritance and hide all getters behind a prototype. Now `produce` doesn't evaluate getters, but at the same time it requires `immerable` property on a state object. Also, I don't want to make users of my library to depend on `immer` package, so I can not directly import it in my lib. 

Right now `immerable` is defined as a private symbol. A minor change of it to public would solve an issue. 

## Can this be solved in user-land code?

Yes, by changing just [one line](https://github.com/immerjs/immer/blob/d4b2def003425834409c83ae0d6d709b936d55d6/src/utils/env.ts#L35). `Symbol() -> Symbol.for()`

## Example

```js
// a file in my library

// no immer import

const immerable = hasSymbol
	? Symbol.for("immer-draftable")
	: ("__$immer_draftable")

// not a final code
export const wrap = (proto, own) => {
  const res = Object.assign(Object.create(proto), own)
  res[immerable] = true
  return res
}
```

**Comment by mweststrate** [comment]
The latest Immer version uses `Symbol.for` now
