### ISSUE TITLE
Deleting a nested property is not working

### ISSUE THREAD

**Issue by dmarshall83** [immerjs/immer#633]
## 🐛 Bug Report

Using the examples provided I was unable to delete a nested prop in one of my reducers. I was able to get it to work by destructuring the key out and then setting that property of the draft to the remaining value. It's completely possible that this is user error and I'm just missing something. Also sorry if I have not formatted this report correctly

## To Reproduce

Unsuccessful code: 
- I have omitted all but the delete action.
- The action payload is a group id which is the key in the groups object

```
const initState = {
  groups: {},
  loading: false,
  loaded: false,
};

export const groupsReducer = produce((draft, action) => {
  switch (action.type) {
    case DELETE_GROUP:
      delete draft.groups[action.payload];
      return;
    default:
      return;
  }
}, initState);
```

If I change the DELETE_GROUP case to: 

```
case DELETE_GROUP:
      const { [action.payload]: match, ...others } = draft.groups;
      draft.groups = others;
      return;
```

This will work but it seems to defeat the purpose. Also as I understand it this would replace all the groups with a new object which will rerender.

## Observed behavior

Deleting a nested property in the state is not working as expected.  

## Expected behavior

I would expect the delete to remove the key from the nested object.

## Environment
- "redux": "^4.0.5", (if that matters)
- "immer": "^7.0.3",
- [x ] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Could you add a reproduction in code sandbox?

**Comment by dmarshall83** [comment]
I have tried to recreate the issue in multiple ways and I can't, I'm sorry I bother you with this. It is working now. I must have had something in my redux middleware that was causing problems that I have since fixed. Again I'm really sorry to have wasted your time.
