### ISSUE TITLE
Minified CJS bundle doesn't contain plugins

### ISSUE THREAD

**Issue by sconover** [immerjs/immer#635]
(Immer is a great little library, thank you for creating it)

I have a very vanilla TypeScript + rollup project set up, am trying to use the latest version of immer. I would like to make use of the plugins, and while they're "available" as type definitions, the proper plugin js code isn't there at runtime, in my browser bundle.

I've been looking through the immer source and cannot figure out how this *should* be happening - specifically how the plugin ts source is transpiled into js and then ends up in a rollup-produced bundle. I see the minified/production "core" immer js file getting produced under `dist/`...but nothing related to any plugin code. 

I'm sure I'm missing something and would really appreciate a short explanation about how the build and release aspects of the plugin feature work, both out of curiosity and so I can troubleshoot further.

fwiw for now I'm back on 5.3.6 and that's working just fine, including mapset.

**Comment by mweststrate** [comment]
Does your code actually call enableMapSet somewhere?

**Comment by sconover** [comment]
Yes - and `tsc` is happy with it because of what's at the bottom of `immer.d.ts`, 

```export { enableMapSet } from "./plugins/mapset";```

but this fails with (roughly) `enableMapSet is not a function` when my bundle initializes in the browser.

From what I can tell in the minified code (though I may be mistaken), only the core immer module is present - the plugin code is not included. I tried troubleshooting this but am confused about what *would* cause this code to be present in `immer.cjs.production.min.js`. From what I can tell, this code only includes the `enableMapSet` export and checks for the plugin but not the plugin code itself.

I was hoping to understand how this works so I can more productively troubleshoot such problems in the future.

**Comment by mweststrate** [comment]
Might be an issue without cjs build specifically, I think it is rarely used
as bundlers will typically pick the esm build

**Comment by mweststrate** [comment]
I just check the build, and enableMapSet and others seems to be present fine in the CJS bundles. So I guess it is an issue local to your setup, or to a library through which you are using immer indirectly. Both in my local build and on unpkg these functions seem to be available w/o problem:

![Screen Shot 2020-07-24 at 16 42 59](https://user-images.githubusercontent.com/1820292/88409541-fb381300-cdcc-11ea-821b-99f2e9d7cd70.png)

https://unpkg.com/immer@7.0.6/dist/immer.cjs.production.min.js

For any further investigation a minimal test project will be needed.

**Comment by mweststrate** [comment]
Note that if you are building a package, that uses Immer and rolls it up, and you don't call nor re-export plugins; those function will disappear from your bundle, which is exactly what should happen :)

**Comment by mweststrate** [comment]
Closing until more info is available
