### ISSUE TITLE
Mention ImmerJS in Error message?

### ISSUE THREAD

**Issue by sladiri** [immerjs/immer#636]
## 🙋‍♂ Question

Hi, in our project, the developers forget that ImmerJS is included. JavaScript has no immutability built in like some other languages do, so they do not think of ImmerJS when this exception occurs in the screenshot (I just used a screenshot I found). Do you think it is a bad Idea to somehow hint at ImmerJS in the error?

![Immer Exception](https://user-images.githubusercontent.com/2756868/82764160-799c2700-9e15-11ea-9fff-43801addffce.png)

- **Immer version: 6.0.3**

**Comment by mweststrate** [comment]
JavaScript has built-in immutability, through Object.freeze and read only
property descriptors. This error is coming from JavaScript, not Immer
(although the immutable object itself is probably produced using Immer).

**Comment by sladiri** [comment]
I see, thanks for the explanation. By built-in in meant immutability being the default. Id do see your point too, I just wanted ask you for you opinion.
Thank you for your effort.
