### ISSUE TITLE
Callback for applyPatches or an ability to update counter cache

### ISSUE THREAD

**Issue by rrjanbiah** [immerjs/immer#637]
## 🚀 Feature Proposal

Some option to update counter cache. Let's say `todos` has 'count' for total number of todos in the page; if patch is getting applied, need an option to update this `count`

## Motivation

Patch is a very lightweight option to handle realtime applications (say, todos application). But, handling counter cache looks difficult. Had to return total `count` from the server and that seems to defeat the purpose of patch concept

## Can this be solved in user-land code?

Not sure. Not sure if a callback in `applyPatches` https://github.com/immerjs/immer/blob/467ea5d3b5d062c084ce6d875f8d77e21f26965c/src/core/immerClass.ts#L187 would help.

## Example

To update the aggregate of data in the page such as counter cache / count of data. (Mostly `count` alone--less likely sum, average, etc)

**Comment by mweststrate** [comment]
Sorry, it is completely unclear to me what you are proposing. Immer doesn't have counters or todo's. I get that that is probably an example, but then please include the example.

**Comment by rrjanbiah** [comment]
@mweststrate Apologies for my poor English...

For example, in this video series https://egghead.io/lessons/javascript-introduction-to-the-in-depth-immer-course you've used patch to update todos to other users in realtime.

So, the question is how to update the total todos or count of a table listing. For example, from a server, initially, `todos` will be returned like:
```js
{
"todos": [ 
  {"id": 1, "name": "foo"},
  {"id": 2, "name": "bar"}
],
"metaData": {"count": 2} // total count
}
```
So, initially we can show the count. But, when real time activities happen, using the patch concept we're updating the other user. It works excellent, except for the total count display. Say, when one user deletes the item from table, it generates a patch and updates other user(s) too.. but without updating the count.

**Comment by mweststrate** [comment]
Derived data should imho not be stored in your state, but rather be
computed on the fly on the client, for example by using the useMemo hook.
