### ISSUE TITLE
Array patches have become huge again since 7.0.0

### ISSUE THREAD

**Issue by blutorange** [immerjs/immer#642]
## 🐛 Bug Report

There's an old pull request (https://github.com/immerjs/immer/pull/320) which reduced the size of array patches when, for example, the first item was deleted. That PR was released with 2.1.0, and it seems to work until 6.0.9. Since 7.0.0, the generated patches include a replace operation for each index starting at the first modified index.

Was this change accidental, or is there some reason for it? Would be great if the previous behavior could be restored, as this can result in pretty huge patches for array of medium size with items of medium size, especially when patches are stored in memory for a redo/undo feature.

## Link to repro

Code (from the previous bug report #319):

```javascript
produce(
  [1, 2, 3],
  draft => { draft.splice(0, 0, 0) },
  patches => console.log(JSON.stringify(patch))
);
produce(
  [1, 2, 3],
  draft => { draft.splice(0, 1) },
  patches => console.log(JSON.stringify(patch))
);
```

Until 6.0.9, the patches only include what's actually changed (the expected behavior):

https://codesandbox.io/s/immer-from-egghead-tutorial-gucl4?file=/index.js

```text
{"op":"add","path":[0],"value":0}
{"op":"remove","path":[0]}
```

With 7.0.0 - 7.0.5, the patches include more operations than necessary:

https://codesandbox.io/s/immer-from-egghead-tutorial-28g70?file=/index.js

```text
{"op":"replace","path":[0],"value":0}
{"op":"replace","path":[1],"value":1}
{"op":"replace","path":[2],"value":2}
{"op":"add","path":[3],"value":3}

{"op":"replace","path":[0],"value":2}
{"op":"replace","path":[1],"value":3}
{"op":"replace","path":["length"],"value":2}
```

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:** 7.0.5
- [ x ] I filed this report against the _latest_ version of Immer
- [ x ] Occurs with `setUseProxies(true)`
- [ x ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by blutorange** [comment]
Hmm alright, I found #468 where it seems this was changed. I guess there's nothing that can be done? I guess this can be closed if nothing can be done... It's just that just adding an item near the beginning of an array result in pretty much the entire array being in the patch.

**Comment by mweststrate** [comment]
You can do your own post processing of the patches. Our primary concern is
to have them to be correct. Having them minimal is a tradeoff that adds
huge complexity (computing the best diff possible is a really hard problem)
and perf penalties at generation phase but saves it on application phase.
So I recommend to make you own smarter diff that takes base/end/patches and
compresses / optimizes them for the scenario that suits you best. The
current patches merely reflect how the language itself updates the
descriptors in the array (so this could theoretically even differ per
browser).

**Comment by blutorange** [comment]
Thanks for the quick reply. Well, yeah, I could try some external diff library, although in my case, the producers are centralized in a file, I know exactly what I'm changing, so I can just generate patches based on that.
