### ISSUE TITLE
Setting object property with 'undefined' value to 'undefined' breaks immutability

### ISSUE THREAD

**Issue by davidye** [immerjs/immer#646]
## 🐛 Bug Report

```
const { produce } = require("immer");
const foo = { bar: undefined };

console.log(produce(foo, draft => { draft.bar = undefined; }) === foo);
> false
```

This code evaluates to false when I would expect it to evaluate to true.

## Link to repro

https://codesandbox.io/s/immer-sandbox-su9pe?file=/src/index.ts

## To Reproduce

Try code above in node.js or chrome with latest immer 7.0.5

## Observed behavior

When setting an object whose property is undefined to undefined, a different object is returned

## Expected behavior

When setting an object whose property is undefined to undefined, the same object is returned

## Environment

- Node.js and Chrome
- Immer 7.0.5

**Comment by davidye** [comment]
Looks like this is a regression starting from 7.0.0 - works as expected in codesandbox.io when I switch to version 6.0.9

**Comment by mweststrate** [comment]
Thanks for the detailed reproduction. Will publish a fix soon!
