### ISSUE TITLE
ImmerJS as a reactive store

### ISSUE THREAD

**Issue by sergeyt** [immerjs/immer#654]
## 🙋‍♂ Question

Does ImmerJS support any kind of events? I found a mention off `PatchListener` in the codebase. Is it related to the question?

**Comment by sergeyt** [comment]
see also #29

**Comment by mweststrate** [comment]
Nope, but you can use patches to detect fine grained changes if you want.

**Comment by mweststrate** [comment]
See https://immerjs.github.io/immer/docs/patches and the linked vids there for details on patches
