### ISSUE TITLE
Immer doesn't respond to changes made on a class property

### ISSUE THREAD

**Issue by akashishu777** [immerjs/immer#655]
## 🐛 Bug Report

Immer doesn't respond to the changes which we make in the class property, I am assigning an object to the state variable, and if we make any changes to the class property from reducer case the connect function doesn't detect any changes as the state variable reference is not being changed.

When I forcibly assigning the condition to draft.group.conditions (uncomment line no 44) than its working. 

## Link to repro

https://codesandbox.io/s/winter-tree-sw436?file=/src/reducer.js
When I click on push into the array button it adds value to the class property items but the dimmer doesn't seem to be considered as a state change.

## To Reproduce

Steps to reproduce the behavior: Click on push into array it's not rendering the item value to UI

## Observed behavior

The component is not rendering as immer is not considering as a state change.

## Expected behavior

It is expected that the connect function should detect these changes and the component should get re-rendered.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version: 7.0.7**
- [ x] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by Crazybutch** [comment]
Have a look at this Documentation: https://immerjs.github.io/immer/docs/complex-objects

Change your import in Line 1: import {produce, immerable} from "immer";
Add following Line in constructor(): this[immerable] = true;

**Comment by akashishu777** [comment]
Thanks @Crazybutch, It works. This is not a bug.
