### ISSUE TITLE
Typescript: suboptimal declaration files in some situations

### ISSUE THREAD

**Issue by 11bit** [immerjs/immer#657]
## 🐛 Bug Report

Yet another issue with typings in redux-toolkit that boils down to Immer. 

In short, Immer uses recursive types in Draft with an anonymous type. In some situations typescript doesn't handle it well and produces suboptimal declaration files:

For instance, if there is a type SomeType with the shape `{ some: string, example: number  }` and its draft version Draft<SomeType> in some cases in declaration files instead of having Draft<SomeType> typescript expands the types and produce `{ some: string, example: number  }`. 

This can be a problem in big projects where Draft<SomeType>  is used often and SomeType is big because typescript generates huge declaration files which slow it down (especially in a watch mode)

I made a simple example with redux-toolkit here https://github.com/11bit/rtk-typings. For every reducer in `createSlice` function, it duplicates the full shape of the State object. 

As a workaround (before typescript creators will improve it on their side) we can extract anonymous type from Draft into a named one:

Change this:
```
export type Draft<T> = T extends AtomicObject
        // ....
	: T extends object
	? {-readonly [K in keyof T]: Draft<T[K]>}
	: T
``` 

to this 
```
export type ReadWriteDraft<T> = {-readonly [K in keyof T]: Draft<T[K]>};'
export type Draft<T> = T extends AtomicObject
        // ....
	: T extends object
	? ReadWriteDraft<T>
	: T
```

What do you think?

## Link to repro

https://github.com/11bit/rtk-typings

## To Reproduce

Clone repo and run yarn & yarn start

## Observed behavior

ST type's shape is duplicated multiple times in `dec/index.d.ts` file

## Expected behavior

ST type is used by it's name.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [ ] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Since your state isn't marked readonly, I'd expect if you mark your
reducers as type `(state:State)` it will work as well

**Comment by 11bit** [comment]
Yes, I totally agree with you. But it is quite annoying to type state everywhere and, what's more important, there are probably more such cases. There are a lot of [bug reports](https://github.com/microsoft/TypeScript/issues/34119) in TS repo regarding similar issues in various libs. Since it's a small change it might be an easy improvement for the ecosystem.

**Comment by mweststrate** [comment]
Feel free to open a PR
