### ISSUE TITLE
changing array causes the array's other keys than index disappear

### ISSUE THREAD

**Issue by tomwang1013** [immerjs/immer#660]
## 🐛 Bug Report
Changing an array(e.g. `push`, `splice`, etc) causes other props than index(0,1,...) disappear

## To Reproduce

```javascript
const { produce } = require("immer");

const arr = [1, 2, 3];
arr.key = 'abc';
console.dir(arr);  // [ 1, 2, 3, key: 'abc' ]

const newArr = produce(arr, draft => {
  draft.push(4);
});
console.dir(newArr)  // [ 1, 2, 3, 4 ]
```

## Observed behavior

`arr['key']` disappeared

## Expected behavior

`arr['key']`  remained unchanged

## Environment

- **Immer version:**  7.0.8

**Comment by mweststrate** [comment]
Correct, arbitrary properties on arrays aren't supported. And for any future readers of your code it will be less confusing if you don't use them either :)

**Comment by mweststrate** [comment]
https://immerjs.github.io/immer/docs/pitfalls#only-valid-indices-and-length-can-be-mutated-on-arrays
