### ISSUE TITLE
draft.allTodos.push is not a function

### ISSUE THREAD

**Issue by Vince-vegas** [immerjs/immer#662]
When I push the new item why immer throws an error
I am using React Hooks and Switch Statements

code:

      
      const todosState = {
       currentTodos: [],
       allTodos: [],
       activeTodos: [],
       completedTodos: [],
     };

      const todosAction = (draft, action) => {
       switch (action.type) {
         case 'add-new-todo': {
          draft.allTodos = draft.allTodos.push({ id: 3, task: 'test' });
           return;
         }

        default: {
          return draft;
        }
     }
    };

**Comment by mweststrate** [comment]
Closing for the lack of a reproduction. Please follow issue template next time.

**Comment by Vince-vegas** [comment]
I just solve it

Great Library Thanks Immer
