### ISSUE TITLE
Babel plugin for immer

### ISSUE THREAD

**Issue by Aetet** [immerjs/immer#666]
## 🚀 Feature Proposal

Babel plugin for code generation instead of proxifying properties

## Motivation

Current implementation is extremely slow on 1к update operations. 
For my i7-5500 it takes 700ms.
For Object.assign it requires just 32 ms. 

[Dart implementation](https://pub.dev/packages/built_value) based on codegen requires 60ms for update similar shape object.

Immer can export API to create babel plugin which should be used for production environment at build phase. 

It slightly overhead size of application, but it significally increase performance.

## Can this be solved in user-land code?

Code like this:
```
  produce((draft) => draft.a = 10)
```
could be generated to:
```
produce((draftProxy) => draftProxy.set(['a'], 10))
```
etc.

So this will be reasonable trade off between public API simplicity and code performance.

**Comment by mweststrate** [comment]
Sounds like a cool idea that can be build as separate project? Feel free to
take a stab at it

**Comment by mweststrate** [comment]
Closing as this is a problem that can be solved outside the scope of this project
