### ISSUE TITLE
why the currying function receive only state , but the source code shows three params

### ISSUE THREAD

**Issue by HomyeeKing** [immerjs/immer#668]
if we only pass the `producer`, we will get a currified function which receives one parameter `state`,but the source code is 

``` js
return function curriedProduce(
				this: any,
				base = defaultBase,
				...args: any[]
			) {
				return self.produce(base, (draft: Drafted) => recipe.call(this, draft, ...args)) // prettier-ignore
			}

```

I don't understand why this goes wrong?

![image](https://user-images.githubusercontent.com/49113249/92719658-14554d00-f396-11ea-9bfc-44751cc3b8c1.png)

**Comment by mweststrate** [comment]
`this: any` isn't an actual argument, just a type annotation for the `this`
inside the Function for TS. So it should be called like `setItemDone(arr)`

**Comment by HomyeeKing** [comment]
@mweststrate  thx for ur patient explain, I have checked the TS DOCS , I do miss this part , 
btw, `immer` is  an awesome work
I hope I can make something like this one day, but it's still hard for me to understand the source code now 😅


leave the offical doc:
https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters
