### ISSUE TITLE
Cyclic data structures

### ISSUE THREAD

**Issue by nehz** [immerjs/immer#672]
## 🐛 Bug Report

Not entirely sure if this is a design decision or bug, but immer seems unable to deal with cyclic data structures
Example:
```
import produce from 'immer'

interface A {
  b?: B;
}

interface B {
  a: A;
}

const AObj: A = {}
const BObj: B = {a: AObj}
AObj.b = BObj

const nextState = produce({AObj, BObj}, draft => {
  const B2 = {a: AObj}
  draft.BObj = B2
})
```

Output on Chrome `Version 85.0.4183.102 (Official Build) (64-bit)`:
```
Uncaught RangeError: Maximum call stack size exceeded
    at Function.isArray (<anonymous>)
    at o (immer.esm.js:22)
    at i (immer.esm.js:22)
    at M (immer.esm.js:22)
    at A (immer.esm.js:22)
    at eval (immer.esm.js:22)
    at eval (immer.esm.js:22)
    at Array.forEach (<anonymous>)
    at i (immer.esm.js:22)
    at M (immer.esm.js:22)
```

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version: 7.0.9**
- [x] I filed this report against the _latest_ version of Immer
- [X] Occurs with `setUseProxies(true)`
- [X] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
By design, see bullet 3 https://immerjs.github.io/immer/docs/pitfalls

**Comment by nehz** [comment]
Thanks for the reply, had a inkling that was the case. It is possible to "stop" immer from looking at a key/object during the draft to break this cycle? Here I am guessing it is introspecting `draft.BObj`, is there a way to make it just do the assignment and not look for any other changes, e.g treating it as immutable just for that draft?

**Comment by mweststrate** [comment]
Things in the draft that are either frozen, or instances of a class won't
be inspected further
