### ISSUE TITLE
"Maximum call stack exceeded" in production while dealing with arrays

### ISSUE THREAD

**Issue by bhollis** [immerjs/immer#673]
## 🐛 Bug Report

This appears to be similar to, if not exactly the same as https://github.com/immerjs/immer/issues/198. I verified that downgrading to version 6.0.9 fixes it, so it may be the same `sideEffect` declaration in `package.json`.

I have some state that I'm operating on that's effectively an array of objects (A), each of which has as a property another array of objects (B). In my producer function, I'm modifying properties of those leaf (B) objects, as well as adding them to, and removing them from, the inner arrays (B). For example, I'm deleting an object from one B array (e.g. in A[0]) and adding it to another B array (in A[1]).

## To Reproduce

Unfortunately, I haven't managed to reproduce this locally (in node or in browser) or on CodeSandbox. Only our deployed production build had the problem. I was able to verify through Sentry.io that downgrading to v6 stopped this error from happening.

## Observed behavior

An infinite recursion leading to "Maximum call stack exceeded", coming from inside the immer code.

## Expected behavior

State to be updated or at least an error.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [x] I filed this report against the _latest_ version of Immer
- [x] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

I haven't tried `setUseProxies(false)` - we only run in environments which use proxies.

**Comment by mweststrate** [comment]
Did you try changing the sideEffects to see if it makes a difference? You
can use patch-package to automate that if needed. Secondly, if you force
autoFreeze in prod, does that make a difference?

**Comment by mweststrate** [comment]
Also, do investigate on which browsers the exception occurs. It could be
interference from some polyfill.

**Comment by bhollis** [comment]
Good suggestions, I'll do those experiments and get back to you.

**Comment by cuchac** [comment]
Hello,
I'm also having this problem. I spent several days trying to fix it and then desperately trying to remove dependency on Immer. Finally I was able to find the cause few days ago:
I use Immer to produce patches and implement undo/redo. These patches I was storing also inside state managed by Immer. And that was the reason. If I store large patch to variable inside Immer produce() function, I sometimes get this error.

**Comment by Subha** [comment]
I am also having the same issue and this happens only when i have large items in the page like Grids, when i downgraded to 6.0.9 i do not see the issue. I tested it in multiple browser as well. Like Bhollis reported this looks similar to #198. Can someone please look into this issue or provide a work around?

Thank you

**Comment by santiblanco99** [comment]
Any luck with this issue? The bus is still happening in my case, using v9.0.15

**Comment by johnjom10** [comment]
Does the array contain something that is self referencing ie, a  circular structure?

**Comment by toy9986619** [comment]
I meet a similar issue in my app when using redux-toolkit, and I try to make a small repo to reproduce this issue.

I make a react component with using styled (from @mui/material/styles, @emotion), it will crash when the reducer change.
If the data use a native div or "Box" component (from material-UI), it will not crash.

It doesn't crash when I use development mode.

link: https://toy9986619.github.io/immer-issue/
repo: https://github.com/toy9986619/immer-issue

**Comment by carlesandres** [comment]
I'm experiencing this with v10.0.1 only in production mode, dev mode is fine.
The same issue happened in v9.
My array does not contain any circular references.

**Comment by mweststrate** [comment]
This issue is closed, please open a new one and provide minimal
reproduction. You might be storing some alien object accidentally

**Comment by SCLeoX** [comment]
@carlesandres Thank you so much. This was my exact issue. Thank you for leaving a clear explanation and solution here. 👍
