### ISSUE TITLE
Error when rebuilding Date with patches

### ISSUE THREAD

**Issue by jgrenon** [immerjs/immer#676]
## Report

When using new Date as a field value in a draft, the resulting patch doesn't produce a valid date when replayed. 

## Link to repro

https://codesandbox.io/s/immer-sandbox-forked-wzvm6?file=/src/index.js

## To Reproduce

Run the code above and look in the console. 

## Observed behavior

After patch is applied, date is null.

## Expected behavior

After patch, date should be a valid primitive date

## Environment

Node.JS 14.8.0
Immer  7.0.9

**Comment by ebataille** [comment]
I got a bug too here, but don't have the same problem,

Wehn I appluPatches with date, and then do a date.getDate, I Have
`this is not a date object`

I found where the issue happen in Patches.ts in the function deepClonePatchValue

`const cloned = Object.create(Object.getPrototypeOf(obj))`

should be

`const cloned = obj instanceof Date ? new Date-obj) : Object.create(Object.getPrototypeOf(obj))`

It solved the issue for me

**Comment by mweststrate** [comment]
Looks like the `deepClonePatchValue` misses a pre-condition `if (!isDraftable(obj)) return obj`

**Comment by ebataille** [comment]
Any idea of a workaround while this bug is fix ?

**Comment by mweststrate** [comment]
Opening a PR or patch-package

**Comment by mweststrate** [comment]
Should be fixed in 7.12
