### ISSUE TITLE
Immer doesn't update variable post update

### ISSUE THREAD

**Issue by developdeez** [immerjs/immer#678]
I recently updated to latest (7.0.9) and suddenly the draftstate doesn't update the variable.

```
     const previousResult = produce(prev.getInbox, (draftState) => {
            if (draftState) {   
                draftState = [newInboxMsgSubscribe, ...draftState];
            }
          });
          return { getInbox: [...previousResult] };
```

What changed to stop this from working anylonger?

It will update when using push but I need to replace the entire array

**Comment by mweststrate** [comment]
Please follow the issue template.
