### ISSUE TITLE
Missing dist files in @7.0.13

### ISSUE THREAD

**Issue by apostolos** [immerjs/immer#685]
## 🐛 Bug Report

`./dist` folder is empty (besides index.js). Published npm package is unusable:
https://unpkg.com/browse/immer@7.0.13/dist/

![image](https://user-images.githubusercontent.com/41679/96647620-af96f600-1336-11eb-9183-9b0c38e4921b.png)

**Comment by ronaldgj** [comment]
Just noticed same.

**Comment by dsebastien** [comment]
+1, I just broke my repo by merging the update a tad too fast ;-)

**Comment by mikepage** [comment]
Reference: https://github.com/reduxjs/cra-template-redux/issues/30

**Comment by dsacramone** [comment]
same, build broke :-(

**Comment by nobrayner** [comment]
Just found this while trying to spin up a new create-react-app project with the redux-typescript template...

**Comment by mikepage** [comment]
Quick fix for yarn users, add this to the package.json file. 

```
"resolutions": {
    "immer": "7.0.9"
},
```

Read more: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by mweststrate** [comment]
hmm somehow the build doesn't bail out from releasing when there is a build error in CI. Any PR on the `.travis.yml` file to fix that is welcome :)
