### ISSUE TITLE
Could there be a Draftable type for ts?

### ISSUE THREAD

**Issue by otakustay** [immerjs/immer#689]
## 🚀 Feature Proposal

Many times we have a function like `type Next<S> = (s: S) => void` and directly or indirectly use it to `produce` function, and this always produces some type error like:

```
'S' could be instantiated with an arbitrary type which could be unrelated to 'Draft<S>'.
```

In this case, is it possible that we can have a `Draftable` type so that a `Next<S extends Draftable>` can satisfy `produce` function.

## Motivation

This can significantly help users to reuse existing function types and integrate them with immer.

## Can this be solved in user-land code?

I don't think this can be solved in user-land.

## Example

In a real world case, we have a `useMethods` react hook to wrap an object of methods into a state:

```ts
interface ImmerReducers<S> {
    [key: string]: (state: Draft<S>, ...args: any[]) => S | void;
}

type MethodsHook<S, R extends ImmerReducers<S>> = [S, Methods<S, R>, Updater<S>];

function useMethods<S, R extends ImmerReducers<S>>(reducers: R, initialState: S | (() => S)): MethodsHook<S, R>;
```

Then, since we require `Draft<S>` in `ImmerReducers`, all other hooks built on this `useMethods` are required to introduce `Draft<S>` in there methods, as an example, the `useArray` hook:

```ts
const arrayMethods = {
    push(state: T[], item: T) {
        state.push(item);
    },
    unshift(state: T[], item: T) {
        state.unshift(item);
    },
};

function useArray<T>(initialValue: T[]) {
    return useMethods(arrayMethods, initialValue);
}
```

is type invalid, we have to modify all methods to something like `push(state: Draft<T[]>, item: T)`, this is very unfriendly to users.

**Comment by mweststrate** [comment]
sorry I have trouble following your problem or solution. Can you make it a bit more minimal and put it in a code sandbox / typescript playground?

**Comment by otakustay** [comment]
Maybe this is related to `use-immer` package, I have created a sandbox: https://codesandbox.io/s/immer-updater-type-error-8u7wf?file=/src/App.tsx

Line 9 of `App.tsx` reports an error like:

```
Argument of type 'Draft<S>' is not assignable to parameter of type 'S'.
  'S' could be instantiated with an arbitrary type which could be unrelated to 'Draft<S>'.
```

I'm wondering if this can be solved by add a restriction to generic type `S` like:

```
function useImmerWrap<S extends ???>(fn: (current: S, ...args: any[]) => S | void, setState: Updater<S>)
```

**Comment by mweststrate** [comment]
Looks like just using `Draft` works perfectly fine? https://codesandbox.io/s/immer-updater-type-error-forked-x0j1u

**Comment by otakustay** [comment]
This issue seems more complicated, I was extending this to a generic methods factory: https://codesandbox.io/s/immer-updater-type-error-forked-3i7q1?file=/src/App.tsx

With a factory function the type inference seems broken (line 48, it's type is infered to `Draft<T>[]` but not `Draft<T[]>`), I realized that this is not a problem with immer's type, but still find no good solution to it. If this is not resolvable from immer's side, I can close this issue and introduce some `as any` magic to get rid of the type warning.

**Comment by otakustay** [comment]
Also I created a typescript playground to reproduce this issue more straightly ([see here](https://www.typescriptlang.org/play?#code/PTAEEsFtIUwJwFABMYGMA2BDONQBcBPAB1wEE8B7ScVAeQCMArNPUAXlADEBXAO1TzgKvUAB9QABThVwAZxgAeTLwIA+MaAAimPLnEAlGAHMAogA8iGgEIUK6GMo0A5bpHrwNAZTxxwvIwDcCMAAVCEIoCGgAJIAZvgAFrjo4PSgAEQmngBMAIwADACsAHSodvYCQryy6RCyoLwUrH4Y3ChIECJ4smW8seBGxYyywgA0EVGEJPUpANa4hphIwugEpHBwmASjoADqDrMAspiWMHioxaCxmOjooPSYqLP4FKAABsoEb6AAFLIkqHA-RgHUaAHckjgAJQTUAUODvADeAF9vj9YtJIIlcI0UPhiDBZFCdn57k0EqBUJh5PUYLxdL5-KBHH5+rpQDhUNw4LIqp1YUQdAyRJAdKgEn4jPiSKBRUQiJLZLCACoS+pTXBUkTuUDceQdSiU6msPBJeTSwkvd4ANwo4CQ31JpsJmuphOKE2ACBgFnhrBQGGwuA1MVipGtmHAWHo9gUyp2nBu6AeT3YoFt9vUHB83D0Vxu5p9ul4SHqP2VoCLdNLDRg1o8AH58HBc6AAFz59DyKGgJuJ24p54d+YECjxCtVkv1Xh1xtcJOD9ugZVBULhSLLs24WQJCjcdAdAuvGf1hE6uUkDr0bisSB61g63SyXSH2IMjnGffYUDHSzKJCwp4ZyesgaBYDgFp7AchixPAdKoJaHBxOGkbRrG+yYEcJxKCoOyfKo6jiMhEZRpgMaKBhsxAXgOFqKoQQ+kQfqgAG4HBgSey+HgZH2JomxvnGWagIiESgGJAC0OBLCsBCgAA2gA0p0oAjmOy4ALodnxmACcqinqfRCDIkEIbabpQkTmYxY1uQMh0EwLC9suS6WdZ9TEahPGKIsyy8Ksv4KKyHgKSSfQeAAagRTkBWZNEKaoOyxQokXqB2rnVu5YYkWh3kOL5qzUYFYUIilTmFUlpVpZWVkZVBmEwXB-CWk2FZVZONYUA5AhObsXFeUlyqpcuq5gKZ-E0YNaaIopymqeOmnLvpxkIMEYB6vA4lQLAiAhgAqkQSA6PACieEJ6Idj8SDjVp40naoPZsOoGYdOIngPU9dpIEEq26vIcDiVgJber6cDNPS8DXAhMTQPAhhINwCE8ndwmiWJckjh2z6MkYC1-Nxug3TpNGnTsxRk9gRiyB2nxyep72gJ4GjPUEyIrSG3i+EQglpulU6-M+R3U7hoBk8UFNU50sEIhI9OfE5Pyi+LHYy+wH32kuJ7wN9jHMSGhxnLupYnTs+jVW50PbXDCPwLId1CdNSmknNoD6AtHPgFz+j6aoy0ILEfCVMIoBgpsXOeCbZu1dEMNwFbiO26dqg-Dg8Pxx2+g7PIeDeILoD7YdDJ3VCHb66aFBG+HLvqCJYliTgeDciIDDMAIxQjrIycgtbPJQsUKfWz8qO12JPywGXpY7CO9M18Ps9ib0z5XCIHD9-H6MwAQ6lBHPc8Lw+e4lmmCvk3AlNCwQtP01nOe6H8qtL38pMn5TUJQtvO-D83LBi7IvJGLwo8Dbl1kDsaaI4Fr0APkgZEb8h4f3ro3WUQDSzvznsicYH8UTMnqKXQ2CcTaqCHrA1mfsA6CCDqgKSuh1ibAIHHG2gkfg9hnnXM4iCWGzyIHqBIeNc56XUiSXQkA0rMLgTvAWuhihcJ3D8cAQjYEf3QUPZavt-b8HISIbAtDcHAMYaI4ee9QDX3xjADs+cjpwDjLTM609lrDwQXAEQIcTg-EoQ4ahGwtj0KRoNJhmczg3xgMQlahix54LTForYOija8FcO4OASdYFhOAVI7hPxcjZAAMxvyAA))

It seems type `Draft` has some issue meeting complex type inferences, I tried to change it to a more simpler`type Draft<T> = {[K in keyof T]: T[K]}` then all type check passed

**Comment by mweststrate** [comment]
`{[K in keyof T]: T[K]}` Doesn't recurse. 

Closing this for now, it seems at first sight the casts are only needed for your generic utilities, but that the actual reducers are typed fine. In my experience generic meta programming stuff practically always needs some manual casting, and I think that is completely fine as it isn't directly API user facing.
