### ISSUE TITLE
Plugin not loaded for @xstate/immer

### ISSUE THREAD

**Issue by FredyC** [immerjs/immer#691]
## 🙋‍♂ Question

I am making it like a question because I don't have enough for reproduction. I am using `@xstate/immer` which is [a fairly simple binding](https://github.com/davidkpiano/xstate/blob/master/packages/xstate-immer/src/index.ts) for XState. Today I started getting errors from the production like:

> [Immer] minified error nr: 19 ES5. Find the full error at: https://bit.ly/3cXEKWf

Looking at the error list I see that "plugin not loaded", but I have no idea what that means. The binding doesn't seem to use any plugins.

## Link to repro

Did not really manage to reproduce this locally and I have fairly extensive automated tests.

## Environment

Even though `@xstate/immer` is configured with Immer V6, running `yarn why immer` in the project I am getting `immer@7.0.8`. Could it be there isn't some breaking change handled properly?

_Sorry, if I am too vague. I am rather tired from launching product after 8-month work 💦_

**Comment by mweststrate** [comment]
It means that enableES5() needs to be called if you want to support Immer in browsers that don't support Proxy

**Comment by FredyC** [comment]
Right, that makes sense, should have realized that seeing ES5 in the message and it's coming from IE11. Are there any drawbacks to enabling it? As I understand from docs, it's just a fallback and it won't affect other users?

**Comment by mweststrate** [comment]
Correct, just a KB extra, which mostly matters for hypothetical discussions
so loved by programmers :P

**Comment by mweststrate** [comment]
Yeah, will unminify the exception in the next version, as this exception is
something that is more likely to escape the dev street
