### ISSUE TITLE
Proxy has already been revoked. No more operations are allowed to be performed on it (only in production)

### ISSUE THREAD

**Issue by maksimr** [immerjs/immer#695]
The code below will throw error if use production version of immer but all **works fine in development**. This difference is not obvious, maybe better to make behaviour consistent in this case by default in both envs. Thanks

```js
 const state = produce({ x: {} }, (draft) => {
    const x = draft.x;
    x.foo = true;
    draft.y = { x: x };
  });
  console.log(state.y.x.foo);
```
https://codesandbox.io/s/adoring-carson-dc8ni?file=/src/index.js:0-61

With `import { produce } from "immer/dist/immer.cjs.production.min";`
```
TypeError
Proxy has already been revoked. No more operations are allowed to be performed on it
```

All works fine with `import { produce } from "immer/dist/immer.cjs.development";`

-----

Expected result:
- Consistent behaviour in both envs

```
immer@7.0.14
```

**Comment by mweststrate** [comment]
The state you are producing is not a tree but a graph, in which case
Immer's behavior is not defined.

**Comment by maksimr** [comment]
@mweststrate you can look on it as on a tree, it doesn't matter would be result of `y.x` the same object as x or copy. 
But current issue about inconsitency between dev/prod env. It would be nice to have an error early in dev.
If enable wishful thinking I want to produce plain object without proxy in this particular case. I know that I can use `original` or built in JS functionality to get what I want but it break abstraction around draft

**Comment by mweststrate** [comment]
>  you can look on it as on a tree

It is not a tree

>  It would be nice to have an error early in dev.

P.R welcome, but only if you find a cheap way to detect it. Manually configuration setAutoFreeze (to either true or false) will probably remove the difference between prod and dev.

**Comment by maksimr** [comment]
> It is not a tree 

It’s perfectly valid tree, it does not matter that some nodes reference on the same memory

> P.R welcome, but only if you find a cheap way to detect it. Manually configuration setAutoFreeze (to either true or false) will probably remove the difference between prod and dev

Ok, thanks
