### ISSUE TITLE
Support generate patches with custom scope

### ISSUE THREAD

**Issue by WanderWang** [immerjs/immer#697]
## Motivation

generate patches with custom scope

## Example

A simple usecase

```javascript
const state = { data:{...} , tempData:{...} };
const state2 = produce(state,( draft)=> draft.tempData.x = 1, ( patches,inversePatches)=>{});
```
I want to only generate patch when state.data changed.
Here is my temporary solution 

```javascript
const state = { data:{...} , tempData:{...} };
const state2 = produce(state,( draft)=> draft.tempData.x = 1, ( patches,inversePatches)=>{
    patches = patches.filter(patch => patch.path.some(path => path === 'data'));
    inversePatches = inversePatches.filter(patch => patch.path.some(path => path === 'data'));
});
```

If I can control patches's scope , it maybe have a better performance 

```

**Comment by mweststrate** [comment]
It is allowed to nest producers, so inside your outer produce, you can create an inner produce to capture the mutations to a specific piece, like:

```
let patches, inversePatches
produce(state, draft => {
   draft.somethingElse++
   draft.data = produce(draft.data, () => { /* mutations */ }, (p, i) => {
      patches = p; inversePatches = i
   })
});
```

**Comment by WanderWang** [comment]
> It is allowed to nest producers, so inside your outer produce, you can create an inner produce to capture the mutations to a specific piece, like:
> 
> ```
> let patches, inversePatches
> produce(state, draft => {
>    draft.somethingElse++
>    draft.data = produce(draft.data, () => { /* mutations */ }, (p, i) => {
>       patches = p; inversePatches = i
>    })
> });
> ```

Thank u @mweststrate  , your solution works well in a simple case but still cannot slove my problem , because I cannot modify data.somethingElse in nested callback ( because the paramter in callback is draft.data )

**Comment by mweststrate** [comment]
Give one of them a different name

**Comment by mweststrate** [comment]
Closing as the question seems answered.
