### ISSUE TITLE
Add example for using in graphql.

### ISSUE THREAD

**Issue by sahilrajput03** [immerjs/immer#699]
## 🚀 Feature Proposal

I would like you guys to add some introduction for usage of immer for grpahql in official docs.

## Motivation

Its not mentioned in immerjs docs about usage for graphql, which is very popular technology these days.

## Can this be solved in user-land code?

Yes, no code changes are required.

## Example

[Can be found here.](https://docs.gitlab.com/ee/development/fe_guide/graphql.html#immutability-and-cache-updates)

**Comment by anaibol** [comment]
This is a very interesting idea indeed. transforming data to expose it with the right shape in a graphql api
