### ISSUE TITLE
Fastest way of obtaining Nth state

### ISSUE THREAD

**Issue by Sun-2** [immerjs/immer#700]
## 🙋‍♂ Question

I'm using Immer + Redux inside a NodeJS application. To ease debugging, the application saves all patches to a file.

What would be the *fastest* way of calculating the Nth state? Is there some "mutable" mode, where Immer forgoes immutability while applying patches to boost performance? 

If not, before I look into Immer's codebase, would it be quicker to fork Immer, or just write my own patch applier?

## Environment

- **Immer version: `"immer": "^7.0.14"`**

**Comment by mweststrate** [comment]
Not sure if I understand your question, but using applyPatches inside
produce should do just that.

**Comment by mweststrate** [comment]
Closing question as answered, feel free to comment if that interpretation is incorrect.
