### ISSUE TITLE
 "[Circular reference found] Truncated by IDE"

### ISSUE THREAD

**Issue by JianLin176** [immerjs/immer#711]
原来的代码：
`
rawStateHistory=globalData[STATE_HISTORY_KEY]).

expect(globalData[STATE_HISTORY_KEY]).toEqual( produce(rawStateHistory, (draft) => {
                draft.push(produce(rawTableState,(draft)=>draft))
            }));`
报错` "[Circular reference found] Truncated by IDE"`

修改后正常
`
rawStateHistory=JSON.parse(JSON.strifying(globalData[STATE_HISTORY_KEY]))

expect(globalData[STATE_HISTORY_KEY]).toEqual( produce(rawStateHistory, (draft) => {
                draft.push(produce(rawTableState,(draft)=>draft))
            }));`

**Comment by mweststrate** [comment]
Closing for the lack of any relevant information
