### ISSUE TITLE
Arrow functions in produced classes return old values

### ISSUE THREAD

**Issue by KostkaBrukowa** [immerjs/immer#714]
## 🐛 Bug Report

Immer does not work correctly with classes that have arrow functions as members (i think).
I took the example from the [Docs](https://immerjs.github.io/immer/docs/complex-objects) with the `Clock`  class and changed one thing, that is I changed the `get time() {...}` to arrow function `time = () => {...}`.
After that change, consecutive calls to function `time` return the same result.
I'm not very experienced, but I observed in debugger, that when the we call the `time` function, there are two scopes `local` and non local. The `local` scope contains the correct reference to `this` i.e. the changed object, but the other scope contains reference to `_this` and the `_this` reference is the first object that was created, and `_this` is used inside the `time` function producing wrong result.

## Link to repro
[CodeSandbox demo](https://codesandbox.io/s/typescript-redux-todoapp-forked-sikhu?file=/src/index.tsx)

## To Reproduce

Just see the console in codesanbox.

## Observed behavior

3 same clock values are observed in the console.

## Expected behavior

As in example in docs i guess there should be 3 different clock values.

## Environment

We only accept bug reports against the latest Immer version.
Checked against immer 8.0.0

- **Immer version:**
- [X] I filed this report against the _latest_ version of Immer
- [X] Occurs with `setUseProxies(true)`
- [X] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by KostkaBrukowa** [comment]
Quick update
I also noticed saw that transpiled code looks like this:
```js
var Clock = /*#__PURE__*/function () {
  function Clock(_hour, _minute) {
    var _this = this;
    var hour = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : true;
    ...
```
Is it possible that immer also copies the `_this` attribute, when producing the new value? Maybe the problem lies there

**Comment by mweststrate** [comment]
That is indeed a limitation of arrow functions, they close over 'this' at
the moment of declaration, rather than invocation, so they won't be
operating on the correct context indeed when your class is drafted.

**Comment by mweststrate** [comment]
Nope it can't, _this is is not an attribute but a variable stored in the
closure.

**Comment by KostkaBrukowa** [comment]
Ok I understand now. And i found the solution to the problem: not using arrow functions in immerable classes.
 Thank you for quick response.
