### ISSUE TITLE
[question] Nested produce calls are not working as expected.

### ISSUE THREAD

**Issue by jaeyoi** [immerjs/immer#716]
## 🙋‍♂ Question

(https://stackoverflow.com/questions/65139558/immer-nested-produce-calls-are-not-working-as-expected)

```
const { produce } = require("immer");

const outer = produce((draft) => {
  return inner(draft);
}, {});

const inner = produce((draft) => {
  draft.arr = [4, 5, 6];
}, {});

outer().arr.sort();
inner().arr.sort();
```

There is an error on ```inner().arr.sort()```. (read-only error)
My expectation is that ```outer().arr.sort()``` also be an error.
Is there something I'm doing wrong here?

## Link to repro

https://codesandbox.io/s/boring-wiles-ezqtr

## Environment

We only accept questions against the latest Immer version.

- **Immer version:** 8.0
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Probably not. Does it lead to any problems?
