### ISSUE TITLE
produce changes the original object

### ISSUE THREAD

**Issue by daniel-seitz** [immerjs/immer#719]
## 🐛 Bug Report

When creating an immutable copy out of a mutable - nested - original, the original is somehow not mutable anymore and results in error messages. I.e. "Cannot add property 4, object is not extensible."

**Please note: I want to modify the original and NOT the copy!**

Code explains it better:

```
        const original = {
            oneA: 'one1',
            oneB: 'one2',
            twoA: ['1', '2', '3', '4'],
            twoB: ['1', '2', '3', '4'],
            threeA: {
                sub1: 'sub1',
                sub2: ['sub2sub1', 'sub2sub2'],
                sub3: {
                    sub3sub1: 'deep',
                },
            },
            threeB: {
                sub1: 'sub1',
                sub2: ['sub2sub1', 'sub2sub2'],
                sub3: {
                    sub3sub1: 'deep',
                },
            },
        };
        console.log('original before:', original);

        const copy = produce(original, (draft) => {
            // these determine whether the original can be modified, ...A can be modified , ...B will result in an error
            draft.twoA = [];
            draft.threeA = {
                sub1: '',
                sub2: [],
                sub3: {
                    sub3sub1: '',
                },
            };
            // special case
            draft.oneA = 'doesnt matter';
        });

        // always works
        original.oneA = 'something else A';
        original.oneB = 'something else B';
        original.twoA = ['something else A'];
        original.twoB = ['something else B'];

        // THESE WORK: draft was changed -> mutating original
        original.twoA.push('6666 A');
        original.threeA.sub1 = '1111 A';
        original.threeA.sub2 = ['another value A'];
        original.threeA.sub3.sub3sub1 = '3333 A';

        // THESE FAIL: draft was not changed -> mutating original
        original.twoB.push('6666 B');
        original.threeB.sub1 = '1111 B';
        original.threeB.sub2 = ['another value B'];
        original.threeB.sub3.sub3sub1 = '3333 B';

        console.log('original after:', original);
        console.log('copy:', copy);
```

**Intention:**
I want to introduce immer into an existing big project and step by step change, what was mutable before to work with immutable copies. Adding the first 'produce' already broke the application since the app still relies mainly on mutability of the original.

**The docs mention** 
"The interesting thing about Immer is that the **baseState will be untouched**, but the nextState will be a new immutable tree"

_Do I misunderstand something here?_

## Expected behavior

Only the copy is immutable, the original should stay as it is.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version: 8.0.0**
- [x] I filed this report against the _latest_ version of Immer
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
This is behaving as intended and changed in version 6, as not freezing all stored data was confusing users as well, and mutating an object after storing it is typically a developer error, after all you are breaking the immutability contract. One could put an object in a further frozen tree, but if that  new object isn't frozen it could (by accident or intentionally) be modified later on, making the tree effectively mutable, not immutable. 

If indeed intend to modify data after putting it in an immutable tree, clone the data you want to store in that tree first. 

Alternatively you can disable autofreeze, but I fear there is little point in using immer and immutability in general, if the objects you are storing are still being mutated by something else. Those concepts work really very differently, so you can not treat a single object as both mutable and immutable. Rather you should work your way down by making some leaves in your state tree immutable, working your way up all the way to the root. Starting at the root won't work for aforementioned reasons.

**Comment by daniel-seitz** [comment]
Hey thanks Michel @mweststrate, maybe I understand produce wrong then.

You are talking about storing the the object (original) and freezing it. Intuitively, I as a consumer on the other hand would think that produce is taking the original and returning an immutable copy - leaving the original alone. Otherwise the 'return' doesnt make much of a difference.

My intention is not to change the immutable later - of course, but rather introducing immer step by step. And this proves to be hard in my case doing it from bottom  to top.

I was not involved in the discussions and dont know if the pros and cons much but from a consumer perspective 

    const immutable = produce(original, () => {})

indicates that immutable is something new and original stays how it is just like any method, i.e.

    const original = ['1', '2'];
    const mapped = original.map(item => item * 2)

leaves the original as is.

On the other hand - if I think of the term 'produce' as something like a ressource for a factory, then yes it makes sense that the resource is not as before after production and there is a product returned. Just one side, since a copy machine could also produce a copy of an original.

Personally I'd prefer to have your lib - which is gaaf by the way - to make a deep copy first, modify the draft, freezing and then returning it. The original is just the blueprint and something completely else.

What do you think?

**Comment by mweststrate** [comment]
doing a full copy and freezing can be done with basic utilities from libs
like lodash. The goal of Immer is to use structural sharing as much
as possible, which is much faster, much cheaper in memory, and allows
optimizations like memoization. If you are looking for a full copy where
nothing is shared, you don't need Immer and a simple: `const draft =
deepCopy(base); /* mutate draft */; deepFreeze(draft); return draft;` will
do.

But if you are sharing data between the begin- and end-state (which is a
great thing to do!) of a producer, we will freeze all involved data by
default to make sure you don't accidentally break the mental model in the
future. If you don't want to share state, because you intend to mutate it
in the future for example, you should clone that part before storing it,
disable autoFreeze altogether (at your own risk), or produce those states
manually rather than using Immer

**Comment by daniel-seitz** [comment]
Thank you @mweststrate, 

I think the misunderstanding comes from the interface where _produce returns something and functions should be pure_.

As I was and am not involved to heavily in the design of this package I don't know the pros and cons of this too well and can just give you my opinion about this.

I am already deep cloning my object but fell over this as - in my opinion - is not intuitive. However, I think this is an edge case and most people would not really find this.

If you will think about it in the future I am open for discussions here, otherwise sure, close this issue.

Thank you for your consideration, have a merry chrismas and - above all - virus-free new year.
Daniel
