### ISSUE TITLE
`draft` is typed as `any` when using `produce()` within React `setState()`

### ISSUE THREAD

**Issue by oscar-b** [immerjs/immer#720]
## 🐛 Bug Report

`draft` is typed as `any` when using `produce()` within React `setState()`, instead of inferring the type. Older versions of `immer` does this properly, but newer one doesn't. As far as I can see, v2.1.5 (and before) works, after that it doesn't.

## Link to repro

Working:
![image](https://user-images.githubusercontent.com/85102/101661880-1be5ca00-3a49-11eb-9e7e-ea8c8b631e2b.png)
https://codesandbox.io/s/adoring-https-rsgqg?file=/src/App.tsx

Not working (only change is version of `immer` to v8.0.0):
![image](https://user-images.githubusercontent.com/85102/101661965-3324b780-3a49-11eb-96e4-c9375b235f23.png)
https://codesandbox.io/s/flamboyant-lehmann-ms3fw?file=/src/App.tsx

## Expected behavior

I expect the `draft` to get a proper type.

## Environment

- **Immer version:** 8.0.0
- Typescript 4.0.3 (in Codesandbox)
- [x] I filed this report against the _latest_ version of Immer
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Might suffer from the same problem as demonstrated in this [playground](https://www.typescriptlang.org/play?#code/DYUwLgBAHgXBBiBXAdgYzASwPbINwCh8oIBeCACgEpSA+CAbwF9DRIBPOK2iANywwAmBfG1IQAZinTZkXJoQD0CiAKwgAzsgDkkAO5YATgGtOGZOJAGQaEBABGVgIZH1lfEolTMOCLoOOABwAeABUIECgwawF1BC8ZGnJxZDgQylSGRWV9Y3UAGntESEcIYAwwMFAIMCxfQVtyR1RUEACwWOQfSTRvZFjHWN0QYGB092Vu6R8-QNDE5NT0iDD6LN9DFwKAK0R1SBR1RCtfAAtRGDdJ3t9-YLCIqOQYuJ6ZCAAfCBQBEHEzEAEHwgyEQI3mKWWSxW+AgsIgVjAR2QEjw+GY+FQOD21Q0YAATHBVrDHAB+TiwYGIAC2dks1BIdD4ggIjDERIgHnUJywoMBZgsBmqJ0ckGIGFiWHE1TYAVsIJplhhEEccBmAXI5Cg9LomL6WFAADpgFgAOaag01eAYKAAqiUNywjyARMIIAAiAAKjn8VPAlggWigWggGCpATKqHKwFEwv6yK0jmQbCDYBlIAN1XU5AA7AAGHMANkorvCBgMhmDyLAJ3FpX+aOEavIAGZqJzubzgVhis1WpAm0A), meaning we could possibly apply the same solution. See also: https://github.com/mobxjs/mobx/pull/2740

**Comment by iChenLei** [comment]
### typedef change
Before v2.1.5 https://github.com/immerjs/immer/blob/v2.1.5/src/immer.d.ts#L71-L107
After v2.1.5 https://github.com/immerjs/immer/blob/v2.2.0/src/immer.d.ts#L72-L107
In your case, you match the `Curried producer `
### > v2.1.5
```ts
	<
		Recipe extends (...args: any[]) => any,
		Params extends any[] = Parameters<Recipe>,
		T = Params[0]
	>(
		recipe: Recipe
	): <Base extends Immutable<T>>(
		base: Base,
		...rest: Tail<Params>
	) => Produced<Base, ReturnType<Recipe>>
```	
recipe => Recipe => `Recipe extends (...args: any[]) => any`

### <= v2.1.5
```ts
    /** Curried producer with no default value */
    <T = any, Rest extends any[] = [], Return = void>(
        recipe: (this: Draft<T>, draft: Draft<T>, ...rest: Rest) => Return
    ): (base: Immutable<T>, ...rest: Rest) => Produced<T, Return>
```
recipe => `(this: Draft<T>, draft: Draft<T>, ...rest: Rest) => Return`

@mweststrate Sir, Maybe this is why current version `immer` can't infer type correctly. I think it's not same with the mobx case.

### append
- The `useState` typedef
```js
  function useState<S>(initialState: S | (() => S)): [S, Dispatch<SetStateAction<S>>];
  type Dispatch<A> = (value: A) => void;
  type SetStateAction<S> = S | ((prevState: S) => S);
```
