### ISSUE TITLE
When I use produce in reudcer state can be changed use getstate().

### ISSUE THREAD

**Issue by 787941287** [immerjs/immer#725]
## 🙋‍♂ Question

Is there any way to make the data obtained by getstate() is immutable？

## Link to repro

Please provide a [CodeSandbox demo](https://codesandbox.io/s/immer-sandbox-6wijw) to clarify your question if possible. Typically, questions without minimal codesandbox demo won't be answered.

## Environment

We only accept questions against the latest Immer version.

- **Immer version:**
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by 787941287** [comment]
such as :getstate().main.a='anychange'

**Comment by mweststrate** [comment]
Closing for the lack of an example and I have no idea what `getstate()` is.
