### ISSUE TITLE
Export WritableDraft type and optionally make it compatible with ts-essentials

### ISSUE THREAD

**Issue by gyzerok** [immerjs/immer#726]
## 🚀 Feature Proposal

It seems that while `WritableDraft` is an "exposed" type meaning that it can be seen on the consumer side, however it is private. I think it would make sense to export it.

## Motivation

I have the following domain model module

```ts
export type Foo = {
  readonly prop: string
}

// Now I want to make a function operating on foo which "mutates" it and make sure that it is being used only inside produce
export function changeIt(foo: WritableDraft<Foo>): void {
  foo.prop = 'Hello, world!'
}
```
But I can't achieve this, because I can't import `WritableDraft` type. And I think being able to define things this way would provide more type safety, because nobody will be able to accidentaly mutate something outside of `produce`.

## Can this be solved in user-land code?

It could be done with `DeepWritable` from `ts-essentials` however it's weird that there is a need for external package when the type itself exists in `immer`. Also it is "visible" through draft.

## Full example

```ts
// Foo.ts

export type Foo = {
  readonly prop: string
}

export function changeIt(foo: WritableDraft<Foo>): void {
  foo.prop = 'Hello, world!'
}
```
```ts
// reducer.ts
import * as Foo from 'Foo.ts'


type State = {
  readonly foo: Foo
}

return function reducer(state: State, action: Irrelevant): State {
  return produce(state, (draft) => {
    Foo.changeIt(draft)
  })
}
```

## Additional note

Also I've been using [`DeepReadonly` type from `ts-essentials`](https://github.com/krzkaczor/ts-essentials#Deep-wrapper-types) package and it seems that `WritableDraft` does not convert everything writable. For me it failed with nested objects. It would be great if these 2 were compatible.

I think just copying `DeepWritable` implementation from `ts-essentials` would make it just as good and compatible without any regressions.

**Comment by gyzerok** [comment]
I discovered `Draft` type which seems to do what I want. I am wondering though why TypeScript shows me `WritableDraft` as draft type and not `Draft`.

**Comment by JosXa** [comment]
> I am wondering though why TypeScript shows me `WritableDraft` as draft type and not `Draft`

In 2024, I still wonder about it.

**Comment by leoleitedev** [comment]
@JosXa, this comment https://github.com/immerjs/immer/issues/726#issuecomment-752876708 helped me solve it. Did you try that?

**Comment by JosXa** [comment]
@leoleitedev I actually resorted to the `yarn patch` command to sneakily change the type declaration to become exported 😀

**Comment by Harsh-Sharma25** [comment]
@gyzerok 
Is this how you meant it ? 

`import type { Draft } from 'immer';`
