### ISSUE TITLE
Query regarding freezing ?

### ISSUE THREAD

**Issue by suyashdeshpande** [immerjs/immer#732]
## 🙋‍♂ Question

Let's say, we have 10k records which we freeze with immer. Now we produce a draft state and mutate a single object in it and again try to freeze it. Will immer freeze only a single mutated object or it will go over all 10k objects?

**Comment by suyashdeshpande** [comment]
@mweststrate Can you help ?

**Comment by mweststrate** [comment]
> @mweststrate Can you help ?

Don't be rude by pinging maintainers. Especially not hours after you posted the original question and in a weekend. 

> Will immer freeze only a single mutated object or it will go over all 10k objects?

As documented Immer structurally shares non-modified elements, so, no.
