### ISSUE TITLE
How to update private attributes?

### ISSUE THREAD

**Issue by calebho** [immerjs/immer#733]
## 🙋‍♂ Question

Is it possible to update `private` attributes in the recipe function? A workaround could be to make the attribute `public`, but I don't want to break encapsulation if possible.

## Link to repro

https://codesandbox.io/s/immer-sandbox-forked-klxqf?file=/src/index.ts

## Environment

- 5.3.2

**Comment by mweststrate** [comment]
Immer will do its job fine at runtime, it's just typescript that won't
allow this, so, you'll be needed a TS specific work around indeed, making
it non private, or casting it to some utility interface / any

**Comment by calebho** [comment]
Makes sense; thanks @mweststrate!
