### ISSUE TITLE
Cannot perform 'get' on a proxy that has been revoked

### ISSUE THREAD

**Issue by hamed-musallam** [immerjs/immer#742]
I face this when I move the produce function at the level of the reducer instead of call produce function every time inside actions
![image](https://user-images.githubusercontent.com/35760236/105861188-bc3e8080-5fee-11eb-87ef-f515951eae83.png)
![image](https://user-images.githubusercontent.com/35760236/105861232-c95b6f80-5fee-11eb-878f-7cb5460725a4.png)

![image](https://user-images.githubusercontent.com/35760236/105860809-45a18300-5fee-11eb-9d0e-53544e09e6a3.png)

**Comment by mweststrate** [comment]
Please file again but follow the issue template.
