### ISSUE TITLE
when `enablePatches()`, passing two function to `produce` can also return a curried `produce`

### ISSUE THREAD

**Issue by littlee** [immerjs/immer#743]
## 🚀 Feature Proposal

when `enablePatches()`, passing two function to `produce` can also return a curried `produce`

## Motivation

get a curried `produce` without using `produceWithPatches`, callback is more suitable in situation when used with react setState

## Can this be solved in user-land code?

I don't think so

## Example

```js
import produce, { enablePatches } from 'immer';
enablePatches();

var patches = []
const produceFn = produce((draft) => {
  draft.a = 1;
}, (patch, inversePatch) => {
  patches.push({ patch, inversePatch });
})

var baseState = {};
var nextState = produce(baseState);
```

**Comment by mweststrate** [comment]
This would affect the global working of Immer. I suggest to create your won currying utility instead, something on along the lines:

```
function curriedProduceWithPatches(recipe, patchHandler) {
   return function(base) {
      const [res, patch, inversePatch] = produceWithPatch(base, recipe)
      patchHandler(patch, inversePatch)
      return res
   }
}

const produceFn = curriedProduceWithPatches((draft) => {
  draft.a = 1;
}, (patch, inversePatch) => {
  patches.push({ patch, inversePatch });
})
```

Note that `setState` updaters are supposed to be side effect free, so this might lead to unexpected results, like the patch handler being called twice in development mode
