### ISSUE TITLE
Flow errors when passing a $ReadOnlyArray as state to produce

### ISSUE THREAD

**Issue by nathantalewis** [immerjs/immer#744]
## 🐛 Bug Report

The flow typing seems to only allow and `Array` to be passed as state to `produce` and throws and error when `$ReadOnlyArray` is passed.

## Link to repro

This issue can be reproduced as seen in this commit: https://github.com/nathantalewis/immer/commit/c00e900e18c222490f48851ed4ccfcb019cff154

## To Reproduce

Try to pass a `$ReadOnlyArray` as state to the `produce` function.

## Observed behavior

Flow throws an error that a `$ReadOnlyArray` isn't compatible with `Array`.

## Expected behavior

The `produce` function should be able to receive a `$ReadOnlyArray` or a regular `Array` without type errors.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [X] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
We don't actively maintain the flow types, but feel free to submit a PR
with a fix if interested.

**Comment by nathantalewis** [comment]
I was mostly just submitting to raise awareness. In the codebase that uses Immer with Flow that I'm dealing with, it's not important enough to fix so we've just added suppression comments. I'll close this issue and someone else can re-open it with a PR to fix it if they have the time.
