### ISSUE TITLE
Use immer with lodash `set` and `merge`

### ISSUE THREAD

**Issue by nkint** [immerjs/immer#747]
## 🙋‍♂

Hi! I'm asking a question here. Sorry in advance if this is not the right place where to ask but looking at the docs/past issues I haven’t found a good solution.

I'm using lodash `set` and `merge` to mutate the draft provided by immer in a React/Redux state but it doesn't seems to work (missing re-render).

## `<>`

```js
import produce from "immer"
import { set } from "lodash"

const baseState = {
    1: {
        todo: "Learn typescript",
        done: true
    },
}

const nextState = produce(baseState, draftState => {

    draftState[0] = {todo: "foo"}
    // OK, new is created
    
    draftState[23].done = true 
    // TypeError: Cannot set property 'done' of undefined
    
    set(draftState, [23, "done"], true)
    // works but missing re-renders  as if I mutate the state inside a reducer

})
```

I think it has something to deal with Proxy and how lodash does mutations.
Can someone point me to a documentation piece that explains why this happens and how to solve this in a clean way?
`Object.assign` does not suffer from this because of the polyfill mentioned in #248 right?
I would avoid to use external packages as suggested in #303 .

**Comment by mweststrate** [comment]
Please provide a sandbox reproduction if you want anybody to look into it.
It's hard to reason about the symptom 'not rendering' if there is no redux
or react in your question.

**Comment by franky-chanyau** [comment]
Not sure if you managed to solve this but lodash object mutations like `set` and `merge` should trigger re-renders in react if you use [Curried Producers](https://immerjs.github.io/immer/docs/curried-produce) to modify your state. Try something like the snippet below and see if it works. I'm using [Zustand](https://immerjs.github.io/immer/docs/curried-produce) with immer for my state logic so it might be a Redux + Immer thing. Hope it helps though!

```js
...
const nextState = produce(baseState => {
    set(baseState, [23, "done"], true)
})
 ```

This might not work for your use case but these utility functions I use are really handy for quick mutations (like updating a state property when an input value changes) where your producer logic doesn't require complex logic. Look at the immer docs for [inline shortcuts](https://immerjs.github.io/immer/docs/return#inline-shortcuts-using-void) using the `void` operator for what inspired me.

```js
...
// Merging is useful for resetting state or bulk updating state changes
const set = updates => produce( state => void ( typeof updates === 'object' && _.merge(state, updates) ) )
const nextState = set( { 0: { todo: "foo" } } )

// Quickly update a deep nested property's value
const apply = (path, value, updateExistingOnly = false) => produce( state => void ( (_.has(state, path) || !updateExistingOnly) && _.set(state, path, value) ) )
const nextState = apply([23, "done"], true)
const nextState = apply([0, "done"], false, true)
```

Hope this helps. Happy hacking!

**Comment by nkint** [comment]
sorry for the lag in the answer,
thanks @franky-chanyau , it was helpful!
