### ISSUE TITLE
Deno Compatibility

### ISSUE THREAD

**Issue by allangomessl** [immerjs/immer#748]
## 🚀 Feature Proposal

Deno Compatibility

## Motivation

I believe that's simple migrate for deno, a lot of js libs already adopting Node and Deno today.

**Comment by mweststrate** [comment]
I'm not familiar with deno. What does that mean? Feel free to open a PR.

**Comment by Soremwar** [comment]
@mweststrate Deno is a NodeJS alternative https://deno.land/

@allangomessl Thanks to the effort of services like Skypack and ESM.SH we already have access to lots of NPM packages, and immer is one of them!

I just tried this example directly from the immer docs using Skypack as a provider

```ts
import produce, {enableMapSet} from "https://cdn.skypack.dev/immer@8.0.1?dts"
enableMapSet()

const usersById_v1 = new Map([
  ["michel", {name: "Michel Weststrate", country: "NL"}]
])

const usersById_v2 = produce(usersById_v1, draft => {
  const item = draft.get("michel")
  if(item){
    item.country = "UK"
  }
})

console.log(usersById_v1.get("michel")?.country) //NL
console.log(usersById_v2.get("michel")?.country) //UK
```

**Comment by mweststrate** [comment]
So this issue can be closed?

**Comment by allangomessl** [comment]
Thanks!!
