### ISSUE TITLE
`immer.produce` has different typings than `produce`

### ISSUE THREAD

**Issue by ianstormtaylor** [immerjs/immer#749]
## 🐛 Bug Report

If you instantiate your own `new Immer()` instance to keep settings changes local, the `immer.produce` method doesn't have the same typing information as the top-level `produce` export.

## Link to repro

https://codesandbox.io/s/new-mountain-fq0uw?file=/src/index.ts

```ts
import { produce, Immer } from "immer";

const immer = new Immer();
const obj = { a: 1 };

produce(obj, (o) => o);
immer.produce(obj, (o) => o);
                 // ^ Parameter 'o' implicitly has an 'any' type.
```

With `produce` the types are as expected. But with `immer.produce` the draft that gets passed to the callback is of type `any` instead of `Draft`.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [x] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by iChenLei** [comment]
## immer package entry
```ts
export const produce: IProduce = immer.produce

export {Immer}
```
You can noticed that standalone `produce` function use `IProduce` typedef, and the Immer instance use raw ts source code typedef.
```ts
export class Immer implements ProducersFns {
        /** ommit **/
	produce(base: any, recipe?: any, patchListener?: any) {
```
So it's infer `any` type in your case. @mweststrate Sir,  Is there any way to declare type correctly?
```ts
interface ProducersFns {
	produce: IProduce
	produceWithPatches: IProduceWithPatches
}
```
I noticed that even we `implements ProducersFns`, but it's not work as expected when user use `new Immer()` instance.
