### ISSUE TITLE
Slow sub performance

### ISSUE THREAD

**Issue by jcampbell05** [immerjs/immer#751]
This benchmark is given a result of sub 10K operations a second when immutable JS is hitting around 400K and vanilla JS 700K.

Is there any ideas why this might be the case ? 

https://measurethat.net/Benchmarks/Show/11547/0/immer-setautofreezefalse-vs-shallow-vs-ramda-lens-vs-im

This was tested in the browser and whilst I understand the argument about synthetic benchmarks not being representative we are worried about this having an impact on our app if we switched since we have a lot of small updates like this (i.e keeping track of user intereactions)

**Comment by mweststrate** [comment]
You will get slightly better results if the data is pre-frozen (immer itself wil freeze output by default, so IRL that isn't needed).

Beyond that I think indeed these syntactic benchmarks are not super relevant indeed, I have yet to see the app where the time to _update_ the state is a bottleneck. Usually the bottlenecks is in updating the UI, which is typically order of magnitude more expensive, and it is the structural sharing concept that helps with that regardless which library you pick (and also the reason the mutate example is useless as reference point, in practice that will be by far the slowest of the solutions in that list). 

If you actually hit a perf bottleneck, do check https://immerjs.github.io/immer/docs/performance#performance-tips, or simple opt-out of using immer for certain super critical operations. You can perfectly mix and max immer with manual shallow copies or ramda at any point. (but not with ImmutableJS)
