### ISSUE TITLE
Internet Explorer 11 Support with immer as a nested dependency

### ISSUE THREAD

**Issue by computebender** [immerjs/immer#752]
Hello,
I am using a library called [React Flow](https://reactflow.dev/) to create interactive flow charts. React Flow has easy-peasy as a dependency, which in turn has immer as a dependency. I am currently struggling to find a way to enable ES5 support with the instance of immer easy-peasy uses. 

I have a sample project that demonstrates where I am currently stuck [https://github.com/computebender/flow-ie-support](https://github.com/computebender/flow-ie-support) 
As well as a [codesandbox](https://codesandbox.io/s/friendly-antonelli-bxhii) (although that doesn't really help with IE support)

The current issue I am facing is an error thrown only in IE (not Chrome or Firefox) because of immer: 
`SCRIPT5022: [Immer] Cannot use proxies if Proxy, Proxy.revocable or Reflect are not available`

From here I have found two potential paths to follow,

1. Try to polyfill for Proxy using Google's [proxy-polyfill](https://github.com/GoogleChrome/proxy-polyfill)
2. Enable es5 support in immer by running [enableES5](https://immerjs.github.io/immer/docs/installation)

**1 - Polyfill**
From what I have read, Proxy cannot be fully implemented using polyfills. From babeljs.io:

> Due to the limitations of ES5, Proxies cannot be transpiled or polyfilled. See support in [various JavaScript engines.](https://kangax.github.io/compat-table/es6/#test-Proxy)

Although I have seen posts suggesting to use the Chrome teams [proxy-polyfill](https://github.com/GoogleChrome/proxy-polyfill).
I have tried both just importing proxy-polyfill in the index.js entrypoint of my app,
```js
import 'proxy-polyfill';
```
and importing the proxy.min.js file directly,
```js
import 'proxy-polyfill/proxy.min.js';
```
Neither of these had an impact, and the error in IE remained.

**2 - enableES5()**
From what I've read, it should be very easy to enable es5 support for immer, which would remove the Proxy dependency. So to do this I added immer 7.0.9 (the same version specified in easy-peasy's package.js) as a direct dependency of my project. (Note `npm ls immer` was run on Ubuntu, as that's where I'm writing this, but testing is being done on Windows obviously)
```
flow-ie-support@0.1.0 /home/ben/Projects/flow-ie-support
├── immer@7.0.9 
├─┬ react-flow-renderer@8.8.0
│ └─┬ easy-peasy@4.0.1
│   └── immer@7.0.9  deduped
└─┬ react-scripts@4.0.2
  └─┬ react-dev-utils@11.0.2
    └── immer@7.0.9  deduped
```
I then added:
```js
import { enableES5 } from 'immer';
enableES5()
```
to my index.js entrypoint. This also had no impact on the same Proxy error showing up in internet explorer. I'm just wondering if anyone has any suggestions to proceed.

**Comment by mweststrate** [comment]
I think this issue should be filed at easy-peasy. They can expose the entry
point for enabling ES5 support if they themselves support it.

Op za 13 feb. 2021 16:23 schreef Benjamin Munro <notifications@github.com>:

**Comment by computebender** [comment]
@mweststrate Thanks for the quick reply. I have posted an issue there as well, as I wasn't really sure where my issue stems from. From your perspective would you know why running enableES5 doesn't work to change the instance of immer easy-peasy uses? (Mainly out of curiosity) I've seen quite [a few posts](https://github.com/ctrlplusb/easy-peasy/issues/406) saying that should solve their issue. Thanks for the guidance anyways though :)

**Comment by mweststrate** [comment]
Afaik theoretically it shouldn't work, as EP should get it's own isolated
immer module since it is a direct dep. In practice it might work due to
deduping. Not sure. I wouldn't rely on it at least and ask EP to expose an
API to explicitly configure it, or enable it by default at the cost of a
larger bundle by default.
