### ISSUE TITLE
Shouldn't draft reassignment be forbidden or maybe treated as a usual mutation/replacement?

### ISSUE THREAD

**Issue by smileart** [immerjs/immer#756]
## 🙋‍♂ Question

Currently the following is totally legit and neither throws an error nor produces any useful result (which is and surely should be totally O.K. from JS/TSs point of view):

```js
import produce from "immer"

const baseState = []

const staticData = [
    {
        todo: "Learn typescript",
        done: true
    },
    {
        todo: "Try immer",
        done: false
    }
]

const nextState = produce(baseState, draftState => {
    draftState = staticData
    draftState[1].done = true
})
```

But still, in this way we reference the external const which totally replaces the `draftState` producing an empty result (`nextState`) and even mutating the external object by reference. The question is: shouldn't Immer intercept and treat the assignment as a total state mutation/replacement with the **clone** of the value on the right side? 

Or perhaps, throw an exception telling a clueless developer that they actually replace the `draft` with their value and in that way totally loose the reference to the original `draftState`, plus any changes of the "new" `draftState` would cause mutations of the assigned object by reference?

If both are not planned: is there (or should there be) a warning/explanation in the documentation explaining that only mutations on `draft` are allowed, but assignment is meaningless/forbidden/dangerous?

## Link to repro

Here's a link to [CodeSandbox demo](https://codesandbox.io/s/intelligent-sea-ws4m7?fontsize=14&hidenavigation=1&theme=dark&file=/src/index.js) to clarify my question. Additionally notice the utterly confusing console.log(s) produced when the data assigned in place of the draft being mutated and only the final value ever gets logged.

## Environment

Any environment and the latest Immer version (`v8.0.1`)

**Comment by mweststrate** [comment]
It's literally the first in the pitfall list :) https://immerjs.github.io/immer/docs/pitfalls#dont-reassign-the-recipe-argument. Beyond that reassigning a local variable is completely undetectable at runtime, if we could, we would!

**Comment by smileart** [comment]
@mvrststrate thanks for such a quick answer.

In my particular real case I was using Immer as a plugin for [rematch](https://rematchjs.org/docs/plugins/immer/) so it was not entirely clear that by working with `state` I was actually modifying/reassigning the draft. Despite my question being answered I would suggest project maintainers to consider adding those pitfalls directly to the relevant documentation pages as clear warning blocks, cause the current place of the _Pitfalls_ section hardly could be easily discovered by someone looking for a solution for their problem or be used as a guidance to avoid one. Probably something [like this](https://stackoverflow.com/questions/58737436/how-to-create-a-good-looking-notification-or-warning-box-in-github-flavoured-mar) could be used to create those blocks (leaving Pitfalls where they are, but duplicating the info closer to the relevant samples and documentation pages).

Let me know if this sort of change would be welcome and I'd gladly contribute this changes myself to help others avoid these trivial, but real issues in the future.
