### ISSUE TITLE
enableES5 failed on iOS 9 / react-native

### ISSUE THREAD

**Issue by HugoGresse** [immerjs/immer#759]
## 🙋‍♂ Question

I'm trying to fix es5 issue on iOS 9 (react-native). Which is not easy because I don't have any device or emulator on iOS 9 and apple removed the iOS 9 emulator on macOS... 
I've enable es5 on all build and from what I've coded it should run before all reducer initialization, but still getting the error.

The error as repported by crashlytics is : 
```
Fatal Exception: RCTFatalException: Unhandled JS Exception: Error: [Immer] minified error nr: 18 'ES5'. Find the full error at: https://bit.ly/3cXEKWf
Unhandled JS Exception: Error: [Immer] minified error nr: 18 'ES5'. Find the full error at: https://bit.ly/3cXEKWf, stack: t@428:131 A@428:1740 C@428:3405 produce@428:14094 <unknown>@(null):(null) <unknown>@428:13930 <unknown>@411:893 forEach@(null):(null) s@411:856 combineReducers@411:3734 <unknown>@603:273 v@2:1473 d@2:945 o@2:413 <unknown>@446:236 v@2:1473 d@2:945 o@2:413 <unknown>@427:183 v@2:1473 d@2:945 o@2:413 <unknown>@6:80 v@2:1473 d@2:875 o@2:413 global code@1618:3
```

Here is : 
index.js: 
```
import { ActivityIndicator, AppRegistry } from 'react-native'
import { Provider } from 'react-redux'
import React from 'react'
import configureStore from './src/redux/store'
import { PersistGate } from 'redux-persist/es/integration/react'
import App from './src/App'

const { persistor, store } = configureStore()

const AppRedux = () => (
    <Provider store={store}>
        <PersistGate loading={<ActivityIndicator />} persistor={persistor}>
            <App />
        </PersistGate>
    </Provider>
)

AppRegistry.registerComponent('PlantNet', () => AppRedux)
```

and configureStore: 
```
import { enableES5 } from 'immer'
enableES5() // Prevent issue on iOS 9 before importing reducers (where immer is used)

import { createStore, compose, applyMiddleware } from 'redux'
import { persistStore, persistCombineReducers } from 'redux-persist'
import thunk from 'redux-thunk'
import AsyncStorage from '@react-native-community/async-storage'
import { persistReducer } from '../persistReducer'

const config = {
    key: 'root',
    storage: AsyncStorage,
    blacklist: ['volatile'],
}
const middleware = [thunk]

const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose
const reducers = persistCombineReducers(config, persistReducer)
const enhancers = [applyMiddleware(...middleware)]
const persistConfig = { enhancers }
const store = createStore(reducers, undefined, composeEnhancers(...enhancers))
export const persistor = persistStore(store, persistConfig, () => {})

const configureStore = () => {
    return { persistor, store }
}

export default configureStore
```

## Link to repro

iOS 9, [PlantNet app](http://apple.co/2cMtWgu)

## Environment

We only accept questions against the latest Immer version.

- **Immer version:** 7.0.15
- [ ] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)
- React-native 0.63.4

**Comment by mweststrate** [comment]
This means that either your configuration runs too late still, or one of
your libraries is using it's own copy of Immer that isn't configured to use
ES5 (probably the stack trace should reveal that). Without a minimal repro
we can't provide any help beyond that. Note that your immer version is a
major behind as well.

**Comment by HugoGresse** [comment]
Thanks for the quick answer. Then I'll try to update to immer 8 :/ 
I've pasted the files from the app in the original question, I don't see how it should be done higher up. 
Running `npm ls` did not reveal any more immerjs usage

**Comment by mweststrate** [comment]
There is a lot of subtility in module loading order in JS, and it is not as predicatable as it looks like. I'd follow your stacktrace and make sure `enableES5` is called literally the line before one of the calls in the stacktrace

**Comment by HugoGresse** [comment]
I've updated to immer 8.01, moved the es5 to the top of the index.js file, still crashing the same way: 

```
import { enableES5 } from 'immer'
enableES5() // Prevent issue on iOS 9 before importing reducers (where immer is used)

import { ActivityIndicator, AppRegistry } from 'react-native'
import { Provider } from 'react-redux'
import React from 'react'
import configureStore from './src/redux/store'
import { PersistGate } from 'redux-persist/es/integration/react'
import App from './src/App'

const { persistor, store } = configureStore()

const AppRedux = () => (
    <Provider store={store}>
        <PersistGate loading={<ActivityIndicator />} persistor={persistor}>
            <App />
        </PersistGate>
    </Provider>
)

AppRegistry.registerComponent('PlantNet', () => AppRedux)
```

How can I help providing a reproduction for iOS 9?

**Comment by mweststrate** [comment]
Grab the stack trace of the crash, find the call to `produce` in there, and in that module, there is probably some top level initialization code. Make sure to call enableES5() there as well, just before running the initialization code.

**Comment by HugoGresse** [comment]
The stack trace is too much obfuscated to be helpful :/ 

```
Fatal Exception: RCTFatalException: Unhandled JS Exception: Error: [Immer] minified error nr: 18 'ES5'. Find the full error at: https://bit.ly/3cXEKWf
Unhandled JS Exception: Error: [Immer] minified error nr: 18 'ES5'. Find the full error at: https://bit.ly/3cXEKWf, 
stack: 
t@428:131 A@428:1740 C@428:3405 
produce@428:14094 
<unknown>@(null):(null) 
<unknown>@428:13930 
<unknown>@411:893 
forEach@(null):(null) 
s@411:856 
combineReducers@411:3734
 <unknown>@603:273 
 v@2:1473 
 d@2:945 
 o@2:413 
 <unknown>@446:236 
 v@2:1473 
 d@2:945 
 o@2:413 
 <unknown>@427:183 
 v@2:1473 
 d@2:945 
 o@2:413
  <unknown>@6:80 
  v@2:1473 
  d@2:875 
  o@2:413 
  global 
  code@1618:3
  ```
  
  I'm closing this, I'm getting rid for iOS 9 compatibility as I don't have any solution. 
  Thanks for trying to help!

**Comment by mweststrate** [comment]
Not much experience with RN, but it might help to use named functions?

**Comment by HugoGresse** [comment]
surely, I'm trying my best but the codebase is very big and is king of a mess for most parts :/ 
Did not help having 3600 ligne components 😂
Thanks anyway, immer is lightweight, easy to use and great, so much better than Immutable js
