### ISSUE TITLE
useImmerReducer  and axios call

### ISSUE THREAD

**Issue by mvlach** [immerjs/immer#760]
Hi all,

I would like to ask you to help with the useImmer reducer. I have a method called in immerReducer. The problem is that thanks to the asynchronicity the draft is not valid. 

TypeError: Cannot perform 'set' on a proxy that has been revoked

```
export const createDistribution = (
  draft: Draft<ExpeditionDetailView>,
  customerId: number,
  applicationId: string,
  distribution: DistributionView,
) => {
  const { createDistributionForExpedition, getDetailExpeditionV3 } = useContext(ApiContext);

  createDistributionForExpedition(customerId, applicationId, mapToDistributionInDTO(distribution), () => {
    getDetailExpeditionV3(customerId, applicationId, (data) => {
      draft.expeditionStatus = data.expeditionStatus;
    });
  });
};```

How to solve it? 

Many thanks, Mila

**Comment by mweststrate** [comment]
See https://immerjs.github.io/immer/docs/async. The model behind your function is incorrect from immutability perspective. If you want to change state _over time_ you can cannot hold on to a reference to a state from a _specific_ point in time, and mutate it. Even if that would be allowed, you'd overwrite any other change that might have happened in the mean time. Instead, when your request completes, you should find back your expedition details (from wherever you keep your state) and issue an update that is to be executed here and now to store the changes back.

**Comment by mweststrate** [comment]
Closing since question was answered
