### ISSUE TITLE
Is it a bad idea to work in an immutable manner inside of produce()?

### ISSUE THREAD

**Issue by msageryd** [immerjs/immer#761]
I'm preparing to migrate from Immutable.js to Immer. I don't like the proprietary format of Immutable, but I really like the rich collection functions. I'm often using .filter() on maps, for example.

I will either write my own collection helpers or use something like collect.js. Most functions in Collect.js returns a new object or array instead of mutating the input.

[https://github.com/ecrmnn/collect.js](https://github.com/ecrmnn/collect.js)

Question:
I realise that working in an immutable manner inside of produce() is not needed. It might even be a bad idea?
- would it hurt performance?
- would it even mess with the proxy stuff in Immer?

**Comment by mweststrate** [comment]
1) potentially (probably). But probably not in such a significant way that it matters. 2) probably not unless you do weird reflection stuff. 

But if you work immutably inside `produce`, you don't need `produce` in the first place, and just only use it on the places where you actually use mutation. But mixing and matching should generally be fine, although it might be a bit confusing to read. Just make sure you never reassign the `draft` argument (`draft = ....`).
