### ISSUE TITLE
Fully support DeepReadonly

### ISSUE THREAD

**Issue by iquadrat** [immerjs/immer#764]
## 🚀 Feature Proposal

Support DeepReadonly type from utility-types package in immer. Currently, when using DeepReadonly for the state there is a problem with nested array.

## Motivation

The type of react state should be deeply readonly to prevent selectors etc to modify it accidentally. For this, the type DeepReadonly would be handy, you can just wrap the top-level state definition by it to ensure a deep readonly type.

Hover, this approach currently does not work with immer due to _DeepReadonlyArray type not being converted to a writable type through produce.

This short code snippet demonstrates the problem:
```ts
import {produce } from "immer";
import {DeepReadonly} from "utility-types";

export type Foo = {
  readonly strings: string[],
}

export type Wrapped = DeepReadonly<Foo>;

export function reduce(f: Wrapped) {
  return produce(f, (draft) => {
    draft.strings.push("x"); // error: TS2339: Property 'push' does not exist on type 'WritableDraft_DeepReadonlyArray >'
  })
}
```

It seems this could be solved by adding this line to the Draft declaration:
`T extends ReadonlyArray<DeepReadonly<infer V>> ? Array<Draft<V>>`

such that it becomes:
```ts
export type Draft<T> =
  T extends ReadonlyArray<DeepReadonly<infer V>> ? Array<Draft<V>> :
    T extends AtomicObject
      ? T
      : T extends IfAvailable<ReadonlyMap<infer K, infer V>> // Map extends ReadonlyMap
      ? Map<Draft<K>, Draft<V>>
      : T extends IfAvailable<ReadonlySet<infer V>> // Set extends ReadonlySet
        ? Set<Draft<V>>
        : T extends WeakReferences
          ? T
          : T extends object
            ? WritableDraft<T>
            : T;
```

## Can this be solved in user-land code?

I do not see how. Only by replacing all types.

## Example

See above.

**Comment by mweststrate** [comment]
Note that Immer ships with its own Draft and Immutable utility types that
probably do a similar thing
