### ISSUE TITLE
Docs - Navigating directly to sections of the docs website breaks certain links

### ISSUE THREAD

**Issue by Shrugsy** [immerjs/immer#779]
## 🐛 Bug Report

Navigating directly to sections of the docs website appends a trailing slash and breaks 'sibling' links

## Link to repro
Applies to any section of the site with 'sibling links'. E.g. when a link should go from `immer/api` to `immer/produce`
https://immerjs.github.io/immer/api

## To Reproduce

- Go directly to https://immerjs.github.io/immer/api
- Observe that a trailing slash is appended (https://immerjs.github.io/immer/api/)
- In the `Section` column, hover over any links and observe that they have an extra `api` section in the URL (e.g. https://immerjs.github.io/immer/api/produce instead of https://immerjs.github.io/immer/produce)
- Try clicking any of the `Section` links, and observe that a 'Page Not Found' page will be encountered

Note: When accessing a section through the sidebar, no trailing slash is appended, and the links work as expected.

## Observed behavior

The links on a page become invalid when a section of the site is accessed directly.

## Expected behavior

- The links should work even when going to a page directly before clicking the links.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [X] I filed this report against the _latest_ version of Immer
- [X] Occurs with `setUseProxies(true)`
- [X] Occurs with `setUseProxies(false)` (ES5 only)

(Note: Environment is N/A, this is regarding the website only)

**Comment by Shrugsy** [comment]
Possibly related issues on `docusaurus`:  

- https://github.com/facebook/docusaurus/issues/2394
- https://github.com/facebook/docusaurus/issues/4419

**Comment by mweststrate** [comment]
Thanks for reporting! Should be fixed now
