### ISSUE TITLE
Which is the immer version for Angular 6.1.0 with TypeScript 2.7.2.  Upgrade is not possible. 

### ISSUE THREAD

**Issue by vegeta03** [immerjs/immer#780]
## 🙋‍♂ Question

The current project uses Angular 6.1.0 with TypeScript 2.7.2 and an upgrade is not possible. There is a serious requirement for the functionality provided by immer.

Could anyone provide the compatible immer version for this issue?

## Environment

Angular 6.1.0
TypeScript 2.7.2  

Thank you.

**Comment by mweststrate** [comment]
Just try older majors until you have one that works for you?

**Comment by mweststrate** [comment]
Looks like the newest version that support TypeScript 2 is https://github.com/immerjs/immer/blob/1.0.3/package.json. That is fairly old and I'd strongly recommend against using. Obviously we won't provide any support on it. I recommend to instead use the latest version and ignore the typings:

```
const produce = require("immer")

// or maybe:
// @ts-ignore
import { produce} from "immer"
```

**Comment by vegeta03** [comment]
Hi @mweststrate ,

How can I ignore the typings, what to do about that?

**Comment by vegeta03** [comment]
Hi @mweststrate ,

How can I ignore the typings for this specific lib in typescript 2.7.2

Thank you.

**Comment by mweststrate** [comment]
```
const produce = require("immer")
```
