### ISSUE TITLE
Subclasses of 'Map' are returned as the base 'Map' class when produce is run

### ISSUE THREAD

**Issue by mattsoulanille** [immerjs/immer#781]
## 🐛 Bug Report

When produce is run on a class (with `[immerable] = true`) that extends `Map`, it returns an instance of `Map` instead of the original class.

## Link to repro

#782 

## To Reproduce

Steps to reproduce the behavior: Create a class that extends `Map` and run `produce` on an instance of it. The result will be an instance of `Map` but will not be an instance of the original class that extended `Map`.

## Observed behavior

As described at the top of this report. 

## Expected behavior

When `produce` is run on an instance of a class `FooMap` that extends `Map`, the result is an instance of `FooMap`.
 
## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [x] I filed this report against the _latest_ version of Immer
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
`Map`, `Set` and arrays are treated internally very differently from other objects. Like any other native class Immer doesn't support subclassing them and/or making them immerable.

**Comment by mattsoulanille** [comment]
Thanks for the quick response! After looking at my code again, it turns out I don't actually need to draft the class I have that extends `Map`.

For anyone reading this in the future who _does_ need this to work, you can create an immerable class that implements the `Map` interface and wraps an instance of `Map` instead of extending `Map`.
