### ISSUE TITLE
Missing error 19 explaination

### ISSUE THREAD

**Issue by kotojo** [immerjs/immer#783]
## 🙋‍♂ Question
I was investigating a production error at work and ran into this error message. `[Immer] minified error nr: 19 ES5. Find the full error at: https://bit.ly/3cXEKWf`. When I follow that link it takes me to https://github.com/immerjs/immer/blob/master/src/utils/errors.ts, which does not have an error 19 description. It seems that error state was removed from the file a [few months ago ](https://github.com/immerjs/immer/commit/31684f262a9ec16d5aadb82156a78e81b98f65ef#diff-d3b5d70cc2b50e2667c6d9c24da50c9d14582360145b2ba8b171127e787f03d9). Is this no longer a valid error state, and we just need to update our version of immer, or was this oversight on removing that error code?

- **Immer version:** 7.0.7

**Comment by mweststrate** [comment]
It is basically the same error as 18, in other words in your case, you need
to call enableES5() to support older browsers that don't support proxies.

**Comment by kotojo** [comment]
Thanks for the explanation. Was just a bit hard to figure out cause the file my logs pointed to that I linked has error 17, 18, 20... and then I started questioning if I knew how to count a few times.
