### ISSUE TITLE
Migrating from 8 to 9

### ISSUE THREAD

**Issue by christiangoudreau** [immerjs/immer#784]
## 🙋‍♂ Question

Hi, 

I'm having a hard time typing the following snippet of code correctly with immer 9. Can anyone help me? (Type Action is from ngrx)

```
export class ReducerMap<T> {
    private readonly map: Map<string, ReducerFn<T, any>> = new Map();

    public set<A extends Action>(type: string, reducer: ReducerFn<T, A>): void {
        this.map.set(type, reducer);
    }

    public reduce(initialState: T, action?: Action): T {
        return produce<T>(initialState, (draft) => {
            if (action) {
                const reducer: ReducerFn<T, Action> | undefined = this.map.get(action.type);
                if (reducer) {
                    return reducer(draft, action);
                }
            }
        });
    }
}

export type ReducerFn<T, A extends Action> = (initialState: Draft<T>, action: A) => T | void;
```

## Environment

Immer 9

**Comment by mweststrate** [comment]
Please provide a code sandbox so that others can play with it as well.

**Comment by mweststrate** [comment]
Closing for the lack of a repro

**Comment by christiangoudreau** [comment]
It can be reproductable... you only have to copy past that code and typescript will give you the warning. IntelliJ give me the warning right away.

**Comment by mweststrate** [comment]
If you want to submit an issue you will have to set up a reproduction so everyone is looking at the same TS version, config and whatnot. Just follow the issue template which is there for a reason.
