### ISSUE TITLE
🙋‍♀️ TS type errors caused by inconsistent recipe return type

### ISSUE THREAD

**Issue by arimah** [immerjs/immer#787]
## 🙋 Question

Hello! In the process of upgrading from Immer 7 to 9, TypeScript began complaining about my types in ways that I believe are unintended, possibly incorrect.

A bit of background first. I have a moderately complex type, `Table<D>`, and an associated function `update` typed as follows:

```typescript
import { Draft } from 'immer'

type TableUpdater<D> = (draft: Draft<Table<D>>) => Table<D> | void

const update: <D>(table: Table<D>, updater: TableUpdater<D>) => Table<D>
```

The `update` function calls `produce` with the `TableUpdater` as the recipe, then processes the updated table to uphold some invariants, and finally returns the processed table. Crucially, the `TableUpdater` must be able to mutate the table *or* replace it altogether. With Immer 7 and 8, this approach works fine. With 9, the recipe is expected to return a `Draft<...>`.

The root cause seems to be in [the normal `produce`](https://github.com/immerjs/immer/blob/master/src/types/types-external.ts#L214-L226): the recipe return type is given as `ValidRecipeReturnType<D>`, where `D` is the *drafted* value. In contrast, [the curried producers](https://github.com/immerjs/immer/blob/master/src/types/types-external.ts#L187-L206) and [the produce-with-patches versions](https://github.com/immerjs/immer/blob/master/src/types/types-external.ts#L236-L251) all have `ValidRecipeReturnType<State>`/`ValidRecipeReturnType<Base>` – that is, *not* the drafted value.

**So, the meat of my question:** Is the recipe return type correct for the normal producer? Was it actually meant to say `Base` in place of the current `D`, or am I misusing Immer? It seems to me that `Base` would be more powerful, as you can then return `Base` or `D` as desired.

## Link to repro

A simplified reproduction of the working code with Immer 8:  
https://codesandbox.io/s/immer-types-v8-bx5iw?file=/src/index.ts

And the broken implementation with Immer 9:  
https://codesandbox.io/s/immer-types-v9-hfl2h?file=/src/index.ts

Interestingly, if I make `Data` non-generic, all the type issues seem to melt away:  
https://codesandbox.io/s/immer-types-v9-non-generic-cpv2f?file=/src/index.ts

## Environment

- **Immer version:** 9.0.1
- ~~[ ] Occurs with `setUseProxies(true)`~~ N/A
- ~~[ ] Occurs with `setUseProxies(false)` (ES5 only)~~ N/A

**Comment by mweststrate** [comment]
Your recipe should be `type TableUpdater<D> = (draft: Draft<Table<D>>) => Table<D> | void`, and then `produce(recipe)` should produce a `Table<D>`. Does that help?

**Comment by arimah** [comment]
Thank you for replying, @mweststrate. With the current typings, I would indeed have to declare the return type as `Draft<Table<D>>` (... and then `return castDraft(...)` in my recipe).

My question is more concerned with whether the current types are _correct_ or not. To me, it seems that allowing the non-drafted type in the return value would be more powerful and useful. That's also what several other overloads of `produce` already do. 🙂

**Comment by mweststrate** [comment]
There are many overloads and TS inference patterns that interact with each other here, so it is hard to discuss a specific case in isolation and knowing about the ramifications of a possible. 

Could I suggest you instead open a PR with with the proposed change and an example test case to be able to better determine the impact?

**Comment by Mario-Eis** [comment]
Here is the part in the documentation of immer.js, that is currently not working with the TS types:
https://immerjs.github.io/immer/return

`...However, it is allowed to just return draft.

It is also allowed to return arbitrarily other data from the producer function. But only if you didn't modify the draft. This can be useful to produce an entirely new state.`

Now its possible to return draft, but not a new State as Base.

**Comment by mweststrate** [comment]
@Mario-Eis would you mind creating a PR if you're proposing a solution? Touching a single overload has often effect on other use cases, so it will be much easier to discuss any solution using real code and tests.
