### ISSUE TITLE
Can I use immer to maintain immutability in a web worker?

### ISSUE THREAD

**Issue by riodeuno** [immerjs/immer#790]
## 🙋‍♂ Question

We're using `immer` for our redux store. We send the store data for some evaluations to a web worker. I was wondering if immer proxies maintain reference when serialized during postMessage? I can't find much in the google searches regarding this.

So if there hasn't been any changes in the object in the webworker,  is the following true? 
`Obj1 (UI thread) -> webworker -> (Obj2) UI thread === Obj1`

**Comment by mweststrate** [comment]
There is no shared memory afaik between webworkers and main, so no.
