### ISSUE TITLE
produceWithPatches(draft => nothing) puts the nothing symbol in the patches

### ISSUE THREAD

**Issue by dxinteractive** [immerjs/immer#791]
## Link to repro

https://codesandbox.io/s/immer-sandbox-forked-7htbs?file=/src/index.ts

## To Reproduce

```js
var {produceWithPatches, nothing, enablePatches} = require("immer")
enablePatches(true);
let [newState,patches] = produceWithPatches({abc: 123}, draft => nothing);
// newState is undefined <- correct
patches[0].value === nothing <- incorrect?
```

## Observed behavior

The immer `nothing` symbol can appear as the value in `"replace"` patches. Is this right? I thought the purpose of the `nothing` symbol was to simply give producers a way of differentiating between a mutating producer that implicitly returned `undefined`, and a returning producer that wants to output `undefined` as the next state. If that's true then perhaps the `nothing` symbol should not appear outside the producer itself.

## Expected behavior

Patches that are produced setting state to `nothing` should have a value of `undefined`.

## Environment

- 9.0.2
- [x] I filed this report against the _latest_ version of Immer
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Confirmed, reproduction: https://codesandbox.io/s/immer-sandbox-forked-fs9n5?file=/src/index.ts
