### ISSUE TITLE
Return new state from produce

### ISSUE THREAD

**Issue by ArielGueta** [immerjs/immer#799]
Hi, Thanks for this great library.

When we return a new state from the produce function, it'll still do the immer magic or it'll just return it as is?

I'm asking for performance reasons.

```ts
produce(state, draft => {
   return {...draft, somProp: { ...someProp, newProp: '' } }
})
```

Thanks.

**Comment by mweststrate** [comment]
See https://immerjs.github.io/immer/produce, https://immerjs.github.io/immer/return, https://immerjs.github.io/immer/performance

**Comment by ArielGueta** [comment]
Thanks. I read the section where you wrote:

> It is also allowed to return arbitrarily other data from the producer function. But only if you didn't modify the draft. This can be useful to produce an entirely new state

But it doesn't answer the question, whether immer will skip its magic, and will return it as it.

**Comment by mweststrate** [comment]
I don't think I get the question, but a proxy for the root object will always be created, that is the `draft`. 

For follow up questions please provide a more elaborate code example that explains the question, as your original example doesn't doesn't leverage Immer at all, did you watch the intro video on how Immer is supposed to be used? If you find yourself spreading the draft you're probably not using it correctly :).

**Comment by ArielGueta** [comment]
Ok, got you. Thanks for the answer!
