### ISSUE TITLE
[bug?] Immer 9, returning nothing does not leads to a typescript error, when it should

### ISSUE THREAD

**Issue by Bnaya** [immerjs/immer#802]
## 🐛 Bug Report

Immer 9 release notes advertise that it shouldn't be possible(typescript-wise) to return `nothing` / undefined from a `recipe` if it's not assignable to the target state.

## Link to repro
https://codesandbox.io/s/immer-9-type-weakness-0fjis?file=/src/App.tsx

## Observed behavior

See the error / missing error

## Expected behavior

See the error / missing error

## Environment

immer 9

- **Immer version:**
- [x] I filed this report against the _latest_ version of Immer
- this is typescript issue

**Comment by mweststrate** [comment]
@Bnaya  just double checking, this wasn't an issue in the end?

**Comment by Bnaya** [comment]
I was missing that there is the "nothing" symbol, and it's not just means undefined.
