### ISSUE TITLE
Use common.ts:ownKeys instead of Reflect.ownKeys in proxy

### ISSUE THREAD

**Issue by dhilgarth** [immerjs/immer#811]
## 🙋‍♂ Question

In https://github.com/immerjs/immer/blob/7a5382899bc8b0bf5e21972a1c7db63f53e1d697/src/core/proxy.ts#L130, `Reflect.ownKeys` is used directly.
This will fail for browsers that don't support `Reflect.ownKeys`.
It also fails in scenarios, where immer.js is used in an application that removes `Reflect.ownKeys`.

Is there a specific reason why you are not using the `ownKeys` from common.ts in the proxy?

## Environment
- **Immer version: 9.0.1**

**Comment by mweststrate** [comment]
There are no browsers, last time I checked, that do support Proxy, but not
Reflect. Which makes sense since the default traps of Proxy are expressed
in terms of Reflect.

**Comment by dhilgarth** [comment]
Okay, so not a problem with IE as it seems. Still, if an application incorrectly overwrites Reflect - as is the case with Xyleme - it will fail.

**Comment by dhilgarth** [comment]
My workaround currently looks like this:

```
export function ownKeys(target: any): string[] {

    let needsToDeleteOwnKeys = false;
    let needsToDeleteGetOwnPropertyDescriptor;
    if (!('ownKeys' in Reflect)) {
        Reflect.ownKeys =
            typeof Object.getOwnPropertySymbols !== 'undefined' ? obj => Object.getOwnPropertyNames(obj).concat(
                Object.getOwnPropertySymbols(obj) as any
            ) : Object.getOwnPropertyNames;
        needsToDeleteOwnKeys = true;
    }
    if (!('getOwnPropertyDescriptor' in Reflect)) {
        Reflect.getOwnPropertyDescriptor = function getOwnPropertyDescriptors(target: any) {
            const res: any = {}
            Reflect.ownKeys(target).forEach(key => {
                res[key] = Object.getOwnPropertyDescriptor(target, key)
            })
            return res
        }
        needsToDeleteGetOwnPropertyDescriptor = true;
    }
    const result = Object.keys(target);
    if (needsToDeleteOwnKeys) {
        delete Reflect.ownKeys;
    }
    if (needsToDeleteGetOwnPropertyDescriptor) {
        delete Reflect.getOwnPropertyDescriptor;
    }

    return result;
}
```

And then I'm using this `ownKeys` function instead of `Object.keys`

**Comment by mweststrate** [comment]
If your platform doesn't implement things faithfully you can try falling back to the ES5 mode. I don't know what Xyleme is, but if it breaks the standard implementation or incorrectly polyfills an API best take it up with them. There is little point in avoiding Reflect.ownKeys since by the same token any built API might be broken by Xyleme, and there is no way for us to tell. Closing here as this isn't a problem we can fix on our end, and there are two valid workarounds 1) use ES5 mode, 2) polyfill ownKeys yourself as done above.
