### ISSUE TITLE
Immer adds on functions to Set after going through reduce.

### ISSUE THREAD

**Issue by justinmwarner** [immerjs/immer#814]
## 🐛 Bug Report

When producing an object that contains a Set, the Set has functions/properties added to it that are not expected (ie: "delete", "clear", "add", "set")

## Link to repro

https://codesandbox.io/s/immer-playground-forked-b1rl5?file=/src/index.js

## To Reproduce

In repro above, after code has ran, notice that `before keys` has no extra properties. But `after keys` has several properties that were never explicitly added. `immer` seems to be adding this.

## Observed behavior

I wouldn't expect `immer` to change any objects in this way.

## Expected behavior

`after keys` would still print out `[]`

Our specific case though: `jest` deep equality check fails because the objects do not have the same values. We currently have a custom equality check override that looks like:

```ts
return {
  message: () =>
    this.utils.diff(modifiedActualScope, modifiedExpectedScope) ?? '',
  pass: this.equals(modifiedActualScope, modifiedExpectedScope, [
    immerSetHandler,
  ]),
}
```

```ts
/**
 * When an object that contains a set was passed through immer, it adds on additional properties.
 * This causes errors due to new functions, not new values. We only want to compare values though.
 * @param a object a to test
 * @param b object b to test
 * @returns If object a and object b are sets, then we ensure they both have the same values
 */
const immerSetHandler = (a, b) => {
  if (!(a instanceof Set) || !(b instanceof Set)) return;
  return a.size === b.size && [...a].every(value => b.has(value));
};
```

## Environment

- **Immer version:** 9.0.3
- [x] I filed this report against the _latest_ version of Immer

_Note: adding mutliple bugs that may be related, feel free to link/close as needed on your end, I just want to keep this clean_

**Comment by mweststrate** [comment]
Same issue as #816, unseen objects will be frozen by Immer to protect against accidental mutations. Since Set doesn't natively support `Object.freeze`, we 'kill' the mutative methods instead. To disable this behavior you can disable auto freezing. I suspect jest `toMatchObject` or `toMatch(Inline)Snapshot` won't fail on the difference btw.
