### ISSUE TITLE
Args get mutated after produce changes them.

### ISSUE THREAD

**Issue by justinmwarner** [immerjs/immer#816]
## 🐛 Bug Report

In the repro, you can see that when updating the draft state's array, we are updating the reference of the arg that's passed in as well.

## Link to repro

https://codesandbox.io/s/immer-playground-forked-xf3oh?file=/src/index.js

## To Reproduce

Pass an arg into produce and mutate it. See repro.

## Observed behavior

I would expect args passed into a produce to not update the payload, only the draft `state` object.

## Expected behavior

`newX` after `produce` should still be `[5, 6, 7]` and not have the `1` that was intended for `result`.

## Environment

- **Immer version:** 9.0.3
- [x] I filed this report against the _latest_ version of Immer

_Note: adding mutliple bugs that may be related, feel free to link/close as needed on your end, I just want to keep this clean_

**Comment by mweststrate** [comment]
At line 10 you are mutation not the state, but the action, for the reason that you set the state to become the action at line 9. So this is working as intended here. It is the original `state` that gets protected against mutations, for anything else that is passed in the normal JavaScript behavior applies.

**Comment by justinmwarner** [comment]
I think that's fair. Feel free to close this ticket according to the normal process you follow.

**Comment by mweststrate** [comment]
You can just hit close 😊
