### ISSUE TITLE
Migrate to GitHub Actions for CI

### ISSUE THREAD

**Issue by chrissantamaria** [immerjs/immer#823]
Following up on conversation in #820 - Travis CI currently isn't running on new commits, looks like migrating to GitHub Actions might be worthwhile.

Opening an issue for easier tracking, will try to work on this in the next few days

**Comment by mweststrate** [comment]
Done, should be fixed now!

**Comment by chrissantamaria** [comment]
@mweststrate sorry for the delay! Had to go out of town for the weekend, was going to take a look at this today but looks like you beat me to it 😅 

Just rebased #820 and it still looks like tests aren't running, just the Netlify deploy. Maybe just needs a new PR / commit?

Also interestingly, it looks like the release job tried to run on my fork after updating from upstream. It failed since I don't have semantic-release correctly configured - I wonder if there's way to disable that job on forks? https://github.com/chrissantamaria/immer/runs/2992235778

**Comment by mweststrate** [comment]
> Just rebased #820 and it still looks like tests aren't running, just the Netlify deploy. Maybe just needs a new PR / commit?

That is because Github doesn't run github actions automatically anymore for first-time contributors to a repo, so a maintainer has to kick it off manually for the first time. (Thank you bitcoin miners :-/)

> Also interestingly, it looks like the release job tried to run on my fork after updating from upstream. It failed since I don't have semantic-release correctly configured - I wonder if there's way to disable that job on forks? https://github.com/chrissantamaria/immer/runs/2992235778

I added a check, probably won't work the first time, lol :-P

**Comment by chrissantamaria** [comment]
[It actually did work](https://github.com/chrissantamaria/immer/runs/3001091938) 😄  thanks for the fix!
