### ISSUE TITLE
9.0.4 has no dist directory

### ISSUE THREAD

**Issue by muxfe** [immerjs/immer#827]
## 🐛 Bug Report

9.0.4 version has no dist directory, yarn install show errors:

Cannot find module '<...>/node_modules/immer/dist/index.js'. Please verify that the package.json has a valid "main" entry.

## Link to repro

<https://www.npmjs.com/package/immer/v/9.0.4>

## To Reproduce

`yarn add immer`

## Observed behavior

package "main" entry is invalid

## Expected behavior

has dist dir

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [x] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by hcharley** [comment]
I believe my ticket #826 is pointing to the same underlying problem you point to.

**Comment by mweststrate** [comment]
duplicate, closing
