### ISSUE TITLE
tsdx seems unmaintained now, replace it with something else?

### ISSUE THREAD

**Issue by pravi** [immerjs/immer#834]
## 🙋‍♂ Question

As seen in https://github.com/formium/tsdx/issues/1058 would you consider replacing it?

## Link to repro

Please provide a [CodeSandbox demo](https://codesandbox.io/s/immer-sandbox-6wijw) to clarify your question if possible. Typically, questions without minimal codesandbox demo won't be answered.

## Environment

We only accept questions against the latest Immer version.

- **Immer version:**
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Works fine for now, so, no.
