### ISSUE TITLE
After updating to immer 9, unit test start to fail. TypeError: Cannot assign to read only property 'id' of object '#<Object>'

### ISSUE THREAD

**Issue by junqdu** [immerjs/immer#838]
## 🐛 Bug Report
Updated immer 9.0.0 from 8.2.4. With no modification to the code base, some of the unit test start to fail. with the following error message:

 `TypeError: Cannot assign to read only property 'id' of object '#<Object>'`

Same thing happened when I tried to update @reduxjs/toolkit, from 1.5.1 to 1.6.1, because they also bumped immer to immer 9.

Also setAutoFreeze has been set to false in our Store.tsx.

## Link to repro

_A bug report without a reproduction is not a bug report. Failing to follow this templately is likely to result in an immediate close & lock of the issue._

Please provide either a [CodeSandbox demo](https://codesandbox.io/s/immer-sandbox-6wijw), or a PR with a unit test. In limited cases, a _minimal_ repository on GitHub is accepted as well.

## Observed behavior

A description of what behavior you observed and why you consider it faulty.

## Expected behavior

A clear and concise description of what you expected to happen instead.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [ ] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Sounds like a bug in one of your reducers, probably it has side effects.
The stack trace should point out where. If you want anybody to look into it
create a minimal reproduction first. Probably in the process you'll find
the cause of your bug as well.

**Comment by junqdu** [comment]
@mweststrate thanks
