### ISSUE TITLE
Try to ensure the minimum set of patches

### ISSUE THREAD

**Issue by unadlib** [immerjs/immer#840]
## 🚀 Feature Proposal

When using assignment, we can compare old and new values by shallow. If it is a new value for an object or an array, we always want to update the old value with a mutation rather than assigning a new value.

It can be an optional option, such as `enablePatches({ strict: true })`.

## Motivation

We can reduce the inaccuracy of the minimum set patch due to unnecessary assignments.

## Can this be solved in user-land code?

Request that can be solved in user-land code, or are out of scope of Immer (Immer is not a general data management library!) will typically be declined. We try to stay lean and mean here.

## Example

```ts
import produce from "immer"

const baseState = {
  list: [
    {
      title: 'Learn TypeScript',
      done: true,
    },
    {
      title: 'Try Immer',
      done: false,
    },
  ],
};

const nextState0 = produce(baseState, (draftState) => {
  draftState.list.push({ title: 'Tweet about it' });
  draftState.list[1].done = true; // 👍 good practice
});

const nextState1 = produce(nextState0, (draftState) => {
  draftState.list[1].done = true;
  const list = [...draftState.list];
  list.push({ title: 'Tweet about it' });
  draftState.list = list; // 👎 bad practice, and this requires a warning.
});
```

**Comment by mweststrate** [comment]
What kind of patches or mutations are the most efficient to handle downstream depends on many things, and Immer isn't opinionated about it. Nor does it provide the smallest set of patches, it provides the fasted set of patches, and further compressions is up to the user.  

From https://immerjs.github.io/immer/patches

 > Note: The set of patches generated by Immer should be correct, that is, applying them to an equal base object should result in the same end state. However Immer does not guarantee the generated set of patches will be optimal, that is, the minimum set of patches possible. It depends often on the use case what is considered 'optimal', and generating the optimal set of patches is potentially computationally very expensive. So in cases you might want to post process the generated patches, or compress them as explained below.
