### ISSUE TITLE
type error on Recipe for produce

### ISSUE THREAD

**Issue by sladiri** [immerjs/immer#843]
## 🙋‍♂ Question

With Immer 9 I get a type error, and I am not sure how to fix this.

I have a recipe of type: `<State, Message>(previousState: undefined | State, message: Message) => undefined | State`

### Use case
The idea is, that initially there is no state, and the recipe would create one. On subsequent calls, state might get mutated. The recipe might also do nothing (usually this happens only after state has been created).

## Link to repro

I left the message parameter out,
https://codesandbox.io/s/immer-sandbox-forked-mzl5l?file=/src/index.ts

## Environment

- **Immer version: 9.0.5**
- Typescript 4.3.5

**Comment by mweststrate** [comment]
Is this still relevant? In that case I don't understand the issue, if I remove the `State` cast it seems to compile fine?

**Comment by sladiri** [comment]
I'm afraid my example is unclear even to me now. I seemed to have missed that the recipe function uses the Draft wrapper type, and a quick test worked as expected now.
