### ISSUE TITLE
Bug in CodeSandbox demo

### ISSUE THREAD

**Issue by eval** [immerjs/immer#846]
## 🐛 Bug Report

This is a bug in the [CodeSandbox-demo](https://codesandbox.io/s/immer-usestate-ujkgg?file=/src/index.js) linked from the [React & Immer page](https://immerjs.github.io/immer/example-setstate#usestate--immer).

The rendered demo-page shows none of the 2 checkboxes being checked, and the sentence "Tasks left: 1".  
I would expect the sentence to be "Tasks left: 2".

The todos in the collection have the attribute `done`. The state of the checkbox though is based on an attribute named `finished`.
The following patch should fix the example:
```diff
diff --git a/src/index.js b/src/index.js
index cc78d65..7cc5e4b 100644
--- a/src/index.js
+++ b/src/index.js
@@ -58,7 +58,7 @@ const Todo = memo(({ todo, onToggle }) => (
   <li>
     <input
       type="checkbox"
-      checked={todo.finished}
+      checked={todo.done}
       onClick={() => onToggle(todo.id)}
     />
     {todo.title}

```

**Comment by mweststrate** [comment]
Fixed, thanks for noticing!

**Comment by CHOYSEN** [comment]
hey @mweststrate, seems this does not be fixed? https://codesandbox.io/s/use-immer-bvd5v?file=/src/index.js
