### ISSUE TITLE
Excluding a field from being maintained by immer

### ISSUE THREAD

**Issue by shayantabrizi** [immerjs/immer#855]
I found no way of excluding a field of a class from being maintained by immer. Particularly, we have getters and setters in a class which perform some actions on a class field (See the following code). It seems that immer considers two fields: the original one and the the field it generates based on the getter and the setter. However, this may result in inconsistencies and cause bugs. I want to be able to say immer to ignore the getters and setters and just take care of the original fields of the class.

```
class MyClass {
	public _atts: Array<number>;
	
	public get atts() {
		return _atts.filter(n => n > 1000);
	}

	public set atts(atts: Array<number>) {
		_atts = atts.map(n => n + 1000);
	}
}
```

**Comment by mweststrate** [comment]
> However, this may result in inconsistencies and cause bugs

Please open a fresh issue and follow the issue template. Your sample doesn't demonstrate a bug.

**Comment by shayantabrizi** [comment]
But, this isn't a bug report! It's a feature request.

**Comment by mweststrate** [comment]
In that case you should still explain how you think such a feature would be different from what is Immer doing currently (getters / setters are already supported in general) and give some concrete examples on how the behavior should change. You're currently state that getters don't behave like you want them to behave, but don't give any concrete examples of what would go wrong / undesirable. Making it impossible to evaluate the proposal, give counter examples, etc.
