### ISSUE TITLE
Replacing an object/array with a different but identical object/array is identified as a mutation

### ISSUE THREAD

**Issue by landisdesign** [immerjs/immer#856]
## 🐛 Bug Report

If I replace an object inside my state with another, identical object, it's identified as a mutation, even though all the primitives involved are identical. I can see why, technically, but experientially I'd expect Immer to be able to say, "Nothing's _really_ changed" and bypass this assignment.

I'm not sure if this is a bug, or a possible feature (perhaps adding some flag that allows this if there are reasons to make it opt-in only), but I thought I'd start by assuming that it should just work.

I'm sure this has come up before, but oddly couldn't find an issue that looked related when I searched. 🤷‍♂️ 

## Link to repro

https://codesandbox.io/s/jolly-cori-ruodf

## To Reproduce

1. Define an initial state object, with a nested, simple object as a property.
2. In a recipe, set that property with a clone of the original nested object.

## Observed behavior

The produced state is a different reference than the initial state, even though `JSON.stringify(initialState)` matches `JSON.stringify(producedState)`

## Expected behavior

When `JSON.stringify(initialState)` matches `JSON.stringify(producedState)`, `initialState` and `producedState` should reference the same object.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:** 9.0.6
- [x] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
To achieve what you are looking for here, a full deep comparision would be needed on every assignment, which would kill performance. If you stick to the mutative JS apis, things are generally seen as equal when you'd expect it. 

But note that your test is strange, as you forcefully create new objects where it isn't needed in initialisation, and you do create new test objects every render of the component. So this would be a better example: https://codesandbox.io/s/eloquent-goodall-b8w36.

The current records and tupels proposal in TC 39 will introduce structurally equal objects being reference equal as well, but that is something that needs to change in the language and Immer can't really help with.

**Comment by landisdesign** [comment]
Sigh... yeah, I thought that might be the case, but thought it might not hurt to check if y'all might have a trick up your sleeves, or if a flag of some kind were possible that would allow us to say "I'm willing to take the hit because I know this is small".

Thanks for the response!
