### ISSUE TITLE
Where is `draft` coming from in useState + Immer?

### ISSUE THREAD

**Issue by HansKre** [immerjs/immer#863]
I'm trying to understand how useState + Immer work.

I do not understand where `draft` in this [useState + Immer](https://immerjs.github.io/immer/example-setstate/#usestate--immer) example is coming from:

```js
const handleToggle = useCallback((id) => {
    setTodos(
      produce((draft) => {
        const todo = draft.find((todo) => todo.id === id);
        todo.done = !todo.done;
      })
    );
  }, []);
```

I am thinking about setting state always in terms of `setState(newState);` or alternatively as `setState(previousState => { /* calculate newState using previousState and return */ });`

Can someone help understand how `setTodos(produce((draft) => {}));` works?
Is it same as `setTodos(previousTodos => produce((previousTodos) => {}));`?

**Comment by mweststrate** [comment]
See https://immerjs.github.io/immer/curried-produce

**Comment by HansKre** [comment]
Not sure how pattern of having curried producers helps answer my question where `draft` is coming from ... 🤷‍♂️

**Comment by mweststrate** [comment]
`produce(draft => {})` creates a function `state => produce(state, draft => { })`. `setState` accepts a functions that goes `setState(baseState => newState)`. A curried produce has the same signature so you can do `setState(produce(draft => {}))` where the `draft` is hence the drafted version of `baseState`, and the returned object from `produce` becomes the newState.

**Comment by HansKre** [comment]
Amazing explanation. That helped a lot. Thank you!
