### ISSUE TITLE
Custom methods missing in Draft<T> when T implements Map

### ISSUE THREAD

**Issue by Yaojian** [immerjs/immer#864]
## 🐛 Bug Report

Custom methods defined in `T` is missing in `Draft<T>`  when `T` **implements** (not **extends**) `Map`.

Related to #502 , #781

## Link to repro

https://codesandbox.io/s/immer-sandbox-forked-3n014

## To Reproduce

```ts
  describe("When the custom map implements Map", () => {
    class CustomMap implements Map<number, string> {
      [immerable] = true;

      count(): number {
        return this.internalMap.size;
      }

      //#region Map<number, string> implementation
      // .....
      //#endregion
    }

    const base = new CustomMap();
    base.set(1, "first");

    it("the draft should be type compatible with CustomMap", () => {
      produce(base, (draft) => {
        // draft.count(); // TS2339: Property 'count' does not exist on type 'Map<number, string>'.
      });
    });

    it("draft can be hacked with type intersection", () => {
      let count: number | undefined = undefined;
      produce<CustomMap, Draft<CustomMap> & CustomMap>(base, (draft) => {
        count = draft.count(); //OK
      });
      expect(count).toBe(1);
    });
  });
```

## Observed behavior

`Draft<CustomMap>` is `Map<number, string>` without `CustomMap.count` defined.

## Expected behavior

`Draft<CustomMap>` should contain the `count` property.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [x] I filed this report against the _latest_ version of Immer
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
That is correct, Immer does not support customised array, Map or Set functionality beyond their standard functionality as per docs:

> Immer does not support exotic / engine native objects such as DOM Nodes or Buffers, nor is subclassing Map, Set or arrays supported and the immerable symbol can't be used on them.

https://immerjs.github.io/immer/complex-objects
