### ISSUE TITLE
Get notified when draft is modified 

### ISSUE THREAD

**Issue by derolf** [immerjs/immer#869]
## 🚀 Feature Proposal

I’d like to add a handler to a draft created by createDraft that is notified as soon as the draft is modified.

## Motivation

I am using drafts to edit immutable structures in svelte. For an autosave feature, I’d like to watch modifications as they happen.

Right now, you can only listen to patches when finishing a draft.

## Can this be solved in user-land code?

No.

## Example

Please provide an example for how this feature would be used.

**Comment by mweststrate** [comment]
You can check the `patches.length` generated at the end of produce. Patches are only computed when finalising the object, so aren't available in between.
