### ISSUE TITLE
Wrong types for generic tuple arrays

### ISSUE THREAD

**Issue by santiagocezar** [immerjs/immer#873]
## 🐛 Bug Report

When using produce with an array of generic tuples, the draft is typed as an array of drafts, not as a draft of an array. It also makes destructuring not infer the correct type
```ts
function genericSort<T extends [...any[]]>(arr: [id: number, ...values: T][], compare: (a: T, b: T) => number) {
  return produce(arr, draft => {
    //                ^^^^^
    // draft: Draft<[id: number, ...values: T]>[]
    // should be [id: number, ...values: T][] or Draft<[id: number, ...values: T][]>
    draft.sort((a, b) => {
      const [, ...valuesA] = a
      //          ^^^^^^^
      // valuesA: unknown[]
      // should be T
      const [, ...valuesB] = a
      return compare(valuesA, valuesB)
      //             ^^^^^^^
      // Argument of type 'unknown[]' is not assignable to parameter of type 'T'.
    })
  });
}

```

## Link to repro

[CodeSandbox demo](https://codesandbox.io/s/immer-generic-tuples-bttr7)

## To Reproduce

- call `produce` using a generic tuple array as the base 

## Observed behavior

draft type is `Draft<[id: number, ...values: T]>[]`, and tuples cannot be destructured

## Expected behavior

draft type should be `[id: number, ...values: T][]` or destructuring of Draft<[id: number, ...values: T]> should infer the correct types

## Environment

- **Immer version: 9.0.6**
- **Typescript version: 4.4.4**
- [x] I filed this report against the _latest_ version of Immer
- [x] ~Occurs with `setUseProxies(true)`~ shouldn't matter as this is a typing issue

**Comment by mweststrate** [comment]
Type inference, especially when generics are in play, is always quite imperfect and I recommend to explicitly type the `draft` argument in your case

**Comment by santiagocezar** [comment]
It does work doing that indeed, though in my case it was a lengthy type definition. 

Also, you mean it has more to do with typescript than with the library? Should I close the issue then?
