### ISSUE TITLE
applyPatches without enablePatches?

### ISSUE THREAD

**Issue by albertreed** [immerjs/immer#875]
## 🙋‍♂ Question

The only patch functionality required by my application is `applyPatches`. Patches themselves are generated separately. In my use-case `enablePatches` incurs a significant performance impact. 

Is there a way to get the functionality of `applyPatches` without having to call `enablePatches` or a way to somehow disable patches? Not understanding the internals, it seems possible that the performance penalty is generating the patches and not applying them.

## Environment

We only accept questions against the latest Immer version.

- **Immer version:** 9.0.1

**Comment by mweststrate** [comment]
enablePatches should not impact perf normally (only enableES5 does), could
you create a minimal reproduction demonstrating the problem?

**Comment by albertreed** [comment]
Sadly, I don't have a great way of isolating the performance issue down to a minimal cause. If you're confident `enablePatches` isn't causing a performance impact, I'll just assume the hit I was seeing was something else and move on. Thank you so much!
