### ISSUE TITLE
delete an element in the array, patches is an empty array

### ISSUE THREAD

**Issue by blinkcat** [immerjs/immer#879]
## 🐛 Bug Report

immer v9.0.7
just delete an element in the array, it is not difficult to reproduce the bug, please take a look at the following demo or code.

## Link to repro

[demo](https://stackblitz.com/edit/js-i8dgun?devtoolsheight=33&file=index.js)

## To Reproduce

```js
import { produceWithPatches, enablePatches } from 'immer';

enablePatches();

const [newState, patches, inversePatches] = produceWithPatches(
  [1, 2, 3],
  (draft) => {
    delete draft[2];
  }
);

console.log(newState, patches, inversePatches);
// output:
// [1, 2, undefined] [] []
```

## Observed behavior

As described above, patches and inversePatches are all empty

## Expected behavior

They should not be empty.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [x] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by bever1337** [comment]
Do I understand this prevents immer from creating sparse arrays with delete? I've spent the evening slowly removing pieces of my stack and API calls trying to find issues with sparse indices. I have no trouble creating sparse arrays using "proxied mutation"

```typescript
// produces [<empty>,42]
(draftState: Draft<{ values: [] }>) => {
  values[1] = 42;
}
```
Then:
```typescript
// produces [undefined, undefined]
(draftState: Draft<{ values: [] }>) => {
  delete values[1];
}
```

**Comment by bever1337** [comment]
Be careful using the stackblitz console to test the reproduction results. It runs a parser on the input data which casts holes to undefined. Opening the browser's devtools reveals the proper output.
