### ISSUE TITLE
How to detect or catch (throw warning) when trying to assign to read only property?

### ISSUE THREAD

**Issue by nikkizol** [immerjs/immer#882]
## 🙋‍♂ How to detect or catch (throw warning) when trying to assign to read only property?

I have a react app with class components, which are not covered with test. I get via props immutable object which was set before via immer produce and later on in the code I assign new values to the properties of this object, but I don't receive any warnings or errors, I only detect the error at the runtime... 

## Environment

We only accept questions against the latest Immer version.

- **Immer version:**8.0.1
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
cover it with tests and/or make sure to use `readonly` / `Immutable` types instead of mutable types.
