### ISSUE TITLE
Custom freeze function or excluding parts of a data structure from immutability

### ISSUE THREAD

**Issue by sladiri** [immerjs/immer#883]
## 🙋‍♂ Question

In older versions, I was able to instantiate Immer and provide a custom freeze function. Has this been removed, I cannot find it anymore?

I want to do this, because I would like to skip certain parts from being managed by Immer (seems to be what https://github.com/immerjs/immer/issues/855 is about).

My workaround now is to put the data inside a class (and omit the `immerable` symbol). Is this workaround a bad idea? (Obviously I am risking mutating the data by accident.)

**Comment by mweststrate** [comment]
Freezing can still be turned off: https://immerjs.github.io/immer/freezing, but not customised. However, if you want to customize it, creating your own utility wrapper around produce could be fairly straight forward

**Comment by sladiri** [comment]
Wrapping produce sounds much better than the class workaround I came up with, thank you!

We have been using Immer for about three years now, a great tool.

**Comment by sladiri** [comment]
Could you provide an example or rough explanation how you would wrap produce? I am not sure it is possible, I have the following use-case:
- A service has a state object.
- It has a function which mutates the state: `updateState(state, message) -> state'`
- When a message arrives, the service basically calls: `produce(draft -> updateState(draft, message))`

How can omit a particular (sub-) property inside the state object to not be frozen?

**Comment by mweststrate** [comment]
> How can omit a particular (sub-) property inside the state object to not be frozen?

mark it as immerable, or disable auto freeze around produce. But before doing all this trickery, the bigger question to ask is why you'd need to have parts of the trees unfrozen? That sounds both confusing and error prone. Note that if you need some mutable data structures like buffers or something, you could also associate them with the tree, by using e.g. a (Weak)Map instead of storing it *in* the tree.

**Comment by sladiri** [comment]
Thank you for the hints, this helps a lot.

The reason for not freezing leafs in our tree it is that those leafs are only sent to to a third party module, which wants to mutate the data inside the leafs. The current workaround is to clone the data before sending it to the module.

 I understand that this adds complexity, but maybe in this instance I want to take the risk.
