### ISSUE TITLE
Recursive data structures are not supported (call stack size exceeded)

### ISSUE THREAD

**Issue by kevinbeal** [immerjs/immer#884]
## 🐛 Bug Report

Maximum call stack size exceeded error occurs when you try to edit recursive structures (i.e. `a={x:a}`).

## Link to repro

https://stackblitz.com/edit/javascript-fwjtn6?file=index.js

## To Reproduce

1. Look at the console

## Observed behavior

`finalize` is trying to process the same object over and over again.

## Expected behavior

I'm not really sure what I expected. Maybe that there would be some sort of check in the `finalize` step to see if an object has already been finalized and not to re-finalize it. But I'm not familiar enough with the workings of Proxies or Immer to say anything meaningful about that.

## Environment

- **Immer version: 9.0.7**
- [x] I filed this report against the _latest_ version of Immer
- [x] Occurs with `setUseProxies(true)`
- [x] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
recursive structures are not supported indeed, only tree structures are, this could actively be checked against potentially, but that would require keeping a set of all objects in the tree / O(n) memory, so I think it is fine as is.
