### ISSUE TITLE
Investigate use of structuredClone API to boost performance on modern browsers.

### ISSUE THREAD

**Issue by bryanrideshark** [immerjs/immer#886]
# Use Structured Clone where appropriate to increase performance.

## 🚀 Feature Proposal

Modern browsers have recently exposed the "structuredClone" method to the Javascript runtime. This function can deeply clone objects in a highly optimized fashion, similar to doing `JSON.parse(JSON.stringify(yourObject))`, but much more efficient.

[Mozilla Docs on structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone)

It may be the case that the proxies employed by Immer prevent this library from gaining anything from this new API - but it would be great if we can make this library even better by using it.

## Motivation

Performance is fantastic - This might be able to boost performance.

## Can this be solved in user-land code?

No. This has to do with the inner workings of Immer produce.

## Example

Would like no change to the public API of Immer - just want potential performance improvements to be explored.

After briefly reading the source of immer, I noticed that we are indeed reading keys, copy/pasting them, by hand.
[shallowCopy](https://github.com/immerjs/immer/blob/8507692c72f454e9ca50dc91e263df12d4e41f5c/src/utils/common.ts#L165)

Looking at the source deeper, it's possible that we might _not_ gain much benefit from `structuredClone`. It _always_ does a deep clone of objects, though you can pass in a list of things you want to keep unchanged.

If implemeted, this would likely be an inversion of the model for Immer.Js - Instead of making a shallowCopy all the time, one would just mutate the original object and keep track of keys which aren't changed. Then, in making a clone of the object, you would need to pass in all of the unchanged objects to prevent excessive deep copying.

Performance benefits _might_ be found by using structuredClone, but we'd really have to see two versions and measure.

**Comment by mweststrate** [comment]
The point of Immer is to shallow clone wherever it can, not deep clone. As a result everything that is unchanged is structurally shared with the previous data, this saves both memory and helps a lot with optimizations that are based on memoization and reference equality for unchanged pieces of data (like React). So I don't think `structuredClone` is of much help in the context of Immer & immutable data. The primary benefit of structuredClone I see is that it would be easy and (relatively) cheap to to create defensive copies of _mutable_ data.
