### ISSUE TITLE
Immer is modifying baseObject and not throwing exception for nested un-draftable objects.

### ISSUE THREAD

**Issue by keepRunning** [immerjs/immer#890]
## 🐛 Bug Report

Based on the documentation, object of type 'class' needs to have [immerable] set to true to be handled.
When [immerable] is not set, it should throw an exception.

However, if the baseObject is plain javascript/(class with immerable set to true) and the nested object is un-draftable(class without immerable), then the baseObject itself is modified and returned without exception.

## Link to repro
https://codesandbox.io/s/immer-sandbox-error-forked-rry8q

## Observed behavior

BaseObject is modified and returned. No exception is thrown.

## Expected behavior

Exception should be thrown.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version: 9.0.7**
- [x] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
That is working as expected, if a class is not marked immerable, it behaves like it would normally do in JavaScript. The fact that it is referred to by a draft is unrelated to that.

**Comment by keepRunning** [comment]
Thanks for the clarification.
It will be difficult for us to adopt immer without a exception failure, as we have a highly nested class structure and multiple developers introducing new changes.
