### ISSUE TITLE
Export statement may only appear at top level in file...

### ISSUE THREAD

**Issue by thanhlk123** [immerjs/immer#892]
Hi ad.
I use immer version 5.3.4, and my project base on version 0.61.5
From 11/1/2022, I regularly cannot build app. Even if i upgrade immer to the latest version, this issue still occurs.
The following error occurs: "error libs/immer/dist/immer.module.js: Export statement may only appear at top level in file libs/immer/dist/immer.module.js at 1729:2".
Please help me solve this issue.
<img width="1034" alt="Screen Shot 2022-01-12 at 16 12 42" src="https://user-images.githubusercontent.com/49853430/149098432-fc1de88c-dfc7-4e0a-819f-e8f4e53507e0.png">

**Comment by mweststrate** [comment]
Please provide a minimal reproduction as this probably relates to build set
up and we cant debug screenshots

**Comment by jungRoit** [comment]
I'm having the same issue when building my react-native android app.
I'm using dimmer version 5.3.6

**Comment by mweststrate** [comment]
Closing for the lack of a reproduction and opening an issue on 4 major versions back :).

**Comment by arjuntraj** [comment]
@thanhlk123 am also facing the same issue, any solutions?
