### ISSUE TITLE
Proxies cause issues with replacing array item properties.

### ISSUE THREAD

**Issue by developdeez** [immerjs/immer#899]
I've been trying to properly return a new object with the text changed using immer.
My goal is to use the msg ID to change the text. The trouble is immer returns a proxy and it doesnt save to the cache properly. any ideas?

    
```
      const newData = produce(prev, draftState => {
        if(newMessageSubscribe.type==="mod"){
          const foundIndex = prev.getMessages.messages.findIndex((x) => x.id == newMessageSubscribe.id);
          draftState.getMessages.messages[foundIndex].text = "text";
        }
      });
      
      return newData;
```

- **Immer version:**
- [X] I filed this report against the _latest_ version of Immer
- [X] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Please follow the issue template. It is unclear what above code is to do, whether it does or doesn't work, and what all the variables represent.

**Comment by fantasticsoul** [comment]
hi, bro, can u just try limu to see if it has the same problem?
