### ISSUE TITLE
Can I safely read from `draft`?

### ISSUE THREAD

**Issue by ablakey** [immerjs/immer#903]
Is it safe to read from `draft`?

My understanding is that it _should_ work and may have performance consequences because of the `Proxy` indirection, but otherwise it's perfectly fine to read draft?

I ask because I've created an abstraction where my functions have access to `draft` but not `previousState`.  I know I can use `original(draft)` but I was wondering about just reading from draft directly.

**Comment by mweststrate** [comment]
Yes, as long as your recipe runs
