### ISSUE TITLE
the Draft<T> could not use the keyof T type

### ISSUE THREAD

**Issue by Rey-Wang** [immerjs/immer#918]
you can see an code example here:
[code sandbox](https://codesandbox.io/s/typescript-playground-export-forked-jf764x?file=/index.ts)

```
function ChangeState<T extends Record<string, any>, M extends keyof T>(
  state: T,
  field: M,
  value: T[M]
) {
  return produce(state, (draftState) => {
    draftState[field] = value;
    // Type 'M' cannot be used to index type 'Draft<T>'
  });
}
```
the `keyof T` should be used by `Draft<T>`

**Comment by mweststrate** [comment]
See `castDraft` https://immerjs.github.io/immer/typescript#cast-utilities

**Comment by p2k** [comment]
I'm sorry but how does `castDraft` help here? `draftState` is already of the type `Draft<T>` using the cast would produce `Draft<Draft<T>>`.

I have a similar problem:
```
function ChangeStringState<M extends string>(
  state: Record<M, string>,
  field: M,
  value: string,
) {
  return produce(state, (draftState) => {
    draftState[field] = value;
    // Type 'M' cannot be used to index type 'Draft<Record<M, string>>'
  });
}
```

**Comment by lucafanselau** [comment]
Yeah same here, is there a way to use a generic `keyof M` parameter to index the Draft type?

**Comment by weilbith** [comment]
Same issue here. Having a record with generic key type make `immer` fail. Interestingly enough this is not just a type error, but `produce` provides no patches at all. I basically ignored the errors for a moment and tries to use `produceWithPatches`. But the list of returned patches is just empty. In result the produced record is actually changed, but is the same (according to `Object.is`).

**Comment by mweststrate** [comment]
usually these kind of problems take a bit of fiddling around until it "clicks", for typescript like sometimes it helps to type the draft param itself. Or if you use a mutable type definition anyway, there is no `Draft` wrapper needed anyway (it is only there to make sure that readonly types become assignable in producers), so in that case you can just cast to your real type.

Beyond that hard to give advice on specific cases without a sandbox, to fiddle with. 

> But the list of returned patches is just empty

Typescript types have no influence on runtime behaviors, so probably two things are being conflated here. Best open a separate issue. 

I'm locking the issue as it now discusses three different cases and OP is 1.5 years old.
