### ISSUE TITLE
"Cannot perform 'getPrototypeOf' on a proxy that has been revoked" error in simple reducer sandbox example.

### ISSUE THREAD

**Issue by laurencefass** [immerjs/immer#925]
## 🐛 Bug Report

Ive created a very simple immer sandbox comparing immutable and mutable reducers by wrapping the mutable reducer (i.e. a reducer directly mutating state) in an immer produce function. The unwrapped (immutable) reducer works entirely correctly. The immer wrapped (mutable) reducer also updates state correctly but throws an error on attempting to execute console.log. I wrote this sandbox to prove a more complex example (too complex for a sanbox) causing a similar error, and I hope that fixing this will also fix my other issue.

```
TypeError: Cannot perform 'getPrototypeOf' on a proxy that has been revoked
```

This is the most basic reducer example I can think of so Im not sure whats going wrong, or if this is a bug.

## Link to repro

[https://codesandbox.io/s/react-typescript-forked-c2dc09](url)

## To Reproduce

run the code.
increment1 and note the console log works correctly
increment2 and note the repeated error

## Observed behavior

see above

## Expected behavior

console.log should work correctly inside the mutable reducer

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [x ] I filed this report against the _latest_ version of Immer
- [x ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
console.log is an async process that will read your draft only after the
producer has already finished. So either copy / stringify the draft first,
or print the result instead of the draft

**Comment by laurencefass** [comment]
hi thanks for your attention. im not sure if i am interpreting you correctly, but

```
console.log("immutablereducer", {...state});
```
and
```
console.log("immutablereducer", JSON.stringify(state));
```
both result in the same error message
```
TypeError: Cannot perform 'getPrototypeOf' on a proxy that has been revoked
```
i need the log inside the reducer for debugging. my real example is more complex than this and i need to check state changes.
