### ISSUE TITLE
Possible breaking change in package exports in v9.0.13

### ISSUE THREAD

**Issue by markerikson** [immerjs/immer#937]
## 🐛 Bug Report

We just had a user file a Redux Toolkit bug report saying that as of Immer v9.0.13, RTK fails to initialize correctly, with a classic `Object(...) is not a function` error message

https://github.com/reduxjs/redux-toolkit/issues/2315

![image](https://user-images.githubusercontent.com/39653866/167955710-00aef1ac-e2fc-474b-99fc-247b417faa58.png)

Looking at the changes in https://github.com/immerjs/immer/compare/v9.0.12...v9.0.13 , I see that there was a recent PR changing how Immer does its exports:

https://github.com/immerjs/immer/pull/921

This seems like a likely candidate for causing this kind of problem.

Note that this change was _not_ called out in the 9.0.13 release notes, and also seems like it's a much bigger change than a "patch"-level release.  (FWIW I've been advised that changes to `exports` in `package.json` probably justify being breaking majors.)

## Link to repro

Don't have a repro yet - the end user just reported this a few minutes ago.

## Observed behavior

It looks like Immer's exports have potentially changed, depending on the build/run environment.  (Don't know details on the end user's environment yet).

## Expected behavior

Immer's imports load cleanly.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [x] I filed this report against the _latest_ version of Immer

Rest of user environment is unknown, have asked for more details.

**Comment by hirbod** [comment]
Your bundler most likely does not understand `mjs`. Had similar issues with React-Native and had to add `mjs` to `sourceExts` to make `Metro` happy

**Comment by markerikson** [comment]
FWIW, it isn't "my" bundler :)  I'm a Redux Toolkit maintainer (RTK relies on Immer), and one of our users reported the bug against RTK.

Tbh this is the sort of thing that scares _me_ about trying to change package export setup for RTK itself, and why I refuse to touch our setup until we're ready for a major.

**Comment by hirbod** [comment]
So it's your users bundler :)
But I'm totally with you on that. I wouldn't just do something like that in a minor release either.

And here a quote by one of the collaborators (@mweststrate)
> Merging as is. Typically whenever I touch something ESM related, the skies come tumbling down, so brace yourselves. 
https://github.com/immerjs/immer/pull/921#issuecomment-1087709203

Well, guess he has been right :)

**Comment by f-roland** [comment]
related to https://github.com/immerjs/immer/issues/938

this is indeed a breaking change a big a problem for library maintainers.

We have a build system where we generate projects on the fly with a framework that has reduxjs/toolkit as a dependency (and therefore immer). All our builds on our existing versions of our framework are now broken because of this. This should definitely not be published as a patch update :/

I hope it will be rolled back ASAP and included in the next major version instead as @hirbod suggested

**Comment by f-roland** [comment]
no worries @mweststrate , you reacted promptly so that's good :)
Do you have a flow to release in npm's `next` channel ? that's how I would test this in real conditions before "pushing it in the wild"

**Comment by markerikson** [comment]
Wanted to follow up on this in two ways:

- I'm currently working on migrating Redux Toolkit 2.0 alpha to be a full ESM `exports`-based package (with CJS fallback).  Current WIP PR is here: https://github.com/reduxjs/redux-toolkit/pull/3095 .  I think I've got it _mostly_ working as far as the package structure.
- That said, where I'm running into trouble is actually with packages that export both a default value _and_ named values, such as `redux-thunk` and Immer.  (Interestingly, this seems to primarily be a problem with how Jest imports things.)  I also maintain `redux-thunk`, so I can fix that one myself, but Immer is a separate issue.

It might be worth re-considering this set of changes for an Immer 10.0?
