### ISSUE TITLE
React Native compilation problem

### ISSUE THREAD

**Issue by Nadrenfox** [immerjs/immer#938]
`Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
error While trying to resolve module `immer` from file `C:\Users\nadre\Documents\Proyectos\ocho-react\node_modules\@reduxjs\toolkit\dist\redux-toolkit.cjs.production.min.js`, the package `C:\Users\nadre\Documents\Proyectos\ocho-react\node_modules\@reduxjs\toolkit\node_modules\immer\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\Users\nadre\Documents\Proyectos\ocho-react\node_modules\@reduxjs\toolkit\node_modules\immer\dist\immer.esm.mjs`. Indeed, none of these files exist:

  * C:\Users\nadre\Documents\Proyectos\ocho-react\node_modules\@reduxjs\toolkit\node_modules\immer\dist\immer.esm.mjs(.native|.android.js|.native.js|.js|.android.json|.`
I can't compile my code 

I was trying to compile in react native redux tookit that uses immer and it seems is not working anymore for some reason.

**Comment by hirbod** [comment]
I had the same problem, this is most likely related to the ESM changes that many packages start doing.
You need to change your `metro` config

```ts
// Learn more https://docs.expo.io/guides/customizing-metro
const {
  getDefaultConfig
} = require('expo/metro-config');
const path = require('path');

const config = getDefaultConfig(__dirname);

// Monorepo
const projectRoot = __dirname;
const workspaceRoot = path.resolve(__dirname, '../..');

config.watchFolders = [workspaceRoot];
config.resolver.nodeModulesPath = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(workspaceRoot, 'node_modules')
];

config.resolver.sourceExts.push('mjs'); // this is the required fix

module.exports = config;
```

Note that my metro config is based off Expo, if you're using bare RN you'll need to add `mjs` to your sourceExts.

I still think that immerjs should also support react-native ootb, there are many issues in this direction lately from many packages, like uSES, react-query, apollo. etc.

**Comment by f-roland** [comment]
Is there a plan to do anything about this ? 

we have a framework that uses reduxjs/toolkit as a dependency. With this, all our earlier versions are now breaking in new projects, unless people add a specific resolution for immer version, which is quite problematic

**Comment by HarshitMadhav** [comment]
+1 facing this same issue

**Comment by 826505523** [comment]
+2 facing this same issue

**Comment by HarshitMadhav** [comment]
https://github.com/immerjs/immer/pull/939
This issue has been fixed here

**Comment by hirbod** [comment]
I can confirm that the fix is working

**Comment by f-roland** [comment]
yes, this can be closed, #939  was merged and is available in 9.0.14

**Comment by HarshitMadhav** [comment]
I think we can close this issue as of now as it has been fixed.

**Comment by Nadrenfox** [comment]
Yup, closing it now, thank you all for help!
