### ISSUE TITLE
Example of Syncing Immer Patches between Client and Server

### ISSUE THREAD

**Issue by BrianHung** [immerjs/immer#957]
## 🙋‍♂ Question

Would anyone have an example of how to properly sync immer patches between client and server? Specifically, wondering how to manage patches and snapshots, offline state and possibly a very crude multiplayer?

I've seen some resources before

https://egghead.io/lessons/react-create-a-simple-websocket-server-to-distribute-patches-from-immer
https://github.com/webstudio-is/immerhin

but extending that to more robust realtime sync isn't addressed like in

https://github.com/ProseMirror/prosemirror-collab/blob/master/src/collab.ts
https://github.com/ProseMirror/website/tree/master/src/collab

**Comment by mweststrate** [comment]
Some concepts are worked out here:
***@***.***/distributing-state-changes-using-snapshots-patches-and-actions-part-1-2811a2fcd65f
/

**Comment by mweststrate** [comment]
Apologies, original message got garbled, URL should be: https://medium.com/@mweststrate/distributing-state-changes-using-snapshots-patches-and-actions-part-1-2811a2fcd65f
