### ISSUE TITLE
version in package.json

### ISSUE THREAD

**Issue by sergiomarotco** [immerjs/immer#973]
## 🙋‍♂ Question

Is version in [package.json](https://github.com/immerjs/immer/blob/master/package.json) is correct?
I have information that the current version is vulnerable, but the current version is not 9.0.0-beta.1 as determined by Snyk based on the current package.json:
![image](https://user-images.githubusercontent.com/29877074/187363371-73da75e6-0802-4648-8b2a-0f6773b49503.png)

#972

**Comment by mweststrate** [comment]
No, semantic-release determines the version during the release process, but doesn't commit it back into the package.json. Instead look at the tags in the repository.
