### ISSUE TITLE
Array splice does not work

### ISSUE THREAD

**Issue by mwisnicki** [immerjs/immer#983]
## 🐛 Bug Report

It looks like `[].splice` does not work?

I couldn't find a reference list of supported array methods but since push/pop works I assumed other methods should too.

## Link to repro

https://codesandbox.io/s/immer-splice-broken-2p4t6b?file=/src/index.js

## To Reproduce

```js
import { produce } from "immer";

const arr = () => [1, 2, 3, 4, 5];

console.log("case 1 array:", arr().splice(3));
console.log("case 1 immer:", produce((a) => void a.splice(3))(arr()));

console.log("case 2 array:", arr().splice(-2));
console.log("case 2 immer:", produce((a) => void a.splice(-2))(arr()));
```

## Observed behavior

```
case 1 array: 
(2) [4, 5]
case 1 immer: 
(3) [1, 2, 3]
case 2 array: 
(2) [4, 5]
case 2 immer: 
(3) [1, 2, 3]
```

## Expected behavior

No diff

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [x] I filed this report against the _latest_ version of Immer

**Comment by mweststrate** [comment]
Your base case prints what is being removed, while in the immer test case
you print what is remaining.

**Comment by mwisnicki** [comment]
Thanks, that was a dumb mistake 😅
