### ISSUE TITLE
On value set scenario, copy_ can be null

### ISSUE THREAD

**Issue by timtong1982** [immerjs/immer#984]
## 🐛 Bug Report

If your bug report involves classes, check the [docs](https://immerjs.github.io/immer/docs/complex-objects) on how classes are handled first. For patches, don't file issues if they are not optimal, only if they are incorrect.

https://github.com/immerjs/immer/blob/e28b53f2d12696954b1f0125494498e34d77a3df/src/core/proxy.ts#L150

<img width="378" alt="image" src="https://user-images.githubusercontent.com/25381018/195697677-c49919ab-acee-4f7a-8fdf-540286e5b936.png">

## Link to repro

a repo is a little complex, I have a customized redux, I give the draftState for each of the child reducer to process, but if I use current to give the non-draft state for child reducer to process, this issue doesn't exist.

_A bug report without a reproduction is not a bug report. Failing to follow this templately is likely to result in an immediate close & lock of the issue._

Please provide either a [CodeSandbox demo](https://codesandbox.io/s/immer-sandbox-6wijw), or a PR with a unit test. In limited cases, a _minimal_ repository on GitHub is accepted as well.

## Observed behavior

A description of what behavior you observed and why you consider it faulty.

## Expected behavior

A clear and concise description of what you expected to happen instead.

## Environment

We only accept bug reports against the latest Immer version.

- **Immer version:**
- [x] I filed this report against the _latest_ version of Immer
- [ ] Occurs with `setUseProxies(true)`
- [ ] Occurs with `setUseProxies(false)` (ES5 only)

**Comment by mweststrate** [comment]
Closing the issue for the lack of reproduction, as indicated in the issue template. Feel free to open a fresh one once a reproduction is available (or feel free to link one here, but not sure if that triggers the right notifications)

**Comment by mweststrate** [comment]
Closing the issue for the lack of reproduction, as indicated in the issue template. Feel free to open a fresh one once a reproduction is available (or feel free to link one here, but not sure if that triggers the right notifications)
